### ISSUE TITLE
Unable to determine Swift version for the following pods

### ISSUE THREAD

**Issue by MallikarjunH** [SVProgressHUD/SVProgressHUD#1000]
[!] Unable to determine Swift version for the following pods:

- `HexColors` does not specify a Swift version and none of the targets (`FaveoHelpdeskPro_ObjC`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.

![Screenshot 2019-11-04 at 3 45 08 PM](https://user-images.githubusercontent.com/27955299/68114126-49de0e00-ff1b-11e9-9bd4-4244f3894be6.png)

**Comment by honkmaster** [comment]
This is an issue of HexColors, not SVProgressHud.
