### ISSUE TITLE
The HUD position doesn't centralize on iOS 13

### ISSUE THREAD

**Issue by nanyoliveira** [SVProgressHUD/SVProgressHUD#1002]
Whenever the Loading show, it doesn't show in the middle of the screen for ios 13, works fine in the previous OS. It stays in the top left of the screen, even though the overlay works fine.

**Comment by prodia** [comment]
Same problem :(

**Comment by nanyoliveira** [comment]
hey @prodia! I sent a pull request with the fix that I found, and I am just waiting for the review. 

The fix I found is: If you go to the file SVProgressHUD/SVProgressHUD.m in the pods and then just change this line:
`CGRect orientationFrame = self.bounds`
to :
`CGRect orientationFrame = [[UIScreen mainScreen] bounds];`

It will fix the issue in your local project, but it will go away when you update, case this is not fixed.

**Comment by kinhhopbi0** [comment]
> hey @prodia! I sent a pull request with the fix that I found, and I am just waiting for the review.
> 
> The fix I found is: If you go to the file SVProgressHUD/SVProgressHUD.m in the pods and then just change this line:
> `CGRect orientationFrame = self.bounds`
> to :
> `CGRect orientationFrame = [[UIScreen mainScreen] bounds];`
> 
> It will fix the issue in your local project, but it will go away when you update, case this is not fixed.

not working for me

**Comment by slizeray** [comment]
I did a pull request for this issue in august

https://github.com/SVProgressHUD/SVProgressHUD/pull/978

Is this lib still maintained?

**Comment by HoangDinhTho** [comment]
same issue now

**Comment by iHardikTrivedi** [comment]
Try this solution:
[[SOLUTION]](https://github.com/SVProgressHUD/SVProgressHUD/issues/1013#issuecomment-567335032)

**Comment by honkmaster** [comment]
![Simulator Screen Shot - iPhone 11 Pro - 2020-01-04 at 09 47 14](https://user-images.githubusercontent.com/1380397/71763063-b2c01300-2ed7-11ea-98cf-7a485fb071a3.png)

I can not reproduce this issue with the demo application.

**Comment by slizeray** [comment]
@honkmaster You need to adopt the new iOS 13 UIScene API

https://developer.apple.com/documentation/uikit/uiscene

**Comment by alquhait** [comment]
> hey @prodia! I sent a pull request with the fix that I found, and I am just waiting for the review.
> 
> The fix I found is: If you go to the file SVProgressHUD/SVProgressHUD.m in the pods and then just change this line:
> `CGRect orientationFrame = self.bounds`
> to :
> `CGRect orientationFrame = [[UIScreen mainScreen] bounds];`
> 
> It will fix the issue in your local project, but it will go away when you update, case this is not fixed.

Worked with me, Thanks a lot

**Comment by blavkjay** [comment]
I solved this problem by creating a window  and a singleton in my appDelegate:

```
 static var standard: AppDelegate {
        return UIApplication.shared.delegate as! AppDelegate
    }

```
Then in my SceneDelegate:
 ```
func scene(_ scene: UIScene, willConnectTo session: UISceneSession, options connectionOptions: UIScene.ConnectionOptions) {
        guard let _ = (scene as? UIWindowScene) else { return }
        AppDelegate.standard.window = window

    }

```

**Comment by ramakrishna013** [comment]
@blavkjay Thanks for the solution. This is working for me.

**Comment by AlexTikhomirov** [comment]
Thank you, very good.

**Comment by nitinumaretiya123** [comment]
> I solved this problem by creating a window and a singleton in my appDelegate:
> 
> ```
>  static var standard: AppDelegate {
>         return UIApplication.shared.delegate as! AppDelegate
>     }
> ```
> 
> Then in my SceneDelegate:
> 
> ```
> func scene(_ scene: UIScene, willConnectTo session: UISceneSession, options connectionOptions: UIScene.ConnectionOptions) {
>        guard let _ = (scene as? UIWindowScene) else { return }
>        AppDelegate.standard.window = window
> 
>    }
> ```

Many Many Thanks bro

**Comment by nitinumaretiya123** [comment]
> I solved this problem by creating a window and a singleton in my appDelegate:
> 
> ```
>  static var standard: AppDelegate {
>         return UIApplication.shared.delegate as! AppDelegate
>     }
> ```
> 
> Then in my SceneDelegate:
> 
> ```
> func scene(_ scene: UIScene, willConnectTo session: UISceneSession, options connectionOptions: UIScene.ConnectionOptions) {
>        guard let _ = (scene as? UIWindowScene) else { return }
>        AppDelegate.standard.window = window
> 
>    }
> ```

Many Many Thanks @blavkjay

**Comment by hayjay** [comment]
> I solved this problem by creating a window and a singleton in my appDelegate:
> 
> ```
>  static var standard: AppDelegate {
>         return UIApplication.shared.delegate as! AppDelegate
>     }
> ```
> 
> Then in my SceneDelegate:
> 
> ```
> func scene(_ scene: UIScene, willConnectTo session: UISceneSession, options connectionOptions: UIScene.ConnectionOptions) {
>        guard let _ = (scene as? UIWindowScene) else { return }
>        AppDelegate.standard.window = window
> 
>    }
> ```

Many thanks, this worked like a charm!

**Comment by autm-syl** [comment]
Add this line `(UIApplication.shared.delegate as? AppDelegate)?.self.window = window` at the function `scene(_ scene: UIScene, willConnectTo session: UISceneSession, options connectionOptions: UIScene.ConnectionOptions)` in file `SceneDelegate`. Like that: 
`func scene(_ scene: UIScene, willConnectTo session: UISceneSession, options connectionOptions: UIScene.ConnectionOptions) {
        (UIApplication.shared.delegate as? AppDelegate)?.self.window = window
       //...  
    }`

**Comment by JPAppyAudio** [comment]
> Add this line
> `(UIApplication.shared.delegate as? AppDelegate)?.self.window = window` at the function
> `scene(_ scene: UIScene, willConnectTo session: UISceneSession, options connectionOptions: UIScene.ConnectionOptions)` in file `SceneDelegate`. Like that:
> 
> `func scene(_ scene: UIScene, willConnectTo session: UISceneSession, options connectionOptions: UIScene.ConnectionOptions) {
> 
> ```
>     (UIApplication.shared.delegate as? AppDelegate)?.self.window = window
>    //...  
> 
> }`
> ```

This Worked for me thanks!!

**Comment by rajanaat** [comment]
@blavkjay Thanks for the solution.

**Comment by sshahidaslamm** [comment]
> hey @prodia! I sent a pull request with the fix that I found, and I am just waiting for the review.
> 
> The fix I found is: If you go to the file SVProgressHUD/SVProgressHUD.m in the pods and then just change this line:
> `CGRect orientationFrame = self.bounds`
> to :
> `CGRect orientationFrame = [[UIScreen mainScreen] bounds];`
> 
> It will fix the issue in your local project, but it will go away when you update, case this is not fixed.

Worked For me as Well !
