### ISSUE TITLE
Crash whenever calling any SVProgressHUD method

### ISSUE THREAD

**Issue by bstillitano** [SVProgressHUD/SVProgressHUD#1004]
When calling any method (show/dismiss) I get the following crash when building for 13.2.2 on Xcode 11.2.1

dispatch_once(predicate, block); crash

**Comment by LeeJoey77** [comment]
i get the crash too, Xcode 11.2.1, iPhone 13.2.2

**Comment by enriqueg** [comment]
Crashing all the time, please fix it!

**Comment by alirzaeram** [comment]
I couldn't found any answer for that. The only way to solve this problem is to support iOS 12 too.
In Xcode 11 you should make this changes to support iOS 12:
1 Change deployment target to iOS 12.
2 Replace the AppDelegate's methods with AppDelegate of Xcode 10 
3 Remove SceneDelegate.
4 Remove Application Scene Manifest in your info.plist.

**Comment by bstillitano** [comment]
That is a terrible solution. That would remove any and all Catalina support
and would require you to support a no longer officially supported version
of the operating system.

Strongly recommend not doing this.

**Comment by 969990431** [comment]
So how to solve this problem?

**Comment by ppearson111** [comment]
Also seeing this dispatch_once crash issue but in AppDelegate didFinishLaunchingWithOptions, I set some global configuration settings for the HUD, such as `SVProgressHUD.setMaximumDismissTimeInterval(1.0)` 

_Any_ call to SVProgressHUD causes the dispatch_once crash.  XCode 11.2.1, iOS deployment target 13.0.  

Any updates or work-arounds for this issue? thanks!

**Comment by iHardikTrivedi** [comment]
Try this solution:
[[SOLUTION]](https://github.com/SVProgressHUD/SVProgressHUD/issues/1013#issuecomment-567335032)

**Comment by engrinzamam** [comment]
Following the same issue need solution of this.
