### ISSUE TITLE
iOS13 Show之后，如果在0.1s内关闭HUD，会显示HUD四边的黑色线条。

### ISSUE THREAD

**Issue by dragonstark** [SVProgressHUD/SVProgressHUD#1005]
有些请求过快，HUD消失的时候会出现黑框，经过粗略测试，0.2s以上就不出现。0.1s以内不管是SVProgressHUDStyleLight还是SVProgressHUDStyleDark，都会出现。

![IMG_2622](https://user-images.githubusercontent.com/18611506/69031680-a2320700-0a15-11ea-8c38-b196fe011dd3.PNG)
![IMG_2623](https://user-images.githubusercontent.com/18611506/69031681-a2ca9d80-0a15-11ea-8442-9e6df634f931.PNG)
![IMG_2625](https://user-images.githubusercontent.com/18611506/69031853-0359da80-0a16-11ea-9e0a-be8aff0d5e65.jpg)

**Comment by iHardikTrivedi** [comment]
Try this solution:
[[SOLUTION]](https://github.com/SVProgressHUD/SVProgressHUD/issues/1013#issuecomment-567335032)

**Comment by keleboys** [comment]
同样遇到相同的问题

**Comment by dushihao** [comment]
同样的问题
