### ISSUE TITLE
IOS 13 不支持蒙层。

### ISSUE THREAD

**Issue by boaosady** [SVProgressHUD/SVProgressHUD#1010]
如上题。IOS 12及以下，蒙层没问题。13 上uiwindows 逻辑改变了，无法添加蒙层

**Comment by iHardikTrivedi** [comment]
Try this solution:
[[SOLUTION]](https://github.com/SVProgressHUD/SVProgressHUD/issues/1013#issuecomment-567335032)

**Comment by honkmaster** [comment]
Please provide an english error description, otherwise this issue will be closed.
