### ISSUE TITLE
need support iOS 13 & Xcode 11 project.

### ISSUE THREAD

**Issue by iOSSer** [SVProgressHUD/SVProgressHUD#1013]
just crash: SVProgressHUD.show()

look #990

**Comment by Joonet** [comment]
I have this problem, too

**Comment by iHardikTrivedi** [comment]
SOLUTION for
SVProgressHUD in your iOS 13.0 or later version with latest Xcode

**Comment by bahram-hodjaev** [comment]
@iHardikTrivedi, why don't you create a PR for this issue?
