### ISSUE TITLE
In ios13 system, HUD will not be displayed in the center, but in the upper left corner

### ISSUE THREAD

**Issue by xuhuaping** [SVProgressHUD/SVProgressHUD#1018]
![1001578222842_ pic](https://user-images.githubusercontent.com/18001988/71779087-a0d19380-2fef-11ea-8e09-79fc1c3cddfc.jpg)

**Comment by Nibir00795** [comment]
I also facing this problem.

**Comment by Hikaru-Otaki** [comment]
me too

**Comment by FuncTime** [comment]
me too

**Comment by cmdr-surender-singh** [comment]
me too 
![Simulator Screen Shot - iPhone Xs - 2020-01-17 at 19 15 28](https://user-images.githubusercontent.com/42886349/72616832-bd5dbc00-395d-11ea-8452-37c9dc970114.png)

**Comment by JunsW** [comment]
This issue is due to the reason that the current window is only accessible via `UIScene` by default in iOS13 rather than the old way. 

Get the current window like this:

``` [[[[UIApplication sharedApplication] connectedScenes] allObjects] firstObject].delegate.window;```

Pull request #1019 resolved this issue. 

You guys could try it out.

**Comment by hchheta7** [comment]
[Uploading SVProgressHUD.m.zip…]()

Replace SVProgressHUD. m with this updated code. 
this will solve the issue in iOS 13.
and in AppDelegate if you have `add var window  : Window?` then no need it for xcode11 or later.

**Comment by josharnoldjosh** [comment]
The pull request doesn't work for me on latest version of Xcode.

**Comment by hchheta7** [comment]
[SVProgressHUD.m.zip](https://github.com/SVProgressHUD/SVProgressHUD/files/4212085/SVProgressHUD.m.zip)
…]()
Please change SVProgressHUD.m file code with this file for xcode11 or later Its Uiscenedelegate issue.

**Comment by jsaiti** [comment]
> This issue is due to the reason that the current window is only accessible via `UIScene` by default in iOS13 rather than the old way.
> 
> Get the current window like this:
> 
> ` [[[[UIApplication sharedApplication] connectedScenes] allObjects] firstObject].delegate.window;`
> 
> Pull request #1019 resolved this issue.
> 
> You guys could try it out.


It crashes on iOS 12, because in this case: `UIScene *scene = [[[[UIApplication sharedApplication] connectedScenes] allObjects] firstObject];` need to check it for iOS version!

Just replace this code: 
`UIScene *scene = [[[[UIApplication sharedApplication] connectedScenes] allObjects] firstObject];
        if([scene.delegate conformsToProtocol:@protocol(UIWindowSceneDelegate)]){
            window = [(id <UIWindowSceneDelegate>)scene.delegate window];
        }else{
            window = [[[UIApplication sharedApplication]delegate]window];
        }`
with this:
`if (@available(iOS 13.0, *)) {
        UIScene *scene = [[[[UIApplication sharedApplication] connectedScenes] allObjects] firstObject];
        if([scene.delegate conformsToProtocol:@protocol(UIWindowSceneDelegate)]){
            window = [(id <UIWindowSceneDelegate>)scene.delegate window];
        }else{
            window = [[[UIApplication sharedApplication]delegate]window];
        }
    } else {
        window = [[[UIApplication sharedApplication]delegate]window];
    }`

**Comment by LaptrinhvaCuocsong** [comment]
At Appdelegate.swift
In **func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool**
Let set **window = UIWindow(frame: UIScreen.main.bounds)**

**Comment by SunnyFinlitetech** [comment]
> At Appdelegate.swift
> In **func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool**
> Let set **window = UIWindow(frame: UIScreen.main.bounds)**

Works for me.
Thanks @LaptrinhvaCuocsong
