### ISSUE TITLE
[iOS 13] Spinner not centered

### ISSUE THREAD

**Issue by sylvia971** [SVProgressHUD/SVProgressHUD#1028]
The spinner is at the top left corner instead of centre for iOS 13

**Comment by daniilbelikov** [comment]
Me too :(

**Comment by datamaru** [comment]
Yeah me too.

**Comment by yo113** [comment]
Same issue here any solution guys??

**Comment by daniilbelikov** [comment]
> Same issue here any solution guys??

You’re spinner nor centered because you built your project in iOS 13. Code below is solveing problem. This code in App Delegate.

![1E69B757-D2C0-4B1D-BA3A-6DA0C1908751](https://user-images.githubusercontent.com/49493361/77825691-6b3ad300-7124-11ea-9f2f-4407d0f5f2c7.jpeg)

**Comment by yo113** [comment]
> > Same issue here any solution guys??
> 
> You spinner not centered because you built your project in iOS 13. Code below is solveing problem. This code in App Delegate file.
> 
> If you don’t understand, write me on [pvt.belikov@gmail.com](mailto:pvt.belikov@gmail.com)
> 
> ![E8BF6733-65E6-4AD7-9520-53E36650DA3E](https://user-images.githubusercontent.com/49493361/77826207-6fb4bb00-7127-11ea-9abf-5dc926488c6f.jpeg)

Thanks its working...thanks a lot

**Comment by Huberger** [comment]
Great, is working, thanks.
