### ISSUE TITLE
Xcode11 创建了一个oc项目，加载提示框位置显示错误

### ISSUE THREAD

**Issue by Azraeltulips** [SVProgressHUD/SVProgressHUD#1032]
pod 'SVProgressHUD', '~> 2.2.5'
版本2.2.5
[SVProgressHUD showWithStatus:@"正在加载..."];
使用上面的代码 运行后发现 视图在屏幕左上角，且中心点和左上角圆点重合
在Swift里面都是正常的
请问这是为什么呢？

**Comment by ioswangqiang** [comment]
我也遇到了同样的问题，之前使用没问题，最近有问题，难道是Xcode升级到原因？

**Comment by Azraeltulips** [comment]
> 我也遇到了同样的问题，之前使用没问题，最近有问题，难道是Xcode升级到原因？

找到了原因，是因为Xcode11新建的工程有一个新的SceneDelegate类，在iOS13.0系统运行时 会由这个类加载window，导致该库没办法获取window。你把AppDelegate类里面判断系统创建的window代码的if else去掉就可以了

**Comment by yellowMan1** [comment]
能具体说一下嘛 我也遇到了 我在appdelegate 没看到这个 if else

**Comment by Azraeltulips** [comment]
> 能具体说一下嘛 我也遇到了 我在appdelegate 没看到这个 if else

这个if else 是自己写的。你现在只要在appdelegate的didFinishLaunchingWithOptions方法里面直接实现window的创建和根控制器的赋值就可以了，就是把下面的else内容直接写出来
`if (@available(iOS 13.0, *)) {
        
    } else {        
        self.window = [[UIWindow alloc]initWithFrame:UIScreen.mainScreen.bounds];
    self.window.backgroundColor = UIColor.whiteColor;
    
    if (IsLogin) {
        [self.window setRootViewController:LSCommonTool.initLSTabBarController];
    }else {
        LoginController *loginVC = [[LoginController alloc]init];
        
        LSNavigationController *loginNav = [[LSNavigationController alloc]initWithRootViewController:loginVC];
        
        self.window.rootViewController = loginNav;
    }
    
    [self.window makeKeyAndVisible];
        }
        
        [self.window setWindowScene:windowScene];
        [self.window makeKeyAndVisible];
    }`

**Comment by 1148088867** [comment]
Xcode 版本更新新增了SceneDelegate，SVProgressHUD的作者在设置HUDView的中心位置时使用的是UIApplication.sharedApplication.delegate.window.bounds 获取的，而版本更新之后获取不到正确的rect，因此把这部分代码进行调整。（鄙人测试没问题）

代码调整：
SVProgressHUD.m中引入#import "SceneDelegate.h" ，

修改 -(void)positionHUD:(NSNotification*)notification 方法开头位置

#if !defined(SV_APP_EXTENSIONS) && TARGET_OS_IOS
if (@available(ios 13.0, *)) {
UIWindowScene *windowScene = (UIWindowScene *)[[[UIApplication sharedApplication] connectedScenes] allObjects].firstObject;
SceneDelegate *delegate =(SceneDelegate *)windowScene.delegate;
self.frame = delegate.window.bounds;
}else {
self.frame = [[[UIApplication sharedApplication] delegate] window].bounds;
}
UIInterfaceOrientation orientation = UIApplication.sharedApplication.statusBarOrientation;
#elif !defined(SV_APP_EXTENSIONS) && !TARGET_OS_IOS
if (@available(ios 13.0, *)) {
UIWindowScene *windowScene = (UIWindowScene *)[[[UIApplication sharedApplication] connectedScenes] allObjects].firstObject;
SceneDelegate *delegate =(SceneDelegate *)windowScene.delegate;
self.frame = delegate.window.bounds;
}else {
self.frame = [[[UIApplication sharedApplication] delegate] window].bounds;
}
#else

或者更简单的调整（可能会出现其他问题,不建议使用）：
修改 -(void)positionHUD:(NSNotification*)notification 方法开头位置

#if !defined(SV_APP_EXTENSIONS) && TARGET_OS_IOS
self.frame = UIScreen.mainScreen.bounds;
UIInterfaceOrientation orientation = UIApplication.sharedApplication.statusBarOrientation;
#elif !defined(SV_APP_EXTENSIONS) && !TARGET_OS_IOS
self.frame = UIScreen.mainScreen.bounds;
#else
