### ISSUE TITLE
UI API called on a background thread: -[UIApplication applicationState]

### ISSUE THREAD

**Issue by luWenFengGitHub** [SVProgressHUD/SVProgressHUD#1034]
![1](https://user-images.githubusercontent.com/12792480/78973076-b4861c00-7b41-11ea-8b05-04223fe331ba.png)
![2](https://user-images.githubusercontent.com/12792480/78972935-74bf3480-7b41-11ea-8f18-0947028bcf31.png)

**Comment by ShiChenZhi** [comment]
注释掉updateMotionEffectForOrientation
