### ISSUE TITLE
Xcode11 创建了一个oc项目，加载提示框位置（0，0） 大哥们怎么解决

### ISSUE THREAD

**Issue by yellowMan1** [SVProgressHUD/SVProgressHUD#1035]
Xcode11 创建了一个oc项目，加载提示框位置（0，0） 怎么解决呀大哥们

**Comment by 1148088867** [comment]
Xcode 版本更新新增了SceneDelegate，SVProgressHUD的作者在设置HUDView的中心位置时使用的是UIApplication.sharedApplication.delegate.window.bounds 获取的，而版本更新之后获取不到正确的rect，因此把这部分代码进行调整。（鄙人测试没问题）

**代码调整：**
SVProgressHUD.m中引入#import "SceneDelegate.h" ，

修改  -(void)positionHUD:(NSNotification*)notification  方法开头位置

#if !defined(SV_APP_EXTENSIONS) && TARGET_OS_IOS
    if (@available(ios 13.0, *)) {
        UIWindowScene *windowScene = (UIWindowScene *)[[[UIApplication sharedApplication] connectedScenes] allObjects].firstObject;
        SceneDelegate *delegate =(SceneDelegate *)windowScene.delegate;
        self.frame = delegate.window.bounds;
    }else {
        self.frame = [[[UIApplication sharedApplication] delegate] window].bounds;
    }
    UIInterfaceOrientation orientation = UIApplication.sharedApplication.statusBarOrientation;
#elif !defined(SV_APP_EXTENSIONS) && !TARGET_OS_IOS
    if (@available(ios 13.0, *)) {
        UIWindowScene *windowScene = (UIWindowScene *)[[[UIApplication sharedApplication] connectedScenes] allObjects].firstObject;
        SceneDelegate *delegate =(SceneDelegate *)windowScene.delegate;
        self.frame = delegate.window.bounds;
    }else {
        self.frame = [[[UIApplication sharedApplication] delegate] window].bounds;
    }
#else


**或者更简单的调整（可能会出现其他问题,不建议使用）：**
修改  -(void)positionHUD:(NSNotification*)notification  方法开头位置

#if !defined(SV_APP_EXTENSIONS) && TARGET_OS_IOS
    self.frame = UIScreen.mainScreen.bounds;
    UIInterfaceOrientation orientation = UIApplication.sharedApplication.statusBarOrientation;
#elif !defined(SV_APP_EXTENSIONS) && !TARGET_OS_IOS
    self.frame = UIScreen.mainScreen.bounds;
#else

**Comment by Hjt830** [comment]
> Xcode 版本更新新增了SceneDelegate，SVProgressHUD的作者在设置HUDView的中心位置时使用的是UIApplication.sharedApplication.delegate.window.bounds 获取的，而版本更新之后获取不到正确的rect，因此把这部分代码进行调整。（鄙人测试没问题）
> 
> **代码调整：**
> SVProgressHUD.m中引入#import "SceneDelegate.h" ，
> 
> 修改 -(void)positionHUD:(NSNotification*)notification 方法开头位置
> 
> #if !defined(SV_APP_EXTENSIONS) && TARGET_OS_IOS
> if (@available(ios 13.0, *)) {
> UIWindowScene *windowScene = (UIWindowScene *)[[[UIApplication sharedApplication] connectedScenes] allObjects].firstObject;
> SceneDelegate *delegate =(SceneDelegate *)windowScene.delegate;
> self.frame = delegate.window.bounds;
> }else {
> self.frame = [[[UIApplication sharedApplication] delegate] window].bounds;
> }
> UIInterfaceOrientation orientation = UIApplication.sharedApplication.statusBarOrientation;
> #elif !defined(SV_APP_EXTENSIONS) && !TARGET_OS_IOS
> if (@available(ios 13.0, *)) {
> UIWindowScene *windowScene = (UIWindowScene *)[[[UIApplication sharedApplication] connectedScenes] allObjects].firstObject;
> SceneDelegate *delegate =(SceneDelegate *)windowScene.delegate;
> self.frame = delegate.window.bounds;
> }else {
> self.frame = [[[UIApplication sharedApplication] delegate] window].bounds;
> }
> #else
> 
> **或者更简单的调整（可能会出现其他问题,不建议使用）：**
> 修改 -(void)positionHUD:(NSNotification*)notification 方法开头位置
> 
> #if !defined(SV_APP_EXTENSIONS) && TARGET_OS_IOS
> self.frame = UIScreen.mainScreen.bounds;
> UIInterfaceOrientation orientation = UIApplication.sharedApplication.statusBarOrientation;
> #elif !defined(SV_APP_EXTENSIONS) && !TARGET_OS_IOS
> self.frame = UIScreen.mainScreen.bounds;
> #else

导入头文件会报错
<img width="1077" alt="image" src="https://user-images.githubusercontent.com/13915006/82149516-88b92d00-9889-11ea-8e64-827999d124d2.png">

**Comment by Hjt830** [comment]
导入头文件会报错
![image](https://user-images.githubusercontent.com/13915006/82150514-54df0700-988b-11ea-9ab2-7f3d8b9c9894.png)

可以这样修改
#if !defined(SV_APP_EXTENSIONS) && TARGET_OS_IOS
    if (@available(ios 13.0, *)) {
        UIWindowScene *windowScene = (UIWindowScene *)[[[UIApplication sharedApplication] connectedScenes] allObjects].firstObject;
        id <UIWindowSceneDelegate> delegate = (id <UIWindowSceneDelegate>)windowScene.delegate;
        self.frame = delegate.window.bounds;
    } else {
        self.frame = [[[UIApplication sharedApplication] delegate] window].bounds;
    }
    UIInterfaceOrientation orientation = UIApplication.sharedApplication.statusBarOrientation;
#elif !defined(SV_APP_EXTENSIONS) && !TARGET_OS_IOS
    if (@available(ios 13.0, *)) {
        UIWindowScene *windowScene = (UIWindowScene *)[[[UIApplication sharedApplication] connectedScenes] allObjects].firstObject;
        id <UIWindowSceneDelegate> delegate = (id <UIWindowSceneDelegate>)windowScene.delegate;
        self.frame = delegate.window.bounds;
    } else {
        self.frame = [[[UIApplication sharedApplication] delegate] window].bounds;
    }
#else

**Comment by chimingzi** [comment]
#985 shows good solutions.
