### ISSUE TITLE
UIActionSheet 代理回调使用SVProgressHUD不显示.

### ISSUE THREAD

**Issue by JC-Passerby** [SVProgressHUD/SVProgressHUD#1036]
"UIActionSheet" 代理回调使用SVProgressHUD不显示

**Comment by sonic009** [comment]
I am still facing the progressHUD problem with the latest version also.
ProgressHUD is not showing in the center.

**Comment by sonic009** [comment]
This issue has been resolved. It was some window issue in iOS 13.0 or later.
