### ISSUE TITLE
为什么在 iOS 13 系统中显示在左上角？？？？？？？？？？？？

### ISSUE THREAD

**Issue by iOSSer** [SVProgressHUD/SVProgressHUD#1043]
why？
没有加这句还会闪退： @property (strong, nonatomic) UIWindow *window;

**Comment by czl0325** [comment]
同问！！！

**Comment by Azraeltulips** [comment]
iOS13多了一个SceneDelegate类，导致获取不到window了

**Comment by Azraeltulips** [comment]
在源码SVProgressHUD.m文件中第638行self.frame = [[[UIApplication sharedApplication] delegate] window].bounds这句改成
self.frame= [UIApplication sharedApplication].keyWindow.bounds这个应该就可以了

**Comment by iOSSer** [comment]
> 在源码SVProgressHUD.m文件中第638行self.frame = [[[UIApplication sharedApplication] delegate] window].bounds这句改成
> self.frame= [UIApplication sharedApplication].keyWindow.bounds这个应该就可以了

改了还是不行：
- (void)positionHUD:(NSNotification*)notification {
    CGFloat keyboardHeight = 0.0f;
    double animationDuration = 0.0;

#if !defined(SV_APP_EXTENSIONS) && TARGET_OS_IOS
    self.frame = UIApplication.sharedApplication.keyWindow.bounds;
    UIInterfaceOrientation orientation = UIApplication.sharedApplication.statusBarOrientation;
#elif !defined(SV_APP_EXTENSIONS) && !TARGET_OS_IOS
    self.frame= [UIApplication sharedApplication].keyWindow.bounds;
#else

字号不一样行数不一样，建议直接说方法

**Comment by Azraeltulips** [comment]
> > 在源码SVProgressHUD.m文件中第638行self.frame = [[[UIApplication sharedApplication] delegate] window].bounds这句改成
> > self.frame= [UIApplication sharedApplication].keyWindow.bounds这个应该就可以了
> 
> 改了还是不行：
> 
> * (void)positionHUD:(NSNotification*)notification {
>   CGFloat keyboardHeight = 0.0f;
>   double animationDuration = 0.0;
> 
> #if !defined(SV_APP_EXTENSIONS) && TARGET_OS_IOS
> self.frame = UIApplication.sharedApplication.keyWindow.bounds;
> UIInterfaceOrientation orientation = UIApplication.sharedApplication.statusBarOrientation;
> #elif !defined(SV_APP_EXTENSIONS) && !TARGET_OS_IOS
> self.frame= [UIApplication sharedApplication].keyWindow.bounds;
> #else
> 
> 字号不一样行数不一样，建议直接说方法名

就是这里，我这边这样修改之后就没有问题了，不知道你这个为什么不行。目前只找到了这个解决办法

**Comment by Azraeltulips** [comment]
> > > 在源码SVProgressHUD.m文件中第638行self.frame = [[[UIApplication sharedApplication] delegate] window].bounds这句改成
> > > self.frame= [UIApplication sharedApplication].keyWindow.bounds这个应该就可以了
> > 
> > 
> > 改了还是不行：
> > 
> > * (void)positionHUD:(NSNotification*)notification {
> >   CGFloat keyboardHeight = 0.0f;
> >   double animationDuration = 0.0;
> > 
> > #if !defined(SV_APP_EXTENSIONS) && TARGET_OS_IOS
> > self.frame = UIApplication.sharedApplication.keyWindow.bounds;
> > UIInterfaceOrientation orientation = UIApplication.sharedApplication.statusBarOrientation;
> > #elif !defined(SV_APP_EXTENSIONS) && !TARGET_OS_IOS
> > self.frame= [UIApplication sharedApplication].keyWindow.bounds;
> > #else
> > 字号不一样行数不一样，建议直接说方法名
> 
> 就是这里，我这边这样修改之后就没有问题了，不知道你这个为什么不行。目前只找到了这个解决办法

你可以在这里打断点调试 如果self.frame有值，那就不是这个问题了，可能是其他问题

**Comment by AlianOL** [comment]
> > > > 在源码SVProgressHUD.m文件中第638行self.frame = [[[UIApplication sharedApplication] delegate] window].bounds这句改成
> > > > self.frame= [UIApplication sharedApplication].keyWindow.bounds这个应该就可以了
> > > 
> > > 
> > > 改了还是不行：
> > > 
> > > * (void)positionHUD:(NSNotification*)notification {
> > >   CGFloat keyboardHeight = 0.0f;
> > >   double animationDuration = 0.0;
> > > 
> > > #if !defined(SV_APP_EXTENSIONS) && TARGET_OS_IOS
> > > self.frame = UIApplication.sharedApplication.keyWindow.bounds;
> > > UIInterfaceOrientation orientation = UIApplication.sharedApplication.statusBarOrientation;
> > > #elif !defined(SV_APP_EXTENSIONS) && !TARGET_OS_IOS
> > > self.frame= [UIApplication sharedApplication].keyWindow.bounds;
> > > #else
> > > 字号不一样行数不一样，建议直接说方法名
> > 
> > 
> > 就是这里，我这边这样修改之后就没有问题了，不知道你这个为什么不行。目前只找到了这个解决办法
> 
> 你可以在这里打断点调试 如果self.frame有值，那就不是这个问题了，可能是其他问题。或者你直接给frame一个固定值试试

CGRectMake设置frame系统就不走那个方法了。。不知道为啥

**Comment by flyweights** [comment]
我也遇到了同样的问题啊，醉了。。。。

**Comment by AlianOL** [comment]
> 我也遇到了同样的问题啊，醉了。。。。

到现在也没解决这个问题。。忍痛不用sv了。。好可惜

**Comment by iOSSer** [comment]
这么久过去了还是不行！

**Comment by iOSSer** [comment]
XCode & iOS 13+ ，add code：
`@property (nonatomic, strong) UIWindow *window;`
   ` self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds]`

**Comment by CoderAquarius** [comment]
Yes, the huge problem remains

**Comment by Butterfly7777777** [comment]
同样碰到，神坑

**Comment by hllGitHub** [comment]
You can add this in the AppDelegate. It works well.

``` swift
var window: UIWindow?

func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
  self.window = UIWindow(frame: UIScreen.main.bounds)
  return true
}
```
This issue is caused by Window.

**Comment by AlainXu-SE** [comment]
> XCode 11 & iOS 13+ ，add code： `@property (nonatomic, strong) UIWindow *window;` ` self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds]`

Thank you, this save my day!

**Comment by honkmaster** [comment]
I've updated the component and addressed several bugs. Please review version 2.3.0, and should you find any remaining issues, your feedback would be greatly valued.
