### ISSUE TITLE
由SceneDelegate管理的window，使用SVProgressHUD会因为找不到keyWindow崩溃

### ISSUE THREAD

**Issue by AlianOL** [SVProgressHUD/SVProgressHUD#1046]
新建的项目window由SceneDelegate管理，如果pod并使用SVProgressHUD，会因为找不到keyWindow崩溃

**Comment by flyweights** [comment]
是啊

**Comment by yinzhihao** [comment]
我也遇到这个问题了，请问该怎么解决呢？
我是在SDK中使用的，总不能要求APP说，你改一下代码吧
这样不太好吧

**Comment by M-Quadra** [comment]
First, add `var window: UIWindow?` in AppDelegate.

Then, in SceneDelegate ( find or create window ):
```
func scene(_ scene: UIScene, willConnectTo session: UISceneSession, options connectionOptions: UIScene.ConnectionOptions) {
    guard let scene = scene as? UIWindowScene else { return }
    
    let window = UIWindow(windowScene: scene)
    self.window = window
    defer { window.makeKeyAndVisible() }
    
    if let appDelegate = UIApplication.shared.delegate as? AppDelegate {
        appDelegate.window = window
    }
}
```

**Comment by LongerONE** [comment]
I did like this to fix the issue:

> func scene(_ scene: UIScene, willConnectTo session: UISceneSession, options connectionOptions: UIScene.ConnectionOptions) {
>     guard let scene = scene as? UIWindowScene else { return }
>     
>     let window = UIWindow(windowScene: scene)
>     self.window = window
>     defer { window.makeKeyAndVisible() }
>     
>     if let appDelegate = UIApplication.shared.delegate as? AppDelegate {
>         appDelegate.window = window
>     }
> }

**Comment by honkmaster** [comment]
I've updated the component and addressed several bugs. Please review version 2.3.0, and should you find any remaining issues, your feedback would be greatly valued.
