### ISSUE TITLE
-[SVProgressHUD showImage:status:duration:]_block_invoke + 845 crash

### ISSUE THREAD

**Issue by wangjunhua1** [SVProgressHUD/SVProgressHUD#1048]
iPhone XS Max
iOS 13.6.0

pod 'SVProgressHUD', '~> 2.2.5'
crash information:
SVProgressHUD.m - 第 845 行
__43-[SVProgressHUD showImage:status:duration:]_block_invoke + 845
<img width="972" alt="image" src="https://user-images.githubusercontent.com/11474284/87872730-c5bab080-c9ed-11ea-9771-75a13ddac71d.png">

**Comment by jeffreyjackson** [comment]
look at this: https://github.com/SVProgressHUD/SVProgressHUD/issues/990

**Comment by wangjunhua1** [comment]
this does not work all by itself

**Comment by wangjunhua1** [comment]
lazy var window: UIWindow? = {
    return UIApplication.shared.windows.first
}()

**Comment by wangjunhua1** [comment]
this does not work  
 lazy var window: UIWindow? = {
return UIApplication.shared.windows.first
}()  

we just have this crash on iPhone XS Max iOS 13.6.0

**Comment by wangjunhua1** [comment]
It's not obvious
