### ISSUE TITLE
The progress hud is not centered

### ISSUE THREAD

**Issue by borzh** [SVProgressHUD/SVProgressHUD#1050]
This is happening because in center calculations, instead of taking half of the height (0.5f) you are multiplying it by 0.45f!
Please fix ASAP, thanks.

https://github.com/SVProgressHUD/SVProgressHUD/blob/0a9abb56a8d5c1ffc0078babc07fb11ff2fa2f22/SVProgressHUD/SVProgressHUD.m#L714

**Comment by borzh** [comment]
At least can it be configurable, like a multiply constant or something, so the user could have the control of it?

**Comment by honkmaster** [comment]
I've updated the component and addressed several bugs. Please review version 2.3.0, and should you find any remaining issues, your feedback would be greatly valued.
