### ISSUE TITLE
Memory leak issues

### ISSUE THREAD

**Issue by moslienko** [SVProgressHUD/SVProgressHUD#1051]
All operations with the loader are carried out in the main thread, but a memory leak is still formed, in a couple of minutes of using the application there are already 5 of them.
<img width="390" alt="Снимок экрана 2020-08-03 в 20 03 24" src="https://user-images.githubusercontent.com/8676976/89185708-ddd12900-d5c4-11ea-892e-05dd58b13cf8.png">
<img width="1262" alt="Снимок экрана 2020-08-03 в 19 46 51" src="https://user-images.githubusercontent.com/8676976/89185830-0eb15e00-d5c5-11ea-83cb-fb373dd3c21d.png">

**Comment by amahairides** [comment]
I also have this problem, any fix for it?

**Comment by iDevelopper** [comment]
@amahairides , a PR should fix, no?

**Comment by iDevelopper** [comment]
@moslienko , a PR should fix, no?

**Comment by thejeraldo** [comment]
+1 also having memory leaks with SVProgressHUD.

**Comment by bibin-jose** [comment]
Same issue for me ? how to fix ?

**Comment by amahairides** [comment]
I used an own solution for loading, and use SVProgress only for status/error messages where it does not leak.

**Comment by amahairides** [comment]
> Same issue for me ? how to fix ?

 I used an own solution for loading, and use SVProgress only for status/error messages where it does not leak.

**Comment by manghwanitin** [comment]
Any ETA by when this issue will be fixed?

**Comment by honkmaster** [comment]
I've updated the component and addressed several bugs. Please review version 2.3.0, and should you find any remaining issues, your feedback would be greatly valued.
