### ISSUE TITLE
Always template images are ignored

### ISSUE THREAD

**Issue by jjochen** [SVProgressHUD/SVProgressHUD#1053]
Setting images that have the rendering mode `UIImageRenderingModeAlwaysTemplate` are ignored (not shown at all).
The following code has the same result as to setting the image to `nil`:
```
UIImage *image = [[UIImage imageNamed:@"some_image"] imageWithRenderingMode:UIImageRenderingModeAlwaysTemplate];
[SVProgressHUD setSuccessImage:image];
```

**Comment by futuretap** [comment]
When will this be pulled?

**Comment by jjochen** [comment]
Is there any reason this isn't pulled?
