### ISSUE TITLE
SVProgressHud is making the whole app crashing

### ISSUE THREAD

**Issue by embroor** [SVProgressHUD/SVProgressHUD#1058]
this is my most used library, and everything was ok.
but now, every time I use the library my app crashes when I summon the HUD, and I don't know the reason.
All I get in the console is : 

**Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[ProviderMedyaf.AppDelegate window]: unrecognized selector sent to instance 0x60000399c190
( libc++abi.dylib: terminating with uncaught exception of type NSException )**

and it takes me to some code I don't understand at all !
like this : 

_dispatch_once(dispatch_once_t *predicate,
		DISPATCH_NOESCAPE dispatch_block_t block)
{
	if (DISPATCH_EXPECT(*predicate, ~0l) != ~0l) {
		**dispatch_once(predicate, block);    <<------------------------- red error here !**
	} else {
		dispatch_compiler_barrier();
	}
	DISPATCH_COMPILER_CAN_ASSUME(*predicate == ~0l);
}

I tried to update to the latest version, but nothing happened
Please help me out

**Comment by YalayGu** [comment]
In Xcode 11, iOS13  SceneDelegate has a window,  but AppDelegate dose not have a window proprety.

**Comment by AlianOL** [comment]
> In Xcode 11, iOS13 SceneDelegate has a window, but AppDelegate dose not have a window proprety.

so,how do you solve the problem?

**Comment by YalayGu** [comment]
> > In Xcode 11, iOS13 SceneDelegate has a window, but AppDelegate dose not have a window proprety.
> 
> so,how do you solve the problem?

Maybe in PRs, you cloud find some ideas.

**Comment by AlianOL** [comment]
> > > In Xcode 11, iOS13 SceneDelegate has a window, but AppDelegate dose not have a window proprety.
> > 
> > 
> > so,how do you solve the problem?
> 
> Maybe in PRs, you cloud find some ideas.

it makes me disappointed..

**Comment by Afroz50** [comment]
I am also facing same problem and need the solution

**Comment by AlianOL** [comment]
> I am also facing same problem and need the solution

It seems that the author hasn't updated it for a long time

**Comment by iDevelopper** [comment]
> Maybe in PRs, you cloud find some ideas.

Yes but if there is nobody to merge???

So you have to change this library to another one or to a code written by yourself.

**Comment by iDevelopper** [comment]
@YalayGu ,

> Xcode 11, iOS13 SceneDelegate has a window, but AppDelegate dose not have a window proprety.

So you can add this variable again in AppDelegate and set it from the SceneDelegate window variable.

**Comment by ashleymills** [comment]
This is an open source library, which means anyone can make a fork and make any updates they need.

**Comment by ashleymills** [comment]
@Afroz50  @AlianOL @iDevelopper 

This is an open source library, which means anyone can make their own fork and update as required.

**Comment by honkmaster** [comment]
@ashleymills is right.

**Comment by iDevelopper** [comment]
Yes, he is right.

**Comment by honkmaster** [comment]
Another note:

The component may need a rewrite for SceneDelegate. I am / was very busy and had no time to invest into this component. If there are PR these can of course be merged, however they need a proper quality (e.g. most of them miss comments, an update of the Readme.md). If the quality is not good, I need time to update them, which I don't have. Of course you could say, let the submitter update the PR. But this does not happen very often, even if asked.

In addition, due to recent developments regarding SwiftUI, I am personally not sure what is the right way to go.
I made a similar looking SwiftUI component as an experiment [TTProgressHUD](https://github.com/honkmaster/TTProgressHUD).

**Comment by honkmaster** [comment]
Note 2/2:

Most crashed observed are often caused by the hosting app (also here).

**Comment by iDevelopper** [comment]
Cool, so https://github.com/SVProgressHUD/SVProgressHUD is alive!

**Comment by AlianOL** [comment]
> Note 2/2:
> 
> 注2/2:
> 
> Most crashed observed are often caused by the hosting app (also here).
> 
> 大多数崩溃观察通常是由托管应用程序(也在这里)。

Cool,You make me excited，haha

**Comment by AlianOL** [comment]
> Note 2/2:
> 
> Most crashed observed are often caused by the hosting app (also here).

cool，You make me excited，haha

**Comment by iDevelopper** [comment]
@AlianOL , will you send a pull request? Or will I do it?

**Comment by honkmaster** [comment]
Please check existing PR if available and update them if necessary.

**Comment by iDevelopper** [comment]
@honkmaster ,

Can you guide me on which pr I could modify to avoid the crash relative to this issue. I don't have much time either.

Thanks.

**Comment by dozomedyafapp** [comment]
**I found an answer to this problem**

**1/ you go to app delegate page and add this code right after the class  , like this :** 

```
class AppDelegate: UIResponder, UIApplicationDelegate { 

var window: UIWindow? // insert this line if it is not there

...

}
```


**2/ you go to SceneDelegate and add this code inside the first function like this :** 

```
func scene(_ scene: UIScene, willConnectTo session: UISceneSession, options connectionOptions: UIScene.ConnectionOptions) {
                
// insert this line if it is not there
(UIApplication.shared.delegate as? AppDelegate)?.self.window = window

guard let _ = (scene as? UIWindowScene) else { return }
       
 }
```


**I did that and the library worked perfectly**

**Comment by pedrorau** [comment]
> **I found an answer to this problem**
> 
> **1/ you go to app delegate page and add this code right after the class , like this :**
> 
> ```
> class AppDelegate: UIResponder, UIApplicationDelegate { 
> 
> var window: UIWindow? // insert this line if it is not there
> 
> ...
> 
> }
> ```
> 
> **2/ you go to SceneDelegate and add this code inside the first function like this :**
> 
> ```
> func scene(_ scene: UIScene, willConnectTo session: UISceneSession, options connectionOptions: UIScene.ConnectionOptions) {
>                 
> // insert this line if it is not there
> (UIApplication.shared.delegate as? AppDelegate)?.self.window = window
> 
> guard let _ = (scene as? UIWindowScene) else { return }
>        
>  }
> ```
> 
> **I did that and the library worked perfectly**

+1 to this answer, ty bro

**Comment by shishirthedev** [comment]
> **I found an answer to this problem**
> 
> **1/ you go to app delegate page and add this code right after the class , like this :**
> 
> ```
> class AppDelegate: UIResponder, UIApplicationDelegate { 
> 
> var window: UIWindow? // insert this line if it is not there
> 
> ...
> 
> }
> ```
> 
> **2/ you go to SceneDelegate and add this code inside the first function like this :**
> 
> ```
> func scene(_ scene: UIScene, willConnectTo session: UISceneSession, options connectionOptions: UIScene.ConnectionOptions) {
>                 
> // insert this line if it is not there
> (UIApplication.shared.delegate as? AppDelegate)?.self.window = window
> 
> guard let _ = (scene as? UIWindowScene) else { return }
>        
>  }
> ```
> 
> **I did that and the library worked perfectly**

Its working perfectly.

**Comment by jatinfl15** [comment]
![Screenshot 2021-06-08 at 10 35 53 AM](https://user-images.githubusercontent.com/70931173/121126162-56d48900-c845-11eb-80ff-1494ca16e900.png)


what i am missing here.

**Comment by honkmaster** [comment]
I've updated the component and addressed several bugs. Please review version 2.3.0, and should you find any remaining issues, your feedback would be greatly valued.
