### ISSUE TITLE
Xcode 12 is now out with binary support for SPM - Request to get project moved to SPM

### ISSUE THREAD

**Issue by ethanwa** [SVProgressHUD/SVProgressHUD#1060]
Request to get project moved to SPM. About 50% of my components in my app have moved from Pods to SPM now. Would love to see this one moved as well.

**Comment by NachoVarga** [comment]
What would that mean for Objective-C projects?

**Comment by iDevelopper** [comment]
I do not understand the title!

**Comment by sereivoanyong** [comment]
See #1063

**Comment by diogot** [comment]
It's still a valid issue. There is an open PR with the fix waiting to be merged #1063

**Comment by honkmaster** [comment]
I've updated the component and addressed several bugs. Please review version 2.3.0, and should you find any remaining issues, your feedback would be greatly valued.

**Comment by ethanwa** [comment]
Hi @honkmaster 

I'm trying to add the 2.3.0 version to my project using SPM and it's not working. It's asking for an `import SVProgressHUD` when I try to call `SVProgressHUD.show()`, yet it can't find the project dependancies. 

Can you take a Quick Look and make sure SPM support is working properly?

**Comment by honkmaster** [comment]
I checked it with a local SPM beforehand. Will check it tomorrow with the remote GitHub URL.

**Comment by ethanwa** [comment]
Just an update... with 2.3.1:

I can get it to run and work on a brand new Swift project using SPM, but when I try and add it to my existing workspace in Xcode, I get the same errors still. My workspace has two projects, and in my main project with the buildable app it also has an app extension. It's a complex Xcode workspace.

Just so you know, a while back someone branched this repository and added SPM support and fixed some Umbrella warnings. This works in my project just fine with SPM: https://github.com/ethanwa/SVProgressHUD 

Maybe that can help lead you in the right direction? His Package.swift is a bit different than yours.

**Comment by honkmaster** [comment]
@ethanwa Thanks for pointing me to your repository. Feel free to submit a PR, I will take a look this evening (GMT).

**Comment by honkmaster** [comment]
@ethanwa Let me ask: Where do you see significant differences in the Package.swift? The mayor difference are the platforms and one additional resource (PrivacyInfo.xcprivacy). Otherwise it looks quite similar.

**Comment by ethanwa** [comment]
Sorry, I didn't mean to imply they were significant. I just did notice that `publicHeadersPath: "Public"` was different. And it works just fine with my project. But for some reason your branch doesn't.

Also, with your branch I'm getting these warnings on even a brand new clean project, which I don't get with the other branch either. Not sure if they are related:

<img width="304" alt="Screenshot 2023-11-02 at 4 21 10 PM" src="https://github.com/SVProgressHUD/SVProgressHUD/assets/1653780/1cc38ff8-98b0-4c20-a046-f0621b0ca10d">

I appreciate the time you're taking to look into this.

**Comment by honkmaster** [comment]
Maybe @denandreychuk can help.
