### ISSUE TITLE
why is showing in left top ? isn't center ?

### ISSUE THREAD

**Issue by iOSSer** [SVProgressHUD/SVProgressHUD#1062]
my code :
`
- (void)viewDidLoad {
    [super viewDidLoad];
    [self.tableView registerClass:[UITableViewCell class] forCellReuseIdentifier:@"cell"];
    self.tableView.hidden = YES;

    [SVProgressHUD showWithStatus:@"show"];
}

`
Screen Shot Image：
![Simulator Screen Shot - iPhone 8 Plus - 2020-09-23 at 22 14 43](https://user-images.githubusercontent.com/3730100/94025275-e7b82100-fdea-11ea-9432-7889f15d9fd1.png)

**Comment by iOSSer** [comment]
Tried all the methods they said failed

**Comment by iOSSer** [comment]
self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];

**Comment by 008v** [comment]
the same issue

**Comment by codedeman** [comment]
you can use this func to solve this problem     [SVProgressHUD setOffsetFromCenter:(UIOffsetMake(UIApplication.sharedApplication.keyWindow.center.x, UIApplication.sharedApplication.keyWindow.center.y))];

**Comment by CoderAquarius** [comment]
Yes, the huge problem remains

**Comment by geohei** [comment]
Any update on this issue?
It hit me after I switched my app to UISceneSession (for Multiple Window support)

**Comment by honkmaster** [comment]
I've updated the component and addressed several bugs. Please review version 2.3.0, and should you find any remaining issues, your feedback would be greatly valued.
