### ISSUE TITLE
Not working XOCDE 12.1 and iOS 14.1

### ISSUE THREAD

**Issue by thilakks** [SVProgressHUD/SVProgressHUD#1071]
SVProgress hud crashing in Xcode 12.1

**Comment by martynovskij** [comment]
+1

**Comment by DineshKachhot** [comment]
Any solution for this issue ?

**Comment by martynovskij** [comment]
**1/ you go to app delegate page and add this code right after the class , like this :**
```
class AppDelegate: UIResponder, UIApplicationDelegate { 

var window: UIWindow? // insert this line if it is not there

...

}
```
**2/ you go to SceneDelegate and add this code inside the first function like this :**
```
func scene(_ scene: UIScene, willConnectTo session: UISceneSession, options connectionOptions: UIScene.ConnectionOptions) {
                
// insert this line if it is not there
(UIApplication.shared.delegate as? AppDelegate)?.self.window = window

guard let _ = (scene as? UIWindowScene) else { return }
       
 }
```
**I did that and the library worked perfectly**

**Comment by kimckf521** [comment]
@martynovskij Thanks, bro. Your solution works prefectly. You save my life!

**Comment by fritjofdittner** [comment]
Could someone tell me the correct way to fix this in Objective-C?

**Comment by dpedrerol** [comment]
@martynovskij Thanks!! It works great! You have saved me a lot of time!

**Comment by HB-Krutagn** [comment]
Thanks Man!!

**Comment by coopsfly172** [comment]
Is there a similar solution for Objective-C?  @fritjofdittner how did you overcome the problem?

**Comment by iDevelopper** [comment]
@coopsfly172,

This is the same solution but written in Objective-C:

In AppDelegate.h:
```objective-c
@interface AppDelegate : UIResponder <UIApplicationDelegate>

@property (strong, nonatomic) UIWindow* window;

@end
```
In SceneDelegate.m:
```objective-c
#import "AppDelegate.h"

@implementation SceneDelegate

- (void)scene:(UIWindowScene *)scene willConnectToSession:(UISceneSession *)session options:(UISceneConnectionOptions *)connectionOptions {

    ((AppDelegate *)[[UIApplication sharedApplication] delegate]).window = self.window;
    ...
}

```

**Comment by coopsfly172** [comment]
Thanks @iDevelopper - I had to make one amend in SceneDelegate.m for it to build

`[[UIApplication sharedApplication] delegate].window = self.window;`

**Comment by honkmaster** [comment]
I've updated the component and addressed several bugs. Please review version 2.3.0, and should you find any remaining issues, your feedback would be greatly valued.
