### ISSUE TITLE
No such module 'SVProgressHUD'

### ISSUE THREAD

**Issue by selva21kd** [SVProgressHUD/SVProgressHUD#1081]
No such module 'SVProgressHUD'

I added into pod file. after successful installation trying to run the application. getting this issue.

**Comment by phucph1998** [comment]
Same ???

**Comment by phucph1998** [comment]
I deleted file pod, pod lock after install again but result not change.

**Comment by guilhermeJay** [comment]
I had the same issue on a Mac with Apple Silicon, I had to add this to my Podfile:

```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    end
  end
end
```

**Comment by LucasJorgeHubert** [comment]
I'm have the same problem, with Objc works fine, but in Swift file, does't work

**Comment by Dast1Woop** [comment]
use: pod 'SVProgressHUD', '~> 2.2.5', :modular_headers => true

**Comment by GAURAVREX20** [comment]
Got the same issue. Is it solved?

**Comment by Dast1Woop** [comment]
> use: pod 'SVProgressHUD', '~> 2.2.5', :modular_headers => true

then use @import  SVProgressHUD in swift file
