### ISSUE TITLE
SVProgressHud Package dependency installation issue

### ISSUE THREAD

**Issue by Taimoor20** [SVProgressHUD/SVProgressHUD#1093]
i am trying to install SVProgressHUD with package dependency and getting the following error:

> /Package.swift has no Package.swift manifest in https://github.com/SVProgressHUD/SVProgressHUD.git

**Comment by honkmaster** [comment]
I've updated the component and addressed several bugs. Please review version 2.3.0, and should you find any remaining issues, your feedback would be greatly valued.
