### ISSUE TITLE
reason: '-[iosdfu.AppDelegate window]: unrecognized selector sent to instance 0x2834204b0'

### ISSUE THREAD

**Issue by lizhaojie001** [SVProgressHUD/SVProgressHUD#1094]
iOS14.6   8P

**Comment by xiguadalang1** [comment]
在AppDelegate 或者Scene中设置Uiwindow  就不会报错了

**Comment by HelloButler** [comment]
For Objective C, add 
@property (nonatomic, strong) UIWindow *window;
to AppDelegate.h file, it works.

**Comment by xiguadalang1** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by godLoveY** [comment]
您好，邮件已收到

**Comment by xiguadalang1** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by Gargo** [comment]
I have the same issue. The problem is Xcode project had `AppDelegate` only but now it has `SceneDelegate` too. This library doesn't support it

**Comment by xiguadalang1** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by honkmaster** [comment]
I've updated the component and addressed several bugs. Please review version 2.3.0, and should you find any remaining issues, your feedback would be greatly valued.

**Comment by xiguadalang1** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by honkmaster** [comment]
Please provide an English description.
