### ISSUE TITLE
Xcode14.3 File not found: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/arc/libarclite_iphoneos.a

### ISSUE THREAD

**Issue by LiuJinfan** [SVProgressHUD/SVProgressHUD#1104]
File not found: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/arc/libarclite_iphoneos.a

**Comment by iDevelopper** [comment]
Set your pods deployment target to 11 or later in podfile:

```ruby
post_install do |installer|
  installer.generated_projects.each do |project|
    project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
         end
    end
  end
end
```

**Comment by iDevelopper** [comment]
It is not a workaround ! The minimum deployment target Xcode 14 supports is iOS 11.

What do you want to do?

You should elaborate your issue...

**Comment by olejnjak** [comment]
You cannot effectively do that when using Carthage or SPM, the only proper solution is to increase min deployment target in library itself.
