### ISSUE TITLE
Add a release tag 2.2.6 

### ISSUE THREAD

**Issue by aliakhtar-hu** [SVProgressHUD/SVProgressHUD#1107]
Using pod 'SVProgressHUD/AppExtension' doesn't work even after https://github.com/SVProgressHUD/SVProgressHUD/pull/991

[!] CocoaPods could not find compatible versions for pod "SVProgressHUD/AppExtension":
  In Podfile:
    SVProgressHUD/AppExtension

None of your spec sources contain a spec satisfying the dependency: `SVProgressHUD/AppExtension`.

You probably forgot to push the podspec update.

**WHY WE NEED IT**
Since we need to use this as pod spec dependency and in podspec dependency only works with tag

**Comment by aliakhtar-hu** [comment]
@honkmaster needs your attention

**Comment by honkmaster** [comment]
I've updated the component and addressed several bugs. Please review version 2.3.0, and should you find any remaining issues, your feedback would be greatly valued.
