### ISSUE TITLE
memory leak when config SVProgressHud

### ISSUE THREAD

**Issue by ChaoC111** [SVProgressHUD/SVProgressHUD#1109]
when use SVProgressHUD.setBackgroundColor lead memory leak
![02C116B4-F761-4968-8DE4-AFE19381A105](https://github.com/SVProgressHUD/SVProgressHUD/assets/141901969/441cdbc8-26a8-402c-9126-eaea6e840abf)
![83ACD7A9-BBAE-4383-9CF6-2EC465811C87](https://github.com/SVProgressHUD/SVProgressHUD/assets/141901969/b0612199-f631-4fa1-8d0e-4599f9aa0f66)
![84B8A926-8B99-442C-8C27-D7C2692EFD25](https://github.com/SVProgressHUD/SVProgressHUD/assets/141901969/bb9916be-4548-492f-a0a4-86c796022914)

**Comment by honkmaster** [comment]
I've updated the component and addressed several bugs. Please review version 2.3.0, and should you find any remaining issues, your feedback would be greatly valued.
