### ISSUE TITLE
'showError(withStatus:)' returning blank spinner on subsequent appearances

### ISSUE THREAD

**Issue by VanPelt38** [SVProgressHUD/SVProgressHUD#1110]
In our project, if you try and submit an empty form, you get an SVProgressHUD error message and popup. This works, however, if you do this, go out the view, come back and try to do it again, it just shows as blank. Inspecting the debug hierarchy shows that several layers appear to be missing when it's blank, including UIVisualEffectView, UIVisualEffectContentView, and text labels. Thanks in advance for any guidance with this. Pictures attached.
![Simulator Screen Shot - iPhone 14 Pro - 2023-08-16 at 08 38 43](https://github.com/SVProgressHUD/SVProgressHUD/assets/115650433/38d7f693-35af-4eac-87ab-831d598cd15a)
![Simulator Screen Shot - iPhone 14 Pro - 2023-08-16 at 08 39 27](https://github.com/SVProgressHUD/SVProgressHUD/assets/115650433/fc10ef3c-91ce-4e06-9b6c-f16cd8e670c0)

**Comment by honkmaster** [comment]
I've updated the component and addressed several bugs. Please review version 2.3.0, and should you find any remaining issues, your feedback would be greatly valued.
