### ISSUE TITLE
ZKProgressHUD is not working in SPM 

### ISSUE THREAD

**Issue by MHamayun** [SVProgressHUD/SVProgressHUD#1119]
<img width="866" alt="Screenshot 2023-12-12 at 9 50 05 AM" src="https://github.com/SVProgressHUD/SVProgressHUD/assets/33015677/e6950663-2baf-499a-acb3-cfea6cfa7d2b">

**Comment by honkmaster** [comment]
The warning is for ZKProgressHUD not SVProgressHUD
