### ISSUE TITLE
Showing HUD when keyboard resigns as first responder makes it jump

### ISSUE THREAD

**Issue by pepejeria** [SVProgressHUD/SVProgressHUD#125]
The HUD will jump/moved down when showing it when a keyboard is visible and resigns as first responder. 

Example:
# pragma mark - UISearchBarDelegate
- (void)searchBarSearchButtonClicked:(UISearchBar *)searchBar {
  [SVProgressHUD showWithMaskType:SVProgressHUDMaskTypeGradient];
  [searchBar resignFirstResponder];
  }

The HUD will first appear at the top of the screen and move down with the keyboard.

Older versions of of SVProgressHUD did not have this issue since it provided a method where the posY could be defined:
[SVProgressHUD showInView:self.view status:nil networkIndicator:YES posY:-1 maskType:SVProgressHUDMaskTypeClear];

**Comment by macecchi** [comment]
@samvermette I'm still able to reproduce this with iOS 8.3

In my searchBarSearchButtonClicked: method I call resignFirstResponder and then display SVProgressHUD through GCD using @borut-t's code, but I still get the slide down animation.

**Comment by itzAsim** [comment]
Issue still occurring with iOS9 too.

**Comment by lassebunk** [comment]
+1 for occuring in iOS 9 as of May 2016.

**Comment by demchenkoalex** [comment]
If you want to center SVProgressHUD disregard of keyboard is visible or not - modify
`- (CGFloat)visibleKeyboardHeight` in `SVProgressHUD.m` to always return 0

**Comment by iwheelbuy** [comment]
```
extension SVProgressHUD {
    
    func visibleKeyboardHeight() -> CGFloat {
        
        return 0.0
    }
}
```

**Comment by sao101** [comment]
+1 for occuring in iOS 9 as of August 2016.

**Comment by marioqtanjr** [comment]
Swift 4, Xcode 9 - Beta 6

```
extension SVProgressHUD {
    var visibleKeyboardHeight: CGFloat {
        get {
            return 0
        }
    }
}
```

**Comment by protspace** [comment]
+1 ios 11

**Comment by venn0126** [comment]
+1 iOS 11 X
