### ISSUE TITLE
showSuccessWithStatus checkmark not showing when build to device

### ISSUE THREAD

**Issue by hcamatthew** [SVProgressHUD/SVProgressHUD#148]
I'm using showSuccessWithStatus in my project, it works perfectly in the Simulator, but when I build the project to a device (iPhone 4 or iPhone 5) only text appears but no checkmark above it.

Any issues with that happening elsewhere?

**Comment by joshuafeldman** [comment]
Was this every fixed. I still see missing images with the most recent version

**Comment by honkmaster** [comment]
My main issue might be that I am not using Cocoapods on my own ... Most of the time we had an issue like this it was due to that the bundle was not copied during one of the build phases ("Copy bundled resources"). Manually adding the bundle to this phase resolved the issue.
