### ISSUE TITLE
SVProgressHUD not showing when doing work on main thread

### ISSUE THREAD

**Issue by kirani** [SVProgressHUD/SVProgressHUD#161]
Hello,

I am having problems displaying SVProgressHUD when I click on a button in my project. To replicate the problem, I took the SVProgressHUD demo project and updated the "show" method and added a long "for" loop to simulate a long running task. The SVProgressHUD does not show up when I click the "show" button. I even tried to include the SVProgressHUD call in main thread, but the results are same.
- (void)show {
  //dispatch_async(dispatch_get_main_queue(), ^{
  [SVProgressHUD show];
  //});
  
  for (long i=0; i<5000000000; i++)
  {
    if ( i == 4999999999)
        NSLog(@"Ending ...");
  }
  }

Any idea how to resolve this issue?

Thanks,
Kiran

**Comment by habibullah-26** [comment]
Thansk samvermette, Its working good at mine side, if you are using it in splash or any other view, it will be best to use in into the viewdidload.
