### ISSUE TITLE
The New Version of SVProgressHUD not showing  when call dismiss and show at the same time

### ISSUE THREAD

**Issue by thomas-ho** [SVProgressHUD/SVProgressHUD#229]
This happen only with the new version when called as bellow:
[SVProgressHUD showWithStatus:@"test"];
[SVProgressHUD dismiss];
[SVProgressHUD showSuccessWithStatus:@"Great Success!"];

the last status will not show,how could I do ?
my project use the SVProgressHUD as a share HUD,so this call  could happen sometimes.

**Comment by sagargondaliya** [comment]
I have change `FadeInAnimationDuration` and `FadeoutAnimationDuration` to `0.0` and it works fine for me.
I am using HUD like this :
**To Show HUD :**
`func showActivityLoader() {
        
            dispatch_async(dispatch_get_main_queue(), {
                
                SVProgressHUD.show()
                SVProgressHUD.setFadeInAnimationDuration(0.0)
                SVProgressHUD.setFadeOutAnimationDuration(0.0)
                SVProgressHUD.setDefaultMaskType(SVProgressHUDMaskType.Clear)
            })
    }`

**To Hide HUD :** 

`func dismissActivityLoader() {
        
            dispatch_async(dispatch_get_main_queue(), { 
                
                SVProgressHUD.dismiss()
            })
    }`
