### ISSUE TITLE
SVProgressHUDMaskTypeClear ignored and not disabling user interaction (iOS 7.1/Xcode5.1)

### ISSUE THREAD

**Issue by dev-mush** [SVProgressHUD/SVProgressHUD#253]
Is it happening just to me or the mask types appear to be ignored and, specifically, SVProgressHUDMaskTypeClear doesn't seem to disable user interaction anymore?

I had no time to test further but I will soon and post anything on this issue, in the meanwhile I'd like to know if the problem is common or is happening just to me.

**Comment by vangras** [comment]
It seems to occur again in 8.1, with any maskType.

**Comment by honkmaster** [comment]
Can not reproduce, added `[SVProgressHUD setDefaultMaskType:SVProgressHUDMaskTypeClear];` to the demo. Then run the demo and everything works as expected. See the video here: http://youtu.be/N81YogPeRx8

**Comment by vangras** [comment]
Hi, thanks for the quick reply!

If I set it as default, it works. However if I don't:
[SVProgressHUD showWithStatus:errorMessage maskType:SVProgressHUDMaskTypeBlack]
works -  disables interaction

[SVProgressHUD showErrorWithStatus:errorMessage maskType:SVProgressHUDMaskTypeBlack]
doesn't work - doesn't disable interaction

[SVProgressHUD showWithStatus:errorMessage maskType:SVProgressHUDMaskTypeBlack]
doesn't work - doesn't disable interaction

**Comment by skripted** [comment]
I can confirm that setting the default mask type works. Using the methods with integrated mask type, however, don't (at least showError and showSuccess).

**Comment by honkmaster** [comment]
Tried a small bugfix on the master. Please check it out.

**Comment by skripted** [comment]
Looks good! Thank you!

**Comment by avaiyakirtib** [comment]
Replace below method from SVProgressHUD.m as below

+ (void)showWithStatus:(NSString*)status{
    [self sharedView];
      [self setDefaultMaskType:SVProgressHUDMaskTypeGradient];
    [self showProgress:SVProgressHUDUndefinedProgress status:status];
}

**Comment by arjun011** [comment]
SVProgressHUD.show()
        SVProgressHUD.setDefaultAnimationType(SVProgressHUDAnimationType.Native)
        SVProgressHUD.setDefaultMaskType(SVProgressHUDMaskType.Black)

**Comment by ramakrishna013** [comment]
This code worked for me.
If you are using the old classes then Replace below method from SVProgressHUD.m as below
(void)showWithStatus:(NSString*)status{
[self setDefaultMaskType:SVProgressHUDMaskTypeGradient];
[self showProgress:SVProgressHUDUndefinedProgress status:status];
}
