### ISSUE TITLE
window level issue

### ISSUE THREAD

**Issue by yasirmturk** [SVProgressHUD/SVProgressHUD#295]
a bug in ios 7 requires us to make window level more than 0 or UIWindowLevelNormal to enable magnifying glass (the accessibility option), so this makes SVProgressHud stop working. To fix it i had to make this change in the code:
`if (window.windowLevel < UIWindowLevelStatusBar) {`
instead of
`if (window.windowLevel == UIWindowLevelNormal) {`

**Comment by markst** [comment]
this isn't ideal, but my solution for now:
```objc
    if(!self.overlayView.superview){
        NSEnumerator *frontToBackWindows = [UIApplication.sharedApplication.windows reverseObjectEnumerator];
        for (UIWindow *window in frontToBackWindows)
            if ([window isKindOfClass:NSClassFromString(@"UITextEffectsWindow")] == NO) {
                if (window.windowLevel >= UIWindowLevelNormal) {
                    [window addSubview:self.overlayView];
                }
                break;
            }
    } else {
```

**Comment by johnmillz** [comment]
@markst does ``` [[UIApplication sharedApplication]keyWindow] ``` create other issues?

**Comment by zfx5130** [comment]
how to resove it ?

**Comment by yasirmturk** [comment]
@zfx5130  it was fixed
