### ISSUE TITLE
Keep displaying error status until tap on screen

### ISSUE THREAD

**Issue by sadaqata** [SVProgressHUD/SVProgressHUD#304]
Currently, if you use showErrorWithStatus, the HUD disappears after a preset time. I want to keep displaying the HUD in this case until the user taps somewhere on the screen to make sure they saw and read the error. Is this possible?

**Comment by tanalavijay** [comment]
how to reduce the error status animation?

**Comment by seecoolguy** [comment]
maybe something like the duration animation?https://github.com/SVProgressHUD/SVProgressHUD/issues/434

**Comment by tanalavijay** [comment]
yes bro

**Comment by tanalavijay** [comment]
i want to reduce the error status duration
