### ISSUE TITLE
@"UIKeyboard" is now triggering auto-rejection from App Store submit

### ISSUE THREAD

**Issue by tonymillion** [SVProgressHUD/SVProgressHUD#326]
Line 855:

`if([possibleKeyboard isKindOfClass:NSClassFromString(@"UIPeripheralHostView")] || [possibleKeyboard isKindOfClass:NSClassFromString(@"UIKeyboard")])
`

Yay, apple have upgraded their systems and it seems like they are rejecting based on the fact there is a UIKeyboard string/class reference in there!

The rejection is coming from the pre-approval naughty check that looks for private strings/classes being used.

**Comment by EvgenyKarkan** [comment]
👍
