### ISSUE TITLE
Swift: SVProgressHUD.showWithMaskType(SVProgressHUDMaskTypeNone) does not work

### ISSUE THREAD

**Issue by deanq** [SVProgressHUD/SVProgressHUD#338]
How do you choose a type in Swift? The enum definition in the source is not compatible with Swift. You can't choose SVProgressHUDMaskTypeNone, SVProgressHUDMaskType.None, or .None

Anyone else having problems with this?

**Comment by pip8786** [comment]
I had to do this, not sure if it's changed since the one above was posted:
`SVProgressHUD.showWithStatus("Submitting...", maskType: SVProgressHUDMaskType.Black)`

**Comment by arjun011** [comment]
SVProgressHUD.show()
        SVProgressHUD.setDefaultAnimationType(SVProgressHUDAnimationType.Native)
        SVProgressHUD.setDefaultMaskType(SVProgressHUDMaskType.Black)

**Comment by Munchery-KleinLieu** [comment]
With Swift 3.2 and SVProgressHUD v2.2.2 I had to use: ```SVProgressHUDMaskType.clear```
