### ISSUE TITLE
On iPad using iOS 8 the mask doesn't cover the full screen

### ISSUE THREAD

**Issue by cromanderrr** [SVProgressHUD/SVProgressHUD#342]
I'm using SVProgressHUDMaskTypeBlack and sometimes (?!) the mask doesn't cover the full screen.
Using it with cocoapods pointing to head: pod 'SVProgressHUD', :head
The orientation of the indicator looks good but there's the issue with the mask.

**Comment by sansingh30** [comment]
facing same issue while doing portrait to landscape orientation on IPAD on IOS 11.3. It is not yet fixed.
