### ISSUE TITLE
Custom Image Size Restriction

### ISSUE THREAD

**Issue by krzd** [SVProgressHUD/SVProgressHUD#350]
Is there a reason why the image size is restricted to 28x28pt? Would be nice to be able to just use any image.

**Comment by LeeKyungMoon** [comment]
When I added in the image at method '[SVProgressHUD showImage:[UIImage]]'. does it automatically fit to 28 * 28?

**Comment by honkmaster** [comment]
It does not at the moment. The behaviour is not defined, i will see whta i can do.
