### ISSUE TITLE
Wrong mask size after rotation in iOS8

### ISSUE THREAD

**Issue by hubertwang** [SVProgressHUD/SVProgressHUD#377]
Hi,

I found that when I force the app to rotate to portrait orientation, SVProgressHUD's mask size will be abnormal. Precisely, it will no longer be full screen, only cover part of the window. Please take a look at the screenshots below:
1. In login page, my app only allow portrait orientation. Here SVProgressHUD still works fine.
   ![img_2710](https://cloud.githubusercontent.com/assets/1281311/5224854/410fb02c-7716-11e4-8737-06e33813324e.PNG)
2. In main menu, I rotated to landscape then press log out. This will lead me back to login page.
   ![img_2711](https://cloud.githubusercontent.com/assets/1281311/5224853/410bedac-7716-11e4-8d5f-40e3bfb1ac43.PNG)
3. As you can see, when I log in again, the SVProgressHUD's mask is no longer full screen.
   ![img_2712](https://cloud.githubusercontent.com/assets/1281311/5224855/413ac9ba-7716-11e4-8fb8-66cda82d5d5e.PNG)

Did I miss any setting or something? Or this is a bug of SVProgressHUD?

**Comment by edwardmp** [comment]
Unfortunately I still encounter this issue on iOS 9. In a navigation controller I first encounter a SVProgressHud that loads fine in a view. Then I go one step back in the nav hierarchy, rotate my device, then again go that view, I only see a partial mask (about half the screen in iPhone 6 landscape).
