### ISSUE TITLE
SVProgressHUDDidReceiveTouchEventNotification is not fired

### ISSUE THREAD

**Issue by kalys** [SVProgressHUD/SVProgressHUD#401]
I use alert this way:

```
[SVProgressHUD showErrorWithStatus:@"Bla bla" maskType:SVProgressHUDMaskTypeClear];
```

and I don't receive `SVProgressHUDDidReceiveTouchEventNotification` notification because `self.overlay.userInteractionEnabled` depends on maskType https://github.com/TransitApp/SVProgressHUD/blob/master/SVProgressHUD/SVProgressHUD.m#L630

But given maskType is lost here. https://github.com/TransitApp/SVProgressHUD/blob/master/SVProgressHUD/SVProgressHUD.m#L159

**Comment by honkmaster** [comment]
It is working for me.

**Comment by kalys** [comment]
I reproduced this issue here:
https://github.com/kalys/SVProgressHUD-bug-reproduce/blob/master/ololo/ViewController.m#L30

**Comment by honkmaster** [comment]
I recently rechecked. The `SVProgressHUDDidReceiveTouchEventNotification` is firing, also integrated for test in the demo app.

**Comment by huguesbr** [comment]
I think it's only fire if maskType is set to `SVProgressHUDMaskTypeNone`

```
SVProgressHUD.setDefaultMaskType(.none)
```

see here: https://github.com/SVProgressHUD/SVProgressHUD/blob/master/SVProgressHUD/SVProgressHUD.m#L889-L897
