### ISSUE TITLE
SVProgressHud Crashes when show/hide SVProgress in multiple  view controllers.

### ISSUE THREAD

**Issue by Monika-Tapadiya** [SVProgressHUD/SVProgressHUD#435]
I am using [SVProgressHud Show] and [SVProgressHud Dismiss] in multiple viewcontrollers and it is giving Bad_Excess error some times.  
   self.imageView.hidden = YES; here 
some times                 [window addSubview:self.overlayView];

-[CALayer isHidden]: message sent to deallocated instance 0x78e3a6e0 and
-[CALayer Sublayers] message sent to deallocated instance 0x78e3a6ds.
My project is having ARC in it.Can please suggest how to solve this error.
Thanks.

**Comment by honkmaster** [comment]
Please provide a demo project.
