### ISSUE TITLE
HUD with Duration

### ISSUE THREAD

**Issue by hydr93** [SVProgressHUD/SVProgressHUD#453]
I think that, these HUD be shown with durations. For example, I want to show HUD for 3 seconds and then dismiss it. I need to use NSTimer and a Selector Function in order to do that. However, the same in the library will make the library richer in my opinion.

**Comment by cameronehrlich** [comment]
Would a general purpose solution like this solve your use case?
https://github.com/TransitApp/SVProgressHUD/issues/484

**Comment by honkmaster** [comment]
Please check #484.
