### ISSUE TITLE
EXC_BAD_ACCESS because of UIView.superview

### ISSUE THREAD

**Issue by chenshengzhi** [SVProgressHUD/SVProgressHUD#462]
![2015-08-19 3 00 43](https://cloud.githubusercontent.com/assets/2027667/9350398/3d27e05a-4683-11e5-8c95-c134edc404ed.png)
![2015-08-19 3 01 29](https://cloud.githubusercontent.com/assets/2027667/9350401/400d440e-4683-11e5-95ff-0ca73fed8a7c.png)

i think should remove all subviews from _hudView, _overlayView befor dealloc
![qq20150819-4 2x](https://cloud.githubusercontent.com/assets/2027667/9350905/21338d82-4687-11e5-943e-dc7745ea442a.png)

i do  this
```
@implementation UIView (SVProgressHUD)

- (void)dealloc {
    [self.subviews enumerateObjectsUsingBlock:^(id obj, NSUInteger idx, BOOL *stop) {
        [obj removeFromSuperview];
    }];
}

@end
```

**Comment by honkmaster** [comment]
Could you provide a sample project to demonstrate the crash. I can not reproduce your error.

**Comment by chenshengzhi** [comment]
I think i has find out why it happens: 
```
@implementation UIView (BKRemove)

- (void)dealloc {
    [self bk_removeAllBlockObservers];
    [self bk_removeAllAssociatedObjects];
}

@end

```
If i comment UIView's dealloc category,  the crash doesn't happen.

I has upload the [demo](http://pan.baidu.com/s/1mgIjFDm)

**Comment by Payal2793** [comment]
When internet is not reachable or could not connect to server or request timed out , this kind of situation arises at that time svprogress hud shows bad_access error some time in hud view or some times in string label in svprogresshud.m file.please help.

**Comment by honkmaster** [comment]
Such a bug is very hard to reproduce. Therefore, you have to provide a demo project to help me solve the issue.

**Comment by honkmaster** [comment]
No feedback therefore closed.
