### ISSUE TITLE
Xcode 7 / iOS 9: HUD hangs around on top of Facebook App when fast-switching out to native share dialog

### ISSUE THREAD

**Issue by fatuhoku** [SVProgressHUD/SVProgressHUD#487]

**Comment by honkmaster** [comment]
Please provide a more detailed bug description! How to reproduce? What environment? On device? On simulator? Images?

**Comment by fatuhoku** [comment]
Hey @honkmaster I finally got around to taking some screenshots. Here's our app's login with Facebook screen.

![simulator screen shot 6 oct 2015 11 35 39](https://cloud.githubusercontent.com/assets/430233/10306353/613c0974-6c1e-11e5-94ca-cbe25d5a5aed.png)

Once you touch Continue with Facebook, the HUD appears, and then the Facebook app comes up from the bottom and covers the login screen.

![simulator screen shot 6 oct 2015 11 33 47](https://cloud.githubusercontent.com/assets/430233/10306368/7c5bc320-6c1e-11e5-8ba7-a5d6f428eb79.png)

Note that the HUD stays on top of everything throughout this entire process, which obstructs whatever Facebook is trying to display.

![simulator screen shot 6 oct 2015 11 33 38](https://cloud.githubusercontent.com/assets/430233/10306406/b980d1d2-6c1e-11e5-8602-56a6e569d53c.png)


This wasn't a problem in iOS 8, because fast-app-switches were performed by transitioning sideways out of the current app and into the other one.

**Comment by fatuhoku** [comment]
@honkmaster Any idea what could be done as a workaround for this?

**Comment by thiagoross** [comment]
Ive been facing the same problem. Actually, I'm trying to work on a solution where the HUD is dismissed right after browser with Facebook login appears, if I get any results I post it here.

**Comment by fatuhoku** [comment]
@thiagoross That'll be helpful, thanks.  I'm using Parse at the minute and it looks like there is a noticable delay between the Facebook login interface's dismissal and the Facebook login success callback being called. Not sure how to fill this gap with SVProgressHUD.

**Comment by thiagoross** [comment]
@fatuhoku This is what I did:

* On my View Controller with the Facebook button I created a flag boolean called "authenticating", this will control the current view state
* On my log in function (logInWithFacebook:)
    * Set authenticating = true
    * Show SVProgressHUD
    * Call Facebook SDK log in function
    * Set authenticating = false and dismiss SVProgressHUD when log in is finished
* **In the viewWillDisappear function dismiss SVProgressHUD**
* In the viewWillAppear function show SVProgressHUD again

Doing this, that is what is going to happen in sequence:
- You press the Facebook button
- SVProgressHUD appears
- Some time until something happen (Don't ask me why there is a delay :)
- SVProgressHUD disappears
- Facebook log in is showed
- You log in
- SVProgressHUD appears again
- Still processing
- SVProgressHUD disappears again

**Comment by honkmaster** [comment]
Are you able to provide a demo project?
