### ISSUE TITLE
SVProgressHUD + MTStatusBarOverlay issue

### ISSUE THREAD

**Issue by nihilenz** [SVProgressHUD/SVProgressHUD#495]
Hello,
SVProgressHUD is my favorite HUD library, but I have an issue with a project where MTStatusBarOverlay is already integrated. MTStatusBarOverlay is a status bar overlay window.
The result is that after a while `overlayView` has the frame of the status bar and SVProgressHUD is shown inside the status bar.
As work-around, I replaced `[UIApplication sharedApplication].keyWindow.bounds` with `[UIScreen mainScreen].bounds` in `overlayView` getter and `positionHUD:` method.
Any suggestions?
Thank you very much

**Comment by honkmaster** [comment]
I can not comment on this case because I am not using MTStatusBarOverlay.
