### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by zdrjson** [SVProgressHUD/SVProgressHUD#503]
method  "+ (void)showErrorWithStatus:(NSString*)status ", if status is "null" from server,then app will crash ,should you judge or filter somethings?

**Comment by honkmaster** [comment]
Here, Asserts would be perfect ;). PR is welcome.

**Comment by honkmaster** [comment]
In addition: Can not reproduce. Please provide a demo project where the bug occurs and reopen if necessary. (See also #642 )
