### ISSUE TITLE
Cocoapods: `SVProgressHUD.bundle`not added to "Copy Bundle Ressources"-Phase

### ISSUE THREAD

**Issue by honkmaster** [SVProgressHUD/SVProgressHUD#514]
Hi, we are aware of a problem regarding the Podfile (e.g. #449). It seems that the `SVProgressHUD.bundle` is not copied to the "Copy Bundle Resources" Build Phase. Due to this continuing problem we are searching for someone that could check and help with this problem. We are not using Cocoapods on our own and are happy for pull request.

**Comment by honkmaster** [comment]
Maybe `pod install` is the solution?

**Comment by x2on** [comment]
Here looks all fine. 
Using 1.1.3 works good here with CocoaPods.

**Comment by honkmaster** [comment]
Another try. Should be fixed due to https://github.com/SVProgressHUD/SVProgressHUD/commit/de93d1cdcbf76db6d6526db2b629760413cddea8 and #542.
