### ISSUE TITLE
Hud Not Centered

### ISSUE THREAD

**Issue by donileo** [SVProgressHUD/SVProgressHUD#522]
So when testing in the simulator and in my app SVProgressHUD fails to be centered correctly. The suspecting line is line 660 ---> 
.....
} else {
 keyboardHeight = self.visibleKeyboardHeight; 
}

of SVProgressHud.m

Apparently this is doing a call to search the window subviews for a keyboard and is factoring in a keyboard height into the centering. The problem is this is returning a keyboard height when there is no keyboard on the screen so I'd suggest refactoring that method to do better detection.

**Comment by honkmaster** [comment]
I see you used `RKeyboardListener` in you clone. However, we can not integrate an additional third-party lib. Do you think it would be a good idea to "transfer" the code to this one?

**Comment by donileo** [comment]
Hey @honkmaster: Yes I have no problem if you guys want to just copy that. Unfortunately when looking at the design of SVProgressHUD there was no way to know the size of the keyboard as soon as the hud gets displayed hence the reason why a listener has to be installed and running in the app. Considering how lightweight the listener is and the added advantages (being able to detect if the keyboard is shown and its size appwide) I decided this method is better than attempting to identify the keyboard view in the window hierarchy which is hacky..

**Comment by peymankh** [comment]
Same issue here.
