### ISSUE TITLE
Progress bar not showing First Time in iOS9 Swift

### ISSUE THREAD

**Issue by mabuhegde** [SVProgressHUD/SVProgressHUD#523]
I am using SVProgressHUD 1.1.3 cocoapods 0.38.2 version in a swift project. SVProgressHUD only showing when i killed the app and relaunch. i tried 1.1.2 no luck. I am about to release my app.

**Comment by honkmaster** [comment]
Check the lastets 2.0-beta please.

**Comment by mahabaleshwarhnr** [comment]
I have login with facebook in my app. I changed the login behaviour to Web, native, System account. SVProgressHUD only work when login behaviour is Web and System account. Facebook not allow to login with facebook app from iOS 9. By forcible it will open safari view controller. When i use login behaviour to native and browser SVprogressHUD wont display through out the app.
see this thread http://stackoverflow.com/questions/34331597/svprogresshud-not-showing-in-ios-9-when-app-using-login-with-facebook.   can you help me to resolve problem.

**Comment by mahabaleshwarhnr** [comment]
@honkmaster any update on this?
```
func loginButtonWillLogin(loginButton: FBSDKLoginButton!) -> Bool {
        SVProgressHUD.showWithStatus(NSLocalizedString("FB_USER_FETCH_MSG", comment: ""))
        return true
    }
```
if i implement this method SVProgressHUD is displaying. after getting the call back
``` 
func loginButton(loginButton: FBSDKLoginButton!,
        didCompleteWithResult
        result: FBSDKLoginManagerLoginResult!,
        error: NSError!)  {
 // error or success handling. SVProgressHUD not displaying through out the app.
}

```

**Comment by honkmaster** [comment]
No update.
