### ISSUE TITLE
Program crash

### ISSUE THREAD

**Issue by wolikeq** [SVProgressHUD/SVProgressHUD#530]
hello，when I used it in my project,  there had some problem,like this:
 [SVProgressHUD showSuccessWithStatus:@"cool!!!"];

*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[NSBundle initWithURL:]: nil URL argument'
*** First throw call stack:
(0x183e0cf48 0x1992b7f80 0x183e0ce90 0x184cd9bf8 0x184cd9b7c 0x10010126c 0x1000ff690 0x100709c68 0x10070aae0 0x1000ff59c 0x100100674 0x100117194 0x1893d7cfc 0x1893d7c78 0x1893bf930 0x1893d7590 0x1893d71c0 0x1893cfcdc 0x1893a04a4 0x18939e76c 0x183dc4544 0x183dc3fd8 0x183dc1cd8 0x183cf0ca0 0x18f274088 0x189408ffc 0x1000ee198 0x199afa8b8)
libc++abi.dylib: terminating with uncaught exception of type NSException

The break point is in the creation of a single case of the block problem,like this:
#if !defined(SV_APP_EXTENSIONS)
    
    dispatch_once(&once, ^{ sharedView = [[self alloc] initWithFrame:[[[UIApplication sharedApplication] delegate] window].bounds];});
in my xcode 7.1
and  could you help me?

**Comment by asad-appifytech** [comment]
I am also having the same issue. It was working fine before, but after updating Pods, it's crashing. :(

**Comment by asad-appifytech** [comment]
I fixed it by removing "use_frameworks!" in Podfile.
@wolikeq: Can you please try this solution if you are using Pods?

**Comment by wolikeq** [comment]
sorry, I'm not using Pods in my project, just drag the file into the project,  I suggest you look at your thread,  I was forget  to refresh the UI into the main thread

**Comment by wolikeq** [comment]
sorry, I'm not using Pods in my project, just drag the file into the project

**Comment by LukeDurrant** [comment]
So this makes the assumption that your AppDelegate has a window varable

**Comment by honkmaster** [comment]
What do you want to say with that? Yes, the code does make the assumption, seems to be quite clear. Is there a problem?
