### ISSUE TITLE
Move SVProgressHUD to own organization

### ISSUE THREAD

**Issue by honkmaster** [SVProgressHUD/SVProgressHUD#532]
I want to propose to move `SVProgressHUD` to an own organization on GitHub (https://github.com/SVProgressHUD). This is comparable to: 

RestKit: https://github.com/RestKit/RestKit
Alcatraz: https://github.com/alcatraz/Alcatraz
TextMate: https://github.com/textmate/textmate

FYI: I already created the organization and would give managing rights to all previous repo admins. @samvermette What's your opinion?

**Comment by samvermette** [comment]
@honkmaster good idea. Do I have to do something?

**Comment by honkmaster** [comment]
You just have to go to settings of the this repo and then transfer ownership. I already invited you to be an co-owner of the newly created organisation. This way you have the same rights as before. The only thing we have to do in addition is to invite all the previous collaborators to the new organisation so they can commit as usual.
