### ISSUE TITLE
preferredFontForTextStyle check is tripping an All Exceptions breakpoint 

### ISSUE THREAD

**Issue by fatuhoku** [SVProgressHUD/SVProgressHUD#537]
When I run my project with the following breakpoint setting:

![screen shot 2016-01-12 at 20 29 45](https://cloud.githubusercontent.com/assets/430233/12276031/4ad460c4-b96b-11e5-8a9d-a3025b4c93d9.png)

The debugger breaks here:

![screen shot 2016-01-12 at 20 27 10](https://cloud.githubusercontent.com/assets/430233/12275992/0dbf770a-b96b-11e5-918e-6dccafe65faa.png)

Here's the offending code:

```objc
        if ([UIFont respondsToSelector:@selector(preferredFontForTextStyle:)]) { // this line
            _font = [UIFont preferredFontForTextStyle:UIFontTextStyleSubheadline];
        } else {
            _font = [UIFont systemFontOfSize:14.0f];
        }
```

I don't expect any library I use to trigger exceptions! Is there any way to perform this check without tripping the breakpoint?

**Comment by honkmaster** [comment]
First: If you don`t expect any library to trigger some bugs than you probably should write any code on your own. Second: I do not see this behaviour in the demo and also my apps. Provide a demo where the bug is replicated.

**Comment by fatuhoku** [comment]
> If you don`t expect any library to trigger some bugs than you probably should write any code on your own.
@honkmaster you've completely missed my point. I said I didn't expect libraries I use (in their normal operation) to trigger exceptions. The fact that an exception is triggered IS a bug. I fully expect there to be bugs in open source projects.  I have nothing against SVProgressHUD, if that's what you're suggesting.

Anyway, I found out my issue — I stuck `[SVProgressHUD setDefaultMaskType:SVProgressHUDMaskTypeClear];` into `-load`... not a good idea!

**Comment by cartermike** [comment]
@fatuhoku where is it a bad idea to call from?

**Comment by fatuhoku** [comment]
`+load`. http://stackoverflow.com/a/13326633/590767

**Comment by williamgp** [comment]
I'm not calling it from `+load` but I get the same issue
