### ISSUE TITLE
HUD not showing when called from within UITabBarController

### ISSUE THREAD

**Issue by ghost** [SVProgressHUD/SVProgressHUD#54]
Hi,

I am using a UITabBar and call

   `[SVProgressHUD showWithStatus:@"Loading..."];`

from within one of the Tabbar's Viewcontrollers. 

The Activityindicator shows, but the HUD is not showing at all.
This issue might also be related to [Issue 20](https://github.com/samvermette/SVProgressHUD/issues/20).

**Comment by keshavx11** [comment]
Call this in didFinishLaunchingWithOptions:
SVProgressHUD.setContainerView(UIApplication.shared.keyWindow)
