### ISSUE TITLE
about SVProgressHUD Modal

### ISSUE THREAD

**Issue by leiyong316** [SVProgressHUD/SVProgressHUD#543]
After how to set SVProgressHUD show,  Other inoperable。

thanks

**Comment by honkmaster** [comment]
I do not understand your englisch. Could you please elaborate a little more? Especially I need more details like how does the error happen, how to reproduce, maybe also a demo project.

**Comment by leiyong316** [comment]
@honkmaster  thank you reply， no error,    i need display for Modal View

**Comment by leiyong316** [comment]
@honkmaster  i got it,  need set SVProgressHUDMaskType..thank you
