### ISSUE TITLE
2.0-beta2 -showSuccessWithStatus: issue

### ISSUE THREAD

**Issue by KiranPanesar** [SVProgressHUD/SVProgressHUD#544]
Hey! We've been using SVProgressHUD for a while and noticed an issue this morning. Our application that was previously showing a success HUD with a caption was now just indefinitely showing a loading HUD.

I dug into our code and we are calling SVProgressHUD like so:

```objectivec
[SVProgressHUD showSuccessWithStatus:statusText];
[SVProgressHUD dismissWithDelay:5];
```

It appears that `+showSuccessWithStatus:` is now just showing the default spinner, as if we were calling `+show`.

**Comment by honkmaster** [comment]
Can replicate. Will fix now.

**Comment by honkmaster** [comment]
This is related to https://github.com/SVProgressHUD/SVProgressHUD/commit/a15edf3a4fc5aabb1f423b09edb20cf68bd5c397 and `[[NSOperationQueue mainQueue] addOperationWithBlock:^{}]` ...
