### ISSUE TITLE
Success image is black

### ISSUE THREAD

**Issue by abraxascorner** [SVProgressHUD/SVProgressHUD#547]
I have the following code
```objective-c
[SVProgressHUD setBackgroundColor:[UIColor colorWithHexString:@"f1f1f1"]];
                  UIImage *successImage = [UIImage imageNamed:@"success"];
                  [SVProgressHUD setSuccessImage:successImage];
                  [SVProgressHUD showSuccessWithStatus:NSLocalizedString(@"Comment sent.",@"")];
                  [self performSelector:@selector(close:) withObject:nil afterDelay:2.0];
```
My image is not showing (it shows a black square) and background color is not applied. This code worked when I was building with iOS 8 sdk.

I am using 2.0-beta3.

**Comment by honkmaster** [comment]
Have you set `SVProgressHUDStyleCustom` via `setDefaultStyle:`.

**Comment by abraxascorner** [comment]
@honkmaster yep, my background color was also not working (it worked before), but after I setup that property, it worked. 
It is interesting that default image is showing and the only difference between my image and default image is that my image is not transparent. I believe that it has something to do with tintColor and iOS 9 SDK. So, I will try with transparent image and try to do a demo, I am on a tight schedule with my project. :)

**Comment by honkmaster** [comment]
The best case would If you replicate the issue in our `SVProgressHUD` demo and send me the zip. However, You could also give me steps how to reproduce.

**Comment by abraxascorner** [comment]
@honkmaster I have attached a demo, so you could check. My example is in the method - showSuccessWithStatus on the 86th line of code in ViewController.m file. 
[Demo - Nemanja.zip](https://github.com/SVProgressHUD/SVProgressHUD/files/98936/Demo.-.Nemanja.zip)

**Comment by honkmaster** [comment]
Great, will check it this evening (I am currently at work. the HUD is only my leisure-time program ;)).

**Comment by abraxascorner** [comment]
@honkmaster ok, thank you. :)

**Comment by abraxascorner** [comment]
@honkmaster yep, the problem was that my image was not transparent, so tintColor "was painting" all image in black. 
But, I want for my image to be green and my text to be black. Is there any option to achive this?

**Comment by honkmaster** [comment]
I understand correct that you found your bug? And do I understand it right that you want to set the image and tet color independently?

**Comment by abraxascorner** [comment]
Well, I am not sure if it ok just to support transparent image. If image is not transparent, that is a square filled with color.
 I don't want to set the image color, I just want to use it as I created and not with default or some other tint color.

**Comment by honkmaster** [comment]
This "limit" was not introduced by us. `UIImageRenderingModeAlwaysTemplate` introduced with iOS 7 required a transparent image. From the internet: "UIImageRenderingModeAlwaysTemplate mode will replace all non-transparent colors on a UIImage with the tint color. The entire background and any portion of the image that you do not wish to render using the tint color must be completely transparent."

**Comment by abraxascorner** [comment]
@honkmaster ok, but maybe you should have option keep original, so people could use non-transparent images if they like?
And still the problem with different text color and image color cannot be solved?

**Comment by abraxascorner** [comment]
@honkmaster ok

**Comment by honkmaster** [comment]
As long as I maintain this project (mid 2014) there has never been the option to have different image and text colors. In addition this is also true for the image tinting, there has never been the option to use  an image as is (as least as i know).

**Comment by abraxascorner** [comment]
@honkmaster I guess it was Apple feature. :)
![img_7817 copy](https://cloud.githubusercontent.com/assets/1971970/12549005/82d28a2a-c35a-11e5-844d-9cd30b96c03e.png)
This was how lib worked building with iOS 8 SDK. And we discussed how it is working on iOS 9. 
Sorry for Serbian.

**Comment by honkmaster** [comment]
Will close for now as this is an adhancement and not a real bug.

**Comment by ZMAsd** [comment]
could you tell me how to solve this problem ?  when i use setSuccessImage method the image is still black

**Comment by Arpit723** [comment]
i tried this code
