### ISSUE TITLE
When showing with nil image, layout wrong size

### ISSUE THREAD

**Issue by Sunnyyoung** [SVProgressHUD/SVProgressHUD#548]
In `2.0.0-beta` version
![image](https://cloud.githubusercontent.com/assets/5926284/12442216/1338f3cc-bf89-11e5-8e0d-d8b851e5c63e.png)

In `2.0.0-beta4` version, the latest version
![image](https://cloud.githubusercontent.com/assets/5926284/12442224/29576580-bf89-11e5-8d7d-1e42051bc366.png)

Any workaround can solve?

**Comment by honkmaster** [comment]
Will fix tonight.

**Comment by Sunnyyoung** [comment]
Great!

**Comment by honkmaster** [comment]
You`re welcome.
