### ISSUE TITLE
HUD not showing in modal VC(2.0-beta6)

### ISSUE THREAD

**Issue by kwosu87** [SVProgressHUD/SVProgressHUD#549]
It work perfectly in first VC(Main screen), but there's an issue in a specific screen.

Here is a workflow.

1. Click a button to pick photo at Main screen(Modal, PhotoPicker VC)
2. After selecting photo, another VC show up(Modal)
3. Click a button to show HUD(`show()`)
4. Click a button to hide HUD(`dismiss()`)
5. Now I can't make HUD visible with `show()` in this screen.

When after I went back to main screen and tried this one more, HUD is not shown at step 3.
And it still worked in Main VC. This problem only happens in that screen.

Is there any way to solve this? I tried this situation in the stable version(1.1.3), and there is no problem like this.

**Comment by honkmaster** [comment]
Do you call `show` from the VC that i currently being displayed?

**Comment by kwosu87** [comment]
Yes, I did like you said, and thank you for solve this situation! I really need `dismissWithDuration`!

**Comment by kwosu87** [comment]
Yes I did, and thank you for solve this situation! I really need 2.0 version because of `dismissWithDuration()`!

**Comment by kwosu87** [comment]
@honkmaster I tested new `beta-8 version`, and it's still not working. It happens when I use both `dismiss()` and `dismissWithDelay()`. 

I call `show()` in second modal VC(currently being displayed), and I show some animations at the same time. HUD is dismissed after about 1 secs.

After animations are over(about 3 secs, HUD is dismissed), the VC is dismissed, and I can't see HUD in that VC again. (retry 1~4). 

I hope you find out the problem :) Let me know if I can help you.

**Comment by honkmaster** [comment]
Because your case is hard to understand without seeing it I would like a demo project. This would help a lot.

**Comment by kwosu87** [comment]
@honkmaster I made a demo project and I found the exact issue. so you don't need to see my proj.

Here is the thing. It's related not VCs but my callback method. One of callback method(location) invoked sometimes immediately, and sometimes several seconds later. The problem happens when invoked immediately. I expected when I use `dismissWithDelay(1.0)` right after `show()`, HUD would visible for 1 seconds, but actually HUD was not visible in this situation. That's why I consider this as a bug.

I think some people would need feature because of callback method(that we can't control), so I wonder what you think about this situation.

**Comment by kwosu87** [comment]
And this is my code to avoid this situation.

```swift
dispatch_async(dispatch_get_global_queue(QOS_CLASS_USER_INITIATED, 0)) {
  NSThread.sleepForTimeInterval(NSTimeInterval(1))
  dispatch_async(dispatch_get_main_queue()) {
    SVProgressHUD.dismiss()
  }
}
```

**Comment by honkmaster** [comment]
Will look into it.
