### ISSUE TITLE
Progress HUD intersects with default spinner

### ISSUE THREAD

**Issue by rozd** [SVProgressHUD/SVProgressHUD#551]
Hi,

There are some strange behaviours which may be interesting for you:

STR for Demo application:
1. After Demo launch click "show" button
2. Tap "dismiss" button
3. Tap "showWithProgress:"

Then you can see that progress indicator and spinner are intersect:
![screen shot 2016-01-26 at 4 27 22 pm](https://cloud.githubusercontent.com/assets/158493/12583138/d65ed2e4-c449-11e5-8a77-1c4baa78cab4.png)

4. Next tapping on "showSuccessWithStatus:" gives the next result:
![screen shot 2016-01-26 at 4 29 17 pm](https://cloud.githubusercontent.com/assets/158493/12583190/2d38ef78-c44a-11e5-93c6-fbff2f2399fc.png)

Thanks!

EDIT: this is for master branch

**Comment by honkmaster** [comment]
Will fix now.
