### ISSUE TITLE
HUD doesn't `dismiss` if called immediately after the `show` (bug)

### ISSUE THREAD

**Issue by Vinzius** [SVProgressHUD/SVProgressHUD#555]
Hey !

First, thanks for your lib ;)

Problem happens:
- With the 2.0 beta8.
- Can reproduce every time

Problem: if you try to dismiss the HUD just after displaying it, then it won't work.

Example:
```[SVProgressHUD show];
[SVProgressHUD dismiss];```

Reason: the library check if the HUD is displayed when we try to hide it. But in this case, the HUD isn't displayed yet (because the action is in a queue). So we eventually are stuck :-(

Maybe we could move the logic "if([self isVisible]) { }" inside the block execution and not before ?

Cheers,

Vincent

**Comment by honkmaster** [comment]
Good catch, at first it was not obvious why you want to immediately dismiss, but a use case might be that you want to cancel the show. Sure moving might be an idea, I am quite busy at the moment with other projects, so PR is very welcome.

**Comment by Vinzius** [comment]
Yep that's the case. The dismiss is inside a completion block, which can be called directly after!

I'll try to find some time in the coming week!

**Comment by honkmaster** [comment]
Hi, since when did you use this library? This `bug` with the check (`self isVisible] `) exists since https://github.com/SVProgressHUD/SVProgressHUD/commit/28b88ca59839161bda2df5eba7188ac3477ce71a (back in 2013). So I think the behaviour you see is intended. However I agree it should work the way you want it.

**Comment by Vinzius** [comment]
Hi, I'm new with the library. It's being used in a project I'm giving some help before its release in the App Store!

**Comment by miquelbotanch** [comment]
it also happens in this code:

    [[NSOperationQueue mainQueue] addOperationWithBlock:^ {
        [SVProgressHUD setDefaultMaskType:SVProgressHUDMaskTypeBlack];
        [SVProgressHUD showWithStatus:NSLocalizedString(@"filtrando", nil)];
    }];
...... execute some sqlite code... 

    [[NSOperationQueue mainQueue] addOperationWithBlock:^ {
        [SVProgressHUD dismiss];
    }];

if the code in the middle is too fast .. it never dismisses.

**Comment by paulpilone** [comment]
I have a small block of code that uses an NSFileCoordinator to copy a small file from one location to another. I'm able to reproduce this issue on 2.0-beta2. It appears (at least for me) to be a regression between -beta and -beta2.

**Comment by honkmaster** [comment]
Quick update: I currently have no mac anymore (defect). I will continue work (and also invest some time to this issue) when I have the time and money to repair the machine.

**Comment by hjf325802** [comment]
I meet this issue too. I find that method "isVisible" is inappropriate.If you do not modify "isVisible" method, using dispatch_after 0 second shows good performance.

**Comment by Vinzius** [comment]
Hi! I just submitted a PR. I think it'll solve most of the issues + the easiest way to solve the bug while not adding too much code.

@honkmaster sad for the defect :-( I hope you'll trust me for the PR and add it to the next beta-release :-)

Cheers

**Comment by davidrothera** [comment]
:+1: This works for me, when calling showProgress before it would end up not dismissing the HUD at the end because going from 0.9999 -> 1.0 and completing the progress happens too quickly.

@honkmaster is your Mac back yet? If not would you contemplate pushing this PR? Tested and works ok for me.

**Comment by svilon** [comment]
Hi! I have same issue on latest version (2.0). I think @Vinzius solution is more stable.

**Comment by allaire** [comment]
Issue is still happening on master

**Comment by Vinzius** [comment]
Yep, I don't think the commit abd1b38 will help. Why not taking my PR?

**Comment by honkmaster** [comment]
@Vinzius solution is valid. However, the `addOperationWithBlock:` must be used used in the local `dismissWithDuration` function. Will push soon.

**Comment by honkmaster** [comment]
Check the latest master. If you agree, I will tag version 2.0.1

**Comment by ChrisMISDB** [comment]
Just letting you know that the master fixed an issue I had that's the same or related to this issue.  Showing the hud of viewdidload and if the process finished and it's dismissed before the view is displayed it was never dismissing the HUD.  Works fine with the master branch.  Thanks!

**Comment by svilon** [comment]
Yep, update looks good.
