### ISSUE TITLE
Grace Mode

### ISSUE THREAD

**Issue by donileo** [SVProgressHUD/SVProgressHUD#556]
Can the grace mode option be added to SVProgressHUD. Essentially if SVProgressHUD is called to present it should only display itself after x.f seconds. This is really important to prevent showing the hud for microsecond duration calls.

So for example:

```
[SVProgressHUD showWithGraceTime:3.f];
```

or to set globally 

```
[SVProgressHUD setGraceTime:3.f];
[SVProgressHUD show]
```

Will only show the hud if a [SVProgressHUD dismiss] is not called in 3.f seconds.

**Comment by honkmaster** [comment]
I have something similar for one of my apps `+ (void)showWithStatus:(NSString*)status afterInterval:(NSTimeInterval)interval`. However, this is only for the simple `showWithStatus` method. Internally it is implemented with a show time, which is cancelled by calling dismiss. A global grace period is a good idea. A pull request is welcome.

**Comment by donileo** [comment]
:) will look into a PR as soon as I have some free time.

**Comment by honkmaster** [comment]
Quick update: I currently have no mac anymore (defect). I will continue work (and also invest some time to this issue) when I have the time and money to repair the machine.

**Comment by Rusik** [comment]
+1 for this feature

**Comment by guidev** [comment]
+1

**Comment by ngheungyu** [comment]
+1 thanks

**Comment by top2tech** [comment]
This is a very important feature, which can provide much better user experience. 
With current high performance backend server, network call can respond very quickly, the short-lived progress flash may confuse or irritate users.

**Comment by isaced** [comment]
+1
