### ISSUE TITLE
TimeOut

### ISSUE THREAD

**Issue by Saulenco** [SVProgressHUD/SVProgressHUD#559]
a time out functionality will be great, because not all the request returning something :)

**Comment by honkmaster** [comment]
Time out for what? What should happen during a time out? Please give more details.

**Comment by Saulenco** [comment]
timeOut for dismissing the HUD, because there are some request (eg:parse) where sometimes you don't receive a response(success or fail) and the hud si on the screen and the user cand do anything only the kill the app and restart again

**Comment by honkmaster** [comment]
Why do you think it is the responsibility of `SVProgressHUD` to dismiss itself if your application code fails? The `HUD` itself is "stupid" and should not keep track of your application state. Why do you not add a timer on your own?

**Comment by Saulenco** [comment]
thanks man nice component but I guess that I will use then MBProgressHUD.

**Comment by glennposadas** [comment]
If someone wants a functionality like this, I think you can extend the `SVProgressHUD` and add a class func like so:

```
/** A category for SVProgressHUD.
 *  This will give you a `timeout` functionality for the HUD.
 */

extension SVProgressHUD {
    open class func show(_ status: String, maxTime: TimeInterval) {
        SVProgressHUD.show(withStatus: status)
        
        DispatchQueue.main.asyncAfter(deadline: DispatchTime.now() + maxTime) {
            SVProgressHUD.dismiss()
        }
    }
}
```
