### ISSUE TITLE
Does not work well with iPad multitasking

### ISSUE THREAD

**Issue by rosskimes** [SVProgressHUD/SVProgressHUD#560]
It seems that the HUD is centered in the screen, not the application's window when multitasking is enabled on iPads.
![image](https://cloud.githubusercontent.com/assets/302299/13273185/42c89180-da67-11e5-809a-8064898e4c45.png)

**Comment by honkmaster** [comment]
Did you try the latest release / beta?

**Comment by rosskimes** [comment]
Never mind. I was pointing to the latest release. Works well on latest beta. Thanks!

**Comment by honkmaster** [comment]
I currently have no mac anymore (defect). Otherwise I already would have release the final 2.0. Sorry.
