### ISSUE TITLE
Bundle version string in Info.plist breaking fastlane builds

### ISSUE THREAD

**Issue by ergunkocak** [SVProgressHUD/SVProgressHUD#563]
Hello,

Bundle version string in Info.plist "2.0-beta8" is causing fastlane deploy to break. When i change it to "2.0.8" and retry it works.

fyi

**Comment by honkmaster** [comment]
I am not using fastlane myself. We are using naming, such as "2.0-beta8", so it complies with cocoapods. They suggest to use the beta tag as done here. Therefore I can not change anything at the moment.

**Comment by nathanshox** [comment]
We ran into the same issue and resolved it by adding the following into the `before_all` lane.

```
sh("/usr/libexec/PlistBuddy -c 'Set CFBundleShortVersionString 2.0' '../Pods/Target Support Files/SVProgressHUD/Info.plist'")
```

**Comment by honkmaster** [comment]
Good idea and FYI: I currently have no mac (defect). I will submit 2.0 as soon as I got money and time to repair the machine.

**Comment by honkmaster** [comment]
2.0 is released.
