### ISSUE TITLE
不知道是谁的BUG，但真的好蛋疼。

### ISSUE THREAD

**Issue by Z-JaDe** [SVProgressHUD/SVProgressHUD#566]
1、用手势推出栈顶VC后，在viewWillAppear中调用了[SVProgressHUD setDefaultMaskType:SVProgressHUDMaskTypeClear];
    [SVProgressHUD setViewForExtension:self.tableView];
    [SVProgressHUD setDefaultStyle:SVProgressHUDStyleDark];
    [SVProgressHUD showProgress:0 status:@"加载中"];
2、数据下载完成后，调用[SVProgressHUD dismissWithDelay:0.5];
3、但是在[UIView animateWithDuration:duration
                                  delay:delay
                                options:(UIViewAnimationOptions) (UIViewAnimationOptionAllowUserInteraction | UIViewAnimationCurveEaseIn | UIViewAnimationOptionBeginFromCurrentState)
                             animations:^{
                                 animationsBlock();
                             } completion:^(BOOL finished) {
                                 NSLog(@"completionBlock -- %f",delay);
                                 completionBlock();
                             }];里面animationsBlock会执行，
completionBlock不会执行，此时hudView也不会隐藏。

**Comment by Z-JaDe** [comment]
把animationsBlock()注释掉就没事了，问题有点莫名其妙，这样的话就没法动画了

**Comment by Z-JaDe** [comment]
把调用代码写在viewDidAppear中就没事了，看来还是我的问题，IOS动画不能放在viewDidAppear之前，要不然会出问题，不执行completionBlock。

**Comment by honkmaster** [comment]
Sorry, I do not speak chinese. Please repost you issue in Englisch so everybody can understand.

**Comment by Z-JaDe** [comment]
I can't speak English, I have solved it, thank you for your attention!

**Comment by honkmaster** [comment]
If you can not speak English you will have a hard time here on GitHub. I can only offer support in English and German.

**Comment by Z-JaDe** [comment]
I've learned it, thanks.
