### ISSUE TITLE
iOS 9.2 Xcode 7.2.1 Warning

### ISSUE THREAD

**Issue by ClayApps** [SVProgressHUD/SVProgressHUD#567]
1) 
/Users/FlimFlamVir/dev/Ckure/Source/Ckure/<module-includes>:1:1: Umbrella header for module 'SVProgressHUD' does not include header 'SVProgressHUD-Framework.h'

2) /Users/FlimFlamVir/dev/Ckure/Source/Ckure/Ckure/Classes/Thirdparty/SIAlertView/SIAlertView.m:180:1: Conflicting return type in implementation of 'supportedInterfaceOrientations': 'UIInterfaceOrientationMask' (aka 'enum UIInterfaceOrientationMask') vs 'NSUInteger' (aka 'unsigned long')

**Comment by honkmaster** [comment]
1) This looks not related the the HUD as it mentions Umbrella headers? Is this about Carthage? 
2) Can not reproduce.

**Comment by ClayApps** [comment]
Agreed, closing
