### ISSUE TITLE
Add customizations for imageView.size 

### ISSUE THREAD

**Issue by lianweiqin** [SVProgressHUD/SVProgressHUD#568]
I'd like to use 
"+ (void)setSuccessImage:(UIImage*)image;        
- (void)setErrorImage:(UIImage*)image; "
  to replace default success/error image, but It seems the self.imageView's size is  (28, 28), and the property "imageView" is private. 
  How about expose it to a public property or add a method to custom it?

**Comment by shanglina** [comment]
I have the same problem, please content to me if you know

**Comment by shanglina** [comment]
It seems that you have to change the self.imageView.frame or make your own picture 28 *28 or it will be
 shown as black

- (UIImageView*)imageView {
    if(!_imageView) {
        _imageView = [[UIImageView alloc] initWithFrame:CGRectMake(0.0f, 0.0f, 28.0f, 28.0f)];
    }
    if(!_imageView.superview) {
        [self.hudView addSubview:_imageView];
    }
    return _imageView;
}

**Comment by honkmaster** [comment]
It is on purpose that the imageView has a dimension of 28x28 pixels. A further customization would increase the complexity of the component as well as move against our goal to keep the Hud as similar to an iOS component as possible.

**Comment by honkmaster** [comment]
ImageView size can be changed on the current master. Cocoapods release soon.
