### ISSUE TITLE
Progress bar not showing

### ISSUE THREAD

**Issue by ananarola** [SVProgressHUD/SVProgressHUD#573]
Hi..
I am using lastest SVProgressHUD lib which is really nice...i have integrated it in my many of project and its work very nice

but when i switch to swift and used in below way
 SVProgressHUD.show()
 SVProgressHUD.setDefaultMaskType(SVProgressHUDMaskType.Black)

This just visible the gray window (SVProgressHUDMask) to my view and the progess bar either with status or without status it not shown..

What should i need to display to visible the Progress bar

**Comment by hjaurum** [comment]
I have a issue quite similar as yours. SVProgressHUD had been works well, but 'SVProgressHUD.showErrorWithStatus' not shown since I update to '2.0-beta8'.

**Comment by honkmaster** [comment]
Should be fixed.

**Comment by ananarola** [comment]
Thanks @sir.  Hope it should be done soon
