### ISSUE TITLE
Error while uploading build to iTunes Connect 

### ISSUE THREAD

**Issue by itsarjun** [SVProgressHUD/SVProgressHUD#575]
I'm getting the following error while uploading my build to iTunes connect 
"CFBundleShortVersionString must be a period-separated list of most three non-negative integers"

Currently, it is set to 2.0-beta8. I changed it to 2.0. Does this change affect the SVProgressHUD behaviour?

**Comment by lmcd** [comment]
Also had this problem. Can we get a `2.0` release?

**Comment by honkmaster** [comment]
My mac is back from repair, I am on track for 2.0 soon.

**Comment by honkmaster** [comment]
2.0 is released.
