### ISSUE TITLE
SVProgressHUD fails to build with tvOS 9.2 SDK, Xcode 7.3

### ISSUE THREAD

**Issue by yeewensat** [SVProgressHUD/SVProgressHUD#576]
SVProgressHUD fails to build with tvOS 9.2 SDK after updated to Xcode 7.3.
The errors are related to the following not available on tvOS 9.2:
UIKeyboardWillHideNotification,  UIKeyboardDidHideNotification,  UIKeyboardWillShowNotification,  UIKeyboardDidShowNotification

Using pod 'SVProgressHUD', '2.0-beta8'

**Comment by honkmaster** [comment]
Previously these values like `UIKeyboardWillHideNotification` were also available on tvOS, the only thing not available on tvOS was `UIApplicationDidChangeStatusBarOrientationNotification`. Looks like Apple changed that ... Will update to Xcode 7.3 now and then check for myself.

**Comment by SilkyPantsDan** [comment]
We were experiencing the same issue yesterday, and had made these changes locally to remedy the issue. Seems they have removed them in the latest SDK version

FTR this was compiled with Xcode Version 7.3 (7D175)

**Comment by honkmaster** [comment]
Should be fixed.
