### ISSUE TITLE
in XCode 7.3 crashed

### ISSUE THREAD

**Issue by Migo24K** [SVProgressHUD/SVProgressHUD#578]
I upgrade my xcode to 7.3
then my project can't launched..
It crashed in SVProgressHUD.m,352 lines..
NSBundle *bundle = [NSBundle bundleForClass:[SVProgressHUD class]];
//get nil url,then it crashed
NSURL *url = [bundle URLForResource:@"SVProgressHUD" withExtension:@"bundle"];
NSBundle *imageBundle = [NSBundle bundleWithURL:url];

Sorry about my bad English T.T
I need help,thank you!

**Comment by honkmaster** [comment]
Just checked. Works for me in demo and my apps. What is different in your app than in the demo? Did you add the Bundle to `Targets->Build Phases->Copy Bundle Resources`? Do you use Cocoapods? Did you run `pod install`?

**Comment by Migo24K** [comment]
I did't do it,before xcode 7.3,it works well

**Comment by honkmaster** [comment]
Hmm, there must be some weird things in your setup because demo and my apps (overall 5 projects) do work. Please check and reinstall.

**Comment by Migo24K** [comment]
OK,let me try,thanks

**Comment by freemiumdev** [comment]
delete the contents of the folder "dereved data" and rebuild all. :smiley:

**Comment by Migo24K** [comment]
I change a computer,it work's well,i did't change any code,i'm so bad,it cost me 3 days...thank you all~~

**Comment by tspent** [comment]
Hey! just happen to our live version. 6 crashes from one user! Any ideas?

**Comment by honkmaster** [comment]
Did you deploy the Bundle?

**Comment by tspent** [comment]
Of course i have deploy the bundle. Many users use the app without any issue. 
The specific user using iOS 7 and the device is jailbreak!
