### ISSUE TITLE
It's weird to deprecate methods with suffix "withMaskType:"

### ISSUE THREAD

**Issue by huajiahen** [SVProgressHUD/SVProgressHUD#581]
I had use this awesome pod for years in my own project, but the latest 2.0 update introduced a weird change which deprecated all methods with suffix "withMaskType:". I would use clear mask or black mask when app is doing some work that should not be interrupt; when app push to some page which needs download content from network, I would like to use None mask in order to allow user exit this page. In SVProgressHUD 2.0, I have to use 3 lines to change default mask, or I would have tons of Xcode warning of deprecated method.
Please consider to resume these "withMaskType:" methods. Thanks!

**Comment by honkmaster** [comment]
Please read the following discussion: 

https://github.com/SVProgressHUD/SVProgressHUD/pull/384
https://github.com/SVProgressHUD/SVProgressHUD/issues/519

Summary: It is "bad" UX to use the same component with different kind of masks. Therefore we introduced the defaultMask. In addition this makes the component more accessible and iOSesqe. For your example I have on tip: Use UIApplications `setNetworkActivityIndicatorVisible` to show download progress. If you still have questions answer here.

**Comment by huajiahen** [comment]
Well.. I don't think use NetworkActivityIndicator is a good solution for this case. You will never want to show an large empty view with only a tiny top-left network indicator to tell user that you are loading sth from network. They will just think your app is broken.

**Comment by honkmaster** [comment]
I don`t think so, is Apple for example using something like this HUD if the want to show a download progress? No. They use different, more elegant approaches e.g. in Mail.app.
