### ISSUE TITLE
HUD not going away before 5 seconds for short messages too

### ISSUE THREAD

**Issue by kapoorsahil** [SVProgressHUD/SVProgressHUD#582]
using 
SVProgressHUD 2.0
Xcode 7.3
Swift 2.2

**Comment by honkmaster** [comment]
Hi, see #575. This is intended, five seconds is the `minimumDismissTimeInterval ` <=> The time the HUD should be visible as minimum. It was a bug before. If you want shorter times use the customization methods.

**Comment by kapoorsahil** [comment]
Thanks.
