### ISSUE TITLE
setForegroundColor not working anymore

### ISSUE THREAD

**Issue by SvenTiigi** [SVProgressHUD/SVProgressHUD#589]
Hey there

with the last release of the version 2.0.2 it seems that the styling options for `setForegroundColor` and `setBackgroundColor` are not working anymore. It only shows the standard implementation with a white background and black foreground color.

Here is a example of how I call the SVProgressHUD in my code (before the newest release it all worked out fine).

`[SVProgressHUD setForegroundColor:[UIColor orangeColor]];`
`[SVProgressHUD showWithStatus:@"Please wait"];`

**Comment by honkmaster** [comment]
Have you read the hint in `Readme.md`:

*If you want to use custom colors with setForegroundColor and setBackgroundColor: don't forget to set SVProgressHUDStyleCustom via setDefaultStyle:.*

**Comment by SvenTiigi** [comment]
Thank you for your quick reply. This fixed my issue.

Besten dank :+1:

**Comment by honkmaster** [comment]
kein problem!
