### ISSUE TITLE
[SVProgressHUD dismiss] not dismissing the hud sometimes

### ISSUE THREAD

**Issue by PayalUmraliya** [SVProgressHUD/SVProgressHUD#591]
I integared SVProgressHUD in my app.I am using SVProgressHUD when i make request from server.
when from server i receive error at that time i try to dismiss the SVProgressHUD.But it is keep loading and dismiss after request time out.

i am using [SVProgressHUD dismiss] and also tried 
   dispatch_async(dispatch_get_main_queue(), ^{
                    [SVProgressHUD dismiss];
                });
But still facing this issue.

**Comment by honkmaster** [comment]
Are you on the latest version? To help you I need more details, the best would be a demo project.

**Comment by hclviv** [comment]
I tried the latest version 2.0.2 and still facing the same issue. I am using [SVProgressHUD dismiss]; but its not dismiss and keep trying loading

**Comment by honkmaster** [comment]
Hi, again: i need aime kind of demo project or something/ anything else as I can nor reproduce the issue.

**Comment by hclviv** [comment]
Hi @honkmaster 

Here are some pointers to reproduce the issue -

1. call [SVProgressHUD showWithStatus:@"Loading..." ]
2. After this line you can call any web service with AFNetworking Asynchronously 
3. When data received try to dismiss the spinner using [SVProgressHUD dismiss]

**Comment by alampila** [comment]
I too am seeing this behavior when calling dismiss very quickly after a show method. It appears to me that the HUD has not yet been animated on screen by the time dismiss is called.

**Comment by CoderEic** [comment]
@alampila I met the same problem, are you solve that?

**Comment by hclviv** [comment]
try to dismiss SVProgressHUD in main queue --
 dispatch_async(dispatch_get_main_queue(), ^{
        [SVProgressHUD dismiss];
    });

its working fine in my case

**Comment by honkmaster** [comment]
Should be fixed with the latest commit, please check the current master and provide feedback.

**Comment by CoderKid101** [comment]
Could Someone Also Tell How To Lower The Time It Takes For ProgressHUD To Dismiss After Being Launched?

Code:

    @IBAction func logOutPressed(_ sender: AnyObject) {
        
        //TODO: Log out the user and send them back to WelcomeViewController
        do {
            try Auth.auth().signOut()
            SVProgressHUD.showSuccess(withStatus: "Logging Out Sucsessful")
            navigationController?.popToRootViewController(animated: true)
        }
        
        catch {
            print("Error Logging Out : \(error)")
            SVProgressHUD.showError(withStatus: "Logging Out Unsucsessful")
            **SVProgressHUD.dismiss()** Tryed But HUD Duration Is Same Length.
        }
        
    }

**Comment by CoderKid101** [comment]
Could Someone Also Tell How To Lower The Time It Takes For ProgressHUD To Dismiss After Being Launched?

Code:

@IBAction func logOutPressed(_ sender: AnyObject) {
    
    //TODO: Log out the user and send them back to WelcomeViewController
    do {
        try Auth.auth().signOut()
        SVProgressHUD.showSuccess(withStatus: "Logging Out Sucsessful")
        navigationController?.popToRootViewController(animated: true)
    }
    
    catch {
        print("Error Logging Out : \(error)")
        SVProgressHUD.showError(withStatus: "Logging Out Unsucsessful")
        **SVProgressHUD.dismiss()** Tryed But HUD Duration Is Same Length.
    }
    
}

**Comment by krishnasolankiBigbang** [comment]
I am getting Same issue Even i tried :: 
dispatch_async(dispatch_get_main_queue(), ^{
[SVProgressHud Dismiss];
});
