### ISSUE TITLE
SUGGESTION: Tapped Event or button

### ISSUE THREAD

**Issue by ImDestinedMe** [SVProgressHUD/SVProgressHUD#593]
Did you guys ever consider giving the option to supply a button for the progress view? 
For instance: What if someone wanted to cancel an ongoing operation?

**Comment by honkmaster** [comment]
Why not use `NSNotificationCenter` and `SVProgressHUDDidReceiveTouchEventNotification`to dismiss the HUD simply on user interaction?

**Comment by ImDestinedMe** [comment]
@honkmaster I was debating doing that, but a user wouldn't know or assume that thats how to cancel the operation, at least I wouldn't think so?  

I honestly didn't know there was a notification for that 😒

**Comment by honkmaster** [comment]
Sure, he would`t now that he can cancel if there is no "indication" such as a button. However, I do not think adding a button is beneficial, as this will complicate the code. In addition this is a quite rare use case.

**Comment by ImDestinedMe** [comment]
Fair enough, thank you for your replies. I think I'm gonna just use the notification and try to work with that

**Comment by zhuozhuo** [comment]
Hi honkmaster,
    SVProgressHUDDidReceiveTouchEventNotification sometimes did not work,just use showProgress function it is working. I think when show info,success,error cost too long time.It should be dismiss when user tap the view。 What should I do。

**Comment by honkmaster** [comment]
Could you better describe in which cases `SVProgressHUDDidReceiveTouchEventNotification` does not work? I would better **fix** that than **implement additional stuff.**

**Comment by aluco100** [comment]
Hi @honkmaster ,

I have the same issue. I add the notification, but it doesn't trigger it. I don't understand what is wrong. There's my code in swift.

`override func viewDidLoad() {
        super.viewDidLoad()
        
        self.loginButton.addTarget(self, action: #selector(login), for: .touchUpInside)
        self.recoverButton.addTarget(self, action: #selector(recover), for: .touchUpInside)
        NotificationCenter.default.addObserver(self, selector: #selector(hideHUD), name: NSNotification.Name.SVProgressHUDDidReceiveTouchEvent, object: nil)

    }
.....
func hideHUD(){
        SVProgressHUD.dismiss()
    }
`
