### ISSUE TITLE
HUD isn't visible if called dismissWithDelay immediately after the `show`

### ISSUE THREAD

**Issue by sashkasashkin** [SVProgressHUD/SVProgressHUD#594]
Hi! I see that you fixed bug #569 . I updated my pods to 2.0.2.
I want to show HUD and dismiss it in 5 seconds, if dismiss isn't called during that time.
Now screen is blocked in 5 seconds and HUD isn't visible ((

**Comment by sashkasashkin** [comment]
I see that animations block occurs immediatelly in [UIView animateWithDuration: delay: options: animations: completion: ] in the local dismissWithDelay.

**Comment by sashkasashkin** [comment]
I call performSelector to avoid weird behaviour of animateWithDuration 
`[strongSelf` performSelector:@selector(animateDismissing) withObject:nil afterDelay:delay];`
I call [UIView animateWithDuration: delay:options:animations:completion:] in animateDismissing  and it works

**Comment by sgermain06** [comment]
I have the same problem!

**Comment by sgermain06** [comment]
Using Swift, I was able to make this work doing this:

SVProgressHUD.performSelector(#selector(SVProgressHUD.dismiss), withObject: nil, afterDelay: 1, inModes: [NSDefaultRunLoopMode])

Now it works fine.

**Comment by entotsu** [comment]
me too

**Comment by honkmaster** [comment]
Working on a fix. However, PR are always welcome.

**Comment by honkmaster** [comment]
Should be fixed with the latest commit, please check the current master and provide feedback.

**Comment by honkmaster** [comment]
No feedback at all? This is sad.

Questions and issues like this, are the reason people burn out on open source. Don't let others do your work, give good questions, follow issue guidelines, provide a demo project or tell what you have already done to solve the problem. Also give feedback if required! This is a matter of respect for the programmers that make a lot of efforts on writing open source components.

**Comment by sashkasashkin** [comment]
I'm sorry, honkmaster. I'm a new guy on github. We did workaround a half year ago. 
`+ (void)showHUDWithStatus:(NSString*)progressStatus
{
    [self showWithStatus:progressStatus];
    [self dismissHUDWithDelay:SVProgressHUDDefaultDelay];
}

+ (void)hideHUD
{
    [self dismiss];
    [self cancelPerformRequest];
}

+ (void)cancelPerformRequest
{
    [NSObject cancelPreviousPerformRequestsWithTarget:self selector:@selector(hideHUD) object:self];
}

+ (void)dismissHUDWithDelay:(NSTimeInterval)aDelay
{
    [self cancelPerformRequest];
    [self performSelector:@selector(hideHUD) withObject:self afterDelay:aDelay];
}
`
I know, this workaround isn't a good solution. But the problem has gone. 
I just tried your latest version. Unfortunatelly, it isn't working still.

I put
`    [SVProgressHUD show];
    [SVProgressHUD dismissWithDelay:15.0f];
` 
into viewDidAppear to check it.
Best wishes! Thank you for your efforts.
