### ISSUE TITLE
Build command issue

### ISSUE THREAD

**Issue by michaelfrain** [SVProgressHUD/SVProgressHUD#595]
I am getting the following build command failures when installing this dependency through Carthage:

`The following build commands failed:
    Ld /var/root/Library/Developer/Xcode/DerivedData/SVProgressHUD-dhcwvakygysfdkfjpylvmjiiicnw/Build/Intermediates/SVProgressHUD.build/Release-iphoneos/SVProgressHUD-Framework.build/Objects-normal/armv7/SVProgressHUD normal armv7
    Ld /var/root/Library/Developer/Xcode/DerivedData/SVProgressHUD-dhcwvakygysfdkfjpylvmjiiicnw/Build/Intermediates/SVProgressHUD.build/Release-iphoneos/SVProgressHUD-Framework.build/Objects-normal/arm64/SVProgressHUD normal arm64
(2 failures)`

I am attempting to install this dependency for Xcode 7.3 using Carthage 0.15.2.

**Comment by honkmaster** [comment]
Please clean your derived data, then build again.

**Comment by michaelfrain** [comment]
I've already done that. Still getting the build errors.

**Comment by honkmaster** [comment]
Which version of the HUD are you using? The latest master? I have no idea what's causing the problem. Maybe @justin can help.

**Comment by michaelfrain** [comment]
Yep, the latest master. The output above is what is given when I run `carthage update`.

**Comment by justin** [comment]
Can you show me what's in your Cartfile?

**Comment by honkmaster** [comment]
Is this still an active issue?
