### ISSUE TITLE
Cocoapods 1.0 not supports :head anymore

### ISSUE THREAD

**Issue by antons81** [SVProgressHUD/SVProgressHUD#597]
Hi I have tried to update pods with new cocoapods 1.0 beta 6 and they removed :head from its support.
I have updated with new key :git => but it's crashing on

DISPATCH_INLINE DISPATCH_ALWAYS_INLINE DISPATCH_NONNULL_ALL DISPATCH_NOTHROW
void
_dispatch_once(dispatch_once_t *predicate, dispatch_block_t block)
{
	if (DISPATCH_EXPECT(*predicate, ~0l) != ~0l) {
		## this line ----> dispatch_once(predicate, block);
	}
}

It's something with pregress style liek custom etc

version I installed is 2.0.3

> *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[NSBundle initWithURL:]: nil URL argument'
> *** First throw call stack:
> (
> 	0   CoreFoundation                      0x0000000109e31d85 __exceptionPreprocess + 165
> 	1   libobjc.A.dylib                     0x0000000109300deb objc_exception_throw + 48
> 	2   CoreFoundation                      0x0000000109e31cbd +[NSException raise:format:] + 205
> 	3   Foundation                          0x0000000108f37ff7 -[NSBundle initWithURL:] + 87
> 	4   Foundation                          0x0000000108f380a6 +[NSBundle bundleWithURL:] + 45
> 	5   SVProgressHUD                       0x000000010770b1ec -[SVProgressHUD initWithFrame:] + 780
> 	6   SVProgressHUD                       0x0000000107709807 __27+[SVProgressHUD sharedView]_block_invoke + 263
> 	7   libdispatch.dylib                   0x000000010b0ac3eb _dispatch_client_callout + 8
> 	8   libdispatch.dylib                   0x000000010b097d68 dispatch_once_f + 543
> 	9   SVProgressHUD                       0x00000001077096d8 +[SVProgressHUD sharedView] + 136
> 	10  SVProgressHUD                       0x0000000107709974 +[SVProgressHUD setDefaultMaskType:] + 36
> 	11  Leyefe                              0x0000000105db31db _TFC6Leyefe9Functions12showProgressfT_T_ + 75
> 	12  Leyefe                              0x0000000105d7a515

**Comment by hhanesand** [comment]
Try this?

> pod deintegrate
> gem update cocoapods --pre
> pod install

**Comment by antons81** [comment]
Still the same 

P

> od installation complete! There are 12 dependencies from the Podfile and 12
> total pods installed.
> 
> [!] Ignoring obsolete `HEAD` specifier in `SVProgressHUD (HEAD)`
> 
> [!] Ignoring obsolete HEAD specifier in `HEAD based on 2.0.3`
> 
> [!] Ignoring obsolete `HEAD` specifier in `SVProgressHUD (HEAD based on 2.0.3)`

**Comment by honkmaster** [comment]
This is not our issue. The error is on your podfile. Please use

`pod 'SVProgressHUD', :git => 'https://github.com/SVProgressHUD/SVProgressHUD.git'`

as described in our (updated) Readme.md (see #552 and http://blog.cocoapods.org/CocoaPods-1.0/) if you want to use the latest.

**Comment by antons81** [comment]
This is line from my Podfile #  pod 'SVProgressHUD', :git => 'https://github.com/SVProgressHUD/SVProgressHUD.git'

**Comment by petec029** [comment]
I am running into the same issue since updating to cocoa pods 1.0

My pod file has
pod 'SVProgressHUD', :git => 'https://github.com/SVProgressHUD/SVProgressHUD.git'

and after doing a 'pod update' I still get this error message 
Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[NSBundle initWithURL:]: nil URL argument'

Why is this issue closed?  What is the solution?

**Comment by ssnielsen** [comment]
I also think this should be reopened. I'm also running into the issue both with and without the direct git url with Cocoapods 1.0.1

**Comment by antons81** [comment]
Actually I just copy past string from Answer and fro  third time it succeeds

**Comment by ssnielsen** [comment]
Resolved it by removing derived data and resetting simulator (found in #449)
