### ISSUE TITLE
How to use svprogressHUD on image ???

### ISSUE THREAD

**Issue by chinnuios** [SVProgressHUD/SVProgressHUD#603]
@hannesjung  I am working on Chatting.  Though  when I send the image from iphone to server.it's uploading with circular progress bar on image. I need to showing animation like as same Whatsapp upload Image. So I am using SVProgressHUD. How to use it  && where i do write the program. Please tell me.

**Comment by honkmaster** [comment]
This is not working at the moment and also not intended.
