### ISSUE TITLE
all SVProgressHUD use static, why not design it as object

### ISSUE THREAD

**Issue by aozhimin** [SVProgressHUD/SVProgressHUD#604]
in SVProgressHUD, all method is static, all setters is static, such as setDefaultStyle setInfoImage setMinimumDismissTimeInterval. what if I want it be different in two pages, it will be ugly to implement it. why not design hud as a object!

**Comment by honkmaster** [comment]
The HUD is open source so you are welcome to contribute und give new ideas (source-code wise) we can look at.

**Comment by aozhimin** [comment]
got it! thank you
