### ISSUE TITLE
dismissWithDelay -----Bug ----Solution method

### ISSUE THREAD

**Issue by ZTOOTZ** [SVProgressHUD/SVProgressHUD#606]
Hello!  @honkmaster 
If you use SVProgressHUD show a prompt box and want it immediately or disappear after a few seconds, then it is not correct.
   //创建提示框
    [SVProgressHUD show];

//    两秒后消失
    [SVProgressHUD dismissWithDelay:2];

The reason is that the showStatus: in the animation did not perform on the implementation of the dismissWithDelay:        animation.

Solution method ---    Add a delay to the 1073 line of the SVProgressHUD.m.

```
            [NSThread sleepForTimeInterval:strongSelf.fadeInAnimationDuration];
                                                                                                                            ---------To the author
```

@ #605 
---------------A solution to the user

1.Need to show when the animation

```
dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(@"Is greater than or equal to the duration of the animation display" * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{

    //立即消失
    //[SVProgressHUD dismiss];

    //    两秒后消失
    [SVProgressHUD dismissWithDelay:2];
});
```

2.Animations that do not need to be displayed
//显示时动画持续时间   Before dismiss
    [SVProgressHUD setFadeInAnimationDuration:0];

------------------------------------ Split line --------------------------
- (void)showWithStatus:(NSString*)status {
  [self sharedView];   -------I would like to ask this is not redundant .. I saw a few
  
  [self showProgress:SVProgressHUDUndefinedProgress status:status];
  }
  
  I am looking forward to your reply.
  
  ```
                                                          ------------Thank the authors for providing such a good framework
  ```

**Comment by ZTOOTZ** [comment]
Stick me a link to Jane.
中文版  http://www.jianshu.com/writer#/notebooks/2836215/notes/2618617/writing

**Comment by honkmaster** [comment]
Acknowledged this bug. Working on fix.

**Comment by honkmaster** [comment]
Should be fixed with the latest commit, please check the current master and provide feedback.

**Comment by honkmaster** [comment]
No feedback at all? This is sad.

Questions and issues like this, are the reason people burn out on open source. Don't let others do your work, give good questions, follow issue guidelines, provide a demo project or tell what you have already done to solve the problem. Also give feedback if required! This is a matter of respect for the programmers that make a lot of efforts on writing open source components.

**Comment by warpling** [comment]
Hi @honkmaster. I tried the following with the latest commit and can confirm that no HUD is shown:
````
[SVProgressHUD showWithStatus:@"foo"];
[SVProgressHUD dismissWithDelay:5];
````

(Thank you so much for this wonderful library—has saved me quite a bit of time and looks great)
