### ISSUE TITLE
Continuesly crash on dismissWithDuration function

### ISSUE THREAD

**Issue by ananarola** [SVProgressHUD/SVProgressHUD#608]
Hi i am using SVProgressHUD and it is continuously crash on below lines
 strongSelf.hudView.transform = CGAffineTransformScale(self.hudView.transform, 0.8f, 0.8f);
                
                if(strongSelf.isClear){ // handle iOS 7 UIToolbar not answer well to hierarchy opacity change
                   // strongSelf.hudView.alpha = 0.0f;
                } else{
                    strongSelf.alpha = 0.0f;
                }
            }

also crashes at below

  if (duration > 0) {
            [UIView animateWithDuration:duration
                                  delay:delay
                                options:(UIViewAnimationOptions) (UIViewAnimationOptionAllowUserInteraction | UIViewAnimationCurveEaseIn | UIViewAnimationOptionBeginFromCurrentState)
                             animations:^{
                                 animationsBlock();
                             } completion:^(BOOL finished) {
                                 completionBlock();
                             }];
        } else {
            animationsBlock();
            completionBlock();
        }

**Comment by honkmaster** [comment]
Please provide a demo project where the crash appears. Can not reproduce.

**Comment by pkg2016** [comment]
I am also facing same problem crashed at below line

 if (strongSelf.fadeOutAnimationDuration > 0) {
                // Animate appearance
                [UIView animateWithDuration:strongSelf.fadeOutAnimationDuration
                                      delay:delay
                                    options:(UIViewAnimationOptions) (UIViewAnimationOptionAllowUserInteraction | UIViewAnimationCurveEaseIn | UIViewAnimationOptionBeginFromCurrentState)
                                 animations:^{
                                     animationsBlock();
                                 } completion:^(BOOL finished) {
                                     completionBlock();     //crashed at this line
                                 }];
