### ISSUE TITLE
PasscodeLock integration

### ISSUE THREAD

**Issue by sinanulkuatam** [SVProgressHUD/SVProgressHUD#609]
I believe there is a bug where using this library alongside Passcode Lock creates an issue where it is hidden behind the ViewController.  Any thoughts on what the issue could be? Thanks!

https://github.com/yankodimitrov/SwiftPasscodeLock

**Comment by sxua** [comment]
PasscodeLock presents itself in a separate window on top of everything. I have a similar problem with separate windows (including PasscodeLock) and progress hud. Sometimes it doesn't show up.

**Comment by sinanulkuatam** [comment]
The only loader I've found that doesn't seem to have this issue is JGProgressHUD.  I do like SVProgress's design better though.  Good to know I'm not the only one with this problem!

**Comment by honkmaster** [comment]
i can not offer support for issues with external libraries.

**Comment by sinanulkuatam** [comment]
No worries, looks like a workaround was discussed here for anyone with this issue in teh future: https://github.com/yankodimitrov/SwiftPasscodeLock/issues/33
