### ISSUE TITLE
error when I use it with CocoaPods.

### ISSUE THREAD

**Issue by ferrior30** [SVProgressHUD/SVProgressHUD#621]
when used in my project with CocoaPods,error occur .But if I drag it direct into my project, there is no error.

The error as below:

*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[NSBundle initWithURL:]: nil URL argument'

(
	0   CoreFoundation                      0x000000010c138d85 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x000000010b89fdeb objc_exception_throw + 48
	2   CoreFoundation                      0x000000010c138cbd +[NSException raise:format:] + 205
	3   Foundation                          0x000000010b4d6ff7 -[NSBundle initWithURL:] + 87
	4   Foundation                          0x000000010b4d70a6 +[NSBundle bundleWithURL:] + 45
	5   SVProgressHUD                       0x000000010b2f21ec -[SVProgressHUD initWithFrame:] + 780
	6   SVProgressHUD                       0x000000010b2f0807 __27+[SVProgressHUD sharedView]_block_invoke + 263
	7   libdispatch.dylib                   0x000000010efb73eb _dispatch_client_callout + 8
	8   libdispatch.dylib                   0x000000010efa2d68 dispatch_once_f + 543
	9   SVProgressHUD                       0x000000010b2f06d8 +[SVProgressHUD sharedView] + 136
	10  SVProgressHUD                       0x000000010b2f1247 +[SVProgressHUD showWithStatus:] + 55
	11  CWBSBDJ                             0x000000010b08eae5 -[CWClearCacheCell clearCache] + 117
	12  UIKit                               0x000000010d2ebb28 _UIGestureRecognizerSendTargetActions + 153
	13  UIKit                               0x000000010d2e819a _UIGestureRecognizerSendActions + 162
	14  UIKit                               0x000000010d2e6197 -[UIGestureRecognizer _updateGestureWithEvent:buttonEvent:] + 843
	15  UIKit                               0x000000010d2ee655 ___UIGestureRecognizerUpdate_block_invoke898 + 79
	16  UIKit                               0x000000010d2ee4f3 _UIGestureRecognizerRemoveObjectsFromArrayAndApplyBlocks + 342
	17  UIKit                               0x000000010d2dbe75 _UIGestureRecognizerUpdate + 2634
	18  UIKit                               0x000000010ce6848e -[UIWindow _sendGesturesForEvent:] + 1137
	19  UIKit                               0x000000010ce696c4 -[UIWindow sendEvent:] + 849
	20  UIKit                               0x000000010ce14dc6 -[UIApplication sendEvent:] + 263
	21  UIKit                               0x000000010cdee553 _UIApplicationHandleEventQueue + 6660
	22  CoreFoundation                      0x000000010c05e301 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	23  CoreFoundation                      0x000000010c05422c __CFRunLoopDoSources0 + 556
	24  CoreFoundation                      0x000000010c0536e3 __CFRunLoopRun + 867
	25  CoreFoundation                      0x000000010c0530f8 CFRunLoopRunSpecific + 488
	26  GraphicsServices                    0x0000000110ef3ad2 GSEventRunModal + 161
	27  UIKit                               0x000000010cdf3f09 UIApplicationMain + 171
	28  CWBSBDJ                             0x000000010b094c0f main + 111
	29  libdyld.dylib                       0x000000010efeb92d start + 1
	30  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
 
My preject have some other third-framework : 
pod 'AFNetworking'
pod 'MJExtension'
pod 'SDWebImage'
pod 'MJRefresh'
pod 'DACircularProgress'
pod 'FMDB', '~> 2.6.2'
-------
 Please help me!

**Comment by petec029** [comment]
I am running into the same issue. What was the solution?

**Comment by ssnielsen** [comment]
I'd like to hear a solution as well.

**Comment by ssnielsen** [comment]
Resolved it by removing derived data and resetting simulator (found in #449)
