### ISSUE TITLE
popActivity not working as expected

### ISSUE THREAD

**Issue by juanuribeo13** [SVProgressHUD/SVProgressHUD#623]
After running the following code the HUD is not showing.

``` swift
SVProgressHUD.show()
SVProgressHUD.show()
SVProgressHUD.popActivity()
```

**Comment by honkmaster** [comment]
`popActivity` is not working anymore as you can not stack multiple HUDs since a lot time ago. Will close for now, maybe some time I will bring back stacking.

**Comment by sprynmr** [comment]
FYI, found `popActivity` fairly useful.

**Comment by jasonm23** [comment]
FYI readers: commit where popActivity was removed. 44ab58995f2b90f73fac966b61fff792a45ad0ec
