### ISSUE TITLE
SVProgressHUD  Does not support cocospods 1.0?

### ISSUE THREAD

**Issue by wxpasta** [SVProgressHUD/SVProgressHUD#629]
SVProgressHUD  Does not support cocospods 1.0?

**Comment by ecoopnet** [comment]
I found same issue here 
https://github.com/SVProgressHUD/SVProgressHUD/issues/597

**Comment by ecoopnet** [comment]
I resolved cocoapods 1.0 problem by removing derrived data then building again.
