### ISSUE TITLE
SVProgressHUD crash 

### ISSUE THREAD

**Issue by jfk056** [SVProgressHUD/SVProgressHUD#631]
`[AppDelegate window]: unrecognized selector sent to instance 0x7fae1170f3d0 2016-06-20 16:20:02.331 
App[36148:4829956] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[AppDelegate window]: unrecognized selector sent to instance 0x7fae1170f3d0'
*** First throw call stack:
(
	0   CoreFoundation                      0x00000001099c2d85 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x0000000109436deb objc_exception_throw + 48
	2   CoreFoundation                      0x00000001099cbd3d -[NSObject(NSObject) doesNotRecognizeSelector:] + 205
	3   CoreFoundation                      0x0000000109911b17 ___forwarding___ + 487
	4   CoreFoundation                      0x00000001099118a8 _CF_forwarding_prep_0 + 120
	5   App                           0x0000000105b9857e __27+[SVProgressHUD sharedView]_block_invoke + 126
	6   libdispatch.dylib                   0x000000010a5b63eb _dispatch_client_callout + 8
	7   libdispatch.dylib                   0x000000010a5a1d68 dispatch_once_f + 543
	8   App                           0x0000000105b984d8 +[SVProgressHUD sharedView] + 136
	9   App                           0x0000000105b98f37 +[SVProgressHUD showWithStatus:] + 55
	10  App                           0x00000001059f9d6d -[ApplicatoinInfoView copyUgdid] + 253
	11  UIKit                               0x0000000107fdab28 _UIGestureRecognizerSendTargetActions + 153
	12  UIKit                               0x0000000107fd719a _UIGestureRecognizerSendActions + 162
	13  UIKit                               0x0000000107fd5197 -[UIGestureRecognizer _updateGestureWithEvent:buttonEvent:] + 843
	14  UIKit                               0x0000000107fdd655 ___UIGestureRecognizerUpdate_block_invoke898 + 79
	15  UIKit                               0x0000000107fdd4f3 _UIGestureRecognizerRemoveObjectsFromArrayAndApplyBlocks + 342
	16  UIKit                               0x0000000107fcae75 _UIGestureRecognizerUpdate + 2634
	17  UIKit                               0x0000000107b5748e -[UIWindow _sendGesturesForEvent:] + 1137
	18  UIKit                               0x0000000107b586c4 -[UIWindow sendEvent:] + 849
	19  UIKit                               0x0000000107b03dc6 -[UIApplication sendEvent:] + 263
	20  UIKit                               0x0000000107add553 _UIApplicationHandleEventQueue + 6660
	21  CoreFoundation                      0x00000001098e8301 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	22  CoreFoundation                      0x00000001098de22c __CFRunLoopDoSources0 + 556
	23  CoreFoundation                      0x00000001098dd6e3 __CFRunLoopRun + 867
	24  CoreFoundation                      0x00000001098dd0f8 CFRunLoopRunSpecific + 488
	25  GraphicsServices                    0x000000010bf61ad2 GSEventRunModal + 161
	26  UIKit                               0x0000000107ae2f09 UIApplicationMain + 171
	27  App                           0x0000000105a0377f main + 111
	28  libdyld.dylib                       0x000000010a5ea92d start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException`

I'm running on cocoapods 1.0.1 can you help with this issue??

**Comment by abinop** [comment]
Try to clean build folder first

**Comment by honkmaster** [comment]
Resolve this by removing derived data and resetting simulator.

P.S.: Next time reformat the crashlog so it is readable.

**Comment by mehulparmar4ever** [comment]
@jfk056 . It will work for you.

    var window: UIWindow?

Add this line in AppDelegate

**Comment by iampushpinder** [comment]
Hi @mehulparmar4ever 
Your comment helped run it. However, the frame of SVProgressHUD/IHProgressHUD is the top left corner of the screen.
What could be the reason?
What could be the solution, other than manually setting up the frame?

**Comment by mehulparmar4ever** [comment]
Hi @iampushpinder , 
**#Try 1:**
_Go to SceneDelegate.swift file and open below method & add one line of code to update window of scene. So, Your problem will resolved._

```

    var window: UIWindow?
func scene(_ scene: UIScene, willConnectTo session: UISceneSession, options connectionOptions: UIScene.ConnectionOptions) {
        // Use this method to optionally configure and attach the UIWindow `window` to the provided UIWindowScene `scene`.
        // If using a storyboard, the `window` property will automatically be initialized and attached to the scene.
        // This delegate does not imply the connecting scene or session are new (see `application:configurationForConnectingSceneSession` instead).
        guard let _ = (scene as? UIWindowScene) else { return }
        (UIApplication.shared.delegate as! AppDelegate).window = window
    }
```

**#TRY 2**
_Use this type of code in your app-delegate. It means you have to set proper navigation_

```

_In AppDelegate.swift file,_ 
    var window: UIWindow?
func navigateToTabBar() {
        let tabController = Constants_Feez.mainStoryboard.instantiateViewController(withIdentifier: "tabController")
        self.window?.rootViewController = tabController
        
        // A mask of options indicating how you want to perform the animations.
        let options: UIView.AnimationOptions = .transitionCrossDissolve

        // The duration of the transition animation, measured in seconds.
        let duration: TimeInterval = 0.3

        // Creates a transition animation.
        // Though `animations` is optional, the documentation tells us that it must not be nil. ¯\_(ツ)_/¯
        guard let window = self.window else {
            return
        }
        
        UIView.transition(with: window, duration: duration, options: options, animations: {}, completion:
        { completed in
            // maybe do something on completion here
        })
    }
    
    func navigateToSignUp() {
        let tabController = Constants_Feez.mainStoryboard.instantiateViewController(withIdentifier: "signUpProcess")
        self.window?.rootViewController = tabController
        
        // A mask of options indicating how you want to perform the animations.
        let options: UIView.AnimationOptions = .transitionCrossDissolve

        // The duration of the transition animation, measured in seconds.
        let duration: TimeInterval = 0.3

        // Creates a transition animation.
        // Though `animations` is optional, the documentation tells us that it must not be nil. ¯\_(ツ)_/¯
        guard let window = self.window else {
            return
        }
        
        UIView.transition(with: window, duration: duration, options: options, animations: {}, completion:
        { completed in
            // maybe do something on completion here
        })
    }
```

**Comment by sagarkhakhar** [comment]
> Hi @iampushpinder ,
> **#Try 1:**
> _Go to SceneDelegate.swift file and open below method & add one line of code to update window of scene. So, Your problem will resolved._
> 
> ```
> 
>     var window: UIWindow?
> func scene(_ scene: UIScene, willConnectTo session: UISceneSession, options connectionOptions: UIScene.ConnectionOptions) {
>         // Use this method to optionally configure and attach the UIWindow `window` to the provided UIWindowScene `scene`.
>         // If using a storyboard, the `window` property will automatically be initialized and attached to the scene.
>         // This delegate does not imply the connecting scene or session are new (see `application:configurationForConnectingSceneSession` instead).
>         guard let _ = (scene as? UIWindowScene) else { return }
>         (UIApplication.shared.delegate as! AppDelegate).window = window
>     }
> ```
> 
> **#TRY 2**
> _Use this type of code in your app-delegate. It means you have to set proper navigation_
> 
> ```
> 
> _In AppDelegate.swift file,_ 
>     var window: UIWindow?
> func navigateToTabBar() {
>         let tabController = Constants_Feez.mainStoryboard.instantiateViewController(withIdentifier: "tabController")
>         self.window?.rootViewController = tabController
>         
>         // A mask of options indicating how you want to perform the animations.
>         let options: UIView.AnimationOptions = .transitionCrossDissolve
> 
>         // The duration of the transition animation, measured in seconds.
>         let duration: TimeInterval = 0.3
> 
>         // Creates a transition animation.
>         // Though `animations` is optional, the documentation tells us that it must not be nil. ¯\_(ツ)_/¯
>         guard let window = self.window else {
>             return
>         }
>         
>         UIView.transition(with: window, duration: duration, options: options, animations: {}, completion:
>         { completed in
>             // maybe do something on completion here
>         })
>     }
>     
>     func navigateToSignUp() {
>         let tabController = Constants_Feez.mainStoryboard.instantiateViewController(withIdentifier: "signUpProcess")
>         self.window?.rootViewController = tabController
>         
>         // A mask of options indicating how you want to perform the animations.
>         let options: UIView.AnimationOptions = .transitionCrossDissolve
> 
>         // The duration of the transition animation, measured in seconds.
>         let duration: TimeInterval = 0.3
> 
>         // Creates a transition animation.
>         // Though `animations` is optional, the documentation tells us that it must not be nil. ¯\_(ツ)_/¯
>         guard let window = self.window else {
>             return
>         }
>         
>         UIView.transition(with: window, duration: duration, options: options, animations: {}, completion:
>         { completed in
>             // maybe do something on completion here
>         })
>     }
> ```

@mehulparmar4ever thanks bro u saved me. great job.

**Comment by JaisinghSisodia** [comment]
let appDelegate = UIApplication.shared.delegate as! AppDelegate
                     appDelegate.window = self.window this would work if  the frame of SVProgressHUD/IHProgressHUD is the top left corner of the screen.

**Comment by DevBahl** [comment]
> Hi @iampushpinder ,
> **#Try 1:**
> _Go to SceneDelegate.swift file and open below method & add one line of code to update window of scene. So, Your problem will resolved._
> 
> ```
> 
>     var window: UIWindow?
> func scene(_ scene: UIScene, willConnectTo session: UISceneSession, options connectionOptions: UIScene.ConnectionOptions) {
>         // Use this method to optionally configure and attach the UIWindow `window` to the provided UIWindowScene `scene`.
>         // If using a storyboard, the `window` property will automatically be initialized and attached to the scene.
>         // This delegate does not imply the connecting scene or session are new (see `application:configurationForConnectingSceneSession` instead).
>         guard let _ = (scene as? UIWindowScene) else { return }
>         (UIApplication.shared.delegate as! AppDelegate).window = window
>     }
> ```
> 
> **#TRY 2**
> _Use this type of code in your app-delegate. It means you have to set proper navigation_
> 
> ```
> 
> _In AppDelegate.swift file,_ 
>     var window: UIWindow?
> func navigateToTabBar() {
>         let tabController = Constants_Feez.mainStoryboard.instantiateViewController(withIdentifier: "tabController")
>         self.window?.rootViewController = tabController
>         
>         // A mask of options indicating how you want to perform the animations.
>         let options: UIView.AnimationOptions = .transitionCrossDissolve
> 
>         // The duration of the transition animation, measured in seconds.
>         let duration: TimeInterval = 0.3
> 
>         // Creates a transition animation.
>         // Though `animations` is optional, the documentation tells us that it must not be nil. ¯\_(ツ)_/¯
>         guard let window = self.window else {
>             return
>         }
>         
>         UIView.transition(with: window, duration: duration, options: options, animations: {}, completion:
>         { completed in
>             // maybe do something on completion here
>         })
>     }
>     
>     func navigateToSignUp() {
>         let tabController = Constants_Feez.mainStoryboard.instantiateViewController(withIdentifier: "signUpProcess")
>         self.window?.rootViewController = tabController
>         
>         // A mask of options indicating how you want to perform the animations.
>         let options: UIView.AnimationOptions = .transitionCrossDissolve
> 
>         // The duration of the transition animation, measured in seconds.
>         let duration: TimeInterval = 0.3
> 
>         // Creates a transition animation.
>         // Though `animations` is optional, the documentation tells us that it must not be nil. ¯\_(ツ)_/¯
>         guard let window = self.window else {
>             return
>         }
>         
>         UIView.transition(with: window, duration: duration, options: options, animations: {}, completion:
>         { completed in
>             // maybe do something on completion here
>         })
>     }
> ```

Thanks! Saved a lot of time for me.
