### ISSUE TITLE
can't get the url from bundle then crash

### ISSUE THREAD

**Issue by Mocilas** [SVProgressHUD/SVProgressHUD#633]
When the project get the url from "SVProgressHUD.bundle", the url tends to be nil ,which lead to the project's crash.
![image](http://7xp8qf.com1.z0.glb.clouddn.com/problem-QQ20160626-0.png)
Can you help me with the problem?
Thank you very much!

**Comment by ondrejhanslik** [comment]
I had this problem after upgrading cocopods to 1.0 and reinstalling pods. I have deleted derived data and did a full clean and I still had the issue. What helped me was to manually delete the Build folder. I believe there is some issue with links not being updated properly.

**Comment by honkmaster** [comment]
Resolve this by removing derived data and resetting simulator.
