### ISSUE TITLE
Ring not centered in HUD

### ISSUE THREAD

**Issue by rohinb** [SVProgressHUD/SVProgressHUD#635]
I'm not sure if I'm just making some silly mistake, but I can't seem to figure out how to better center the ring in the HUD. I know how to center the HUD in my iPad screen, but there doesn't seem to be a setting for centering the ring. The ring appears at the top of the HUD even without any status text. This is my setup code and a screenshot of the HUD. 
Thanks in advance for any help!

`SVProgressHUD.setMinimumSize(CGSize.init(width: 243.0, height: 243.0))
        SVProgressHUD.setDefaultStyle(SVProgressHUDStyle.Custom)
        SVProgressHUD.setBackgroundLayerColor(UIColor.lightGrayColor().colorWithAlphaComponent(0.3))
        SVProgressHUD.setBackgroundColor(UIColor.whiteColor())
        SVProgressHUD.setRingRadius(67.5)
        SVProgressHUD.setRingNoTextRadius(67.5)
        SVProgressHUD.setForegroundColor(Constants.UIColorFromRGB(0x43D4A6))
        SVProgressHUD.setFadeInAnimationDuration(0.5)
        SVProgressHUD.setCornerRadius(30)
        SVProgressHUD.setDefaultMaskType(SVProgressHUDMaskType.Gradient)`

![simulator screen shot jun 28 2016 1 17 05 pm](https://cloud.githubusercontent.com/assets/6454427/16430867/a0b637d8-3d32-11e6-9dda-9441d38b85df.png)

**Comment by rohinb** [comment]
The problem seems to be with the size I am setting the HUD to be. Does SVProgressHUD not work with HUDs as big as mine, 243x243?

**Comment by peymankh** [comment]
Same issue here.

**Comment by honkmaster** [comment]
Hey guys, this is a bug, sure. However, at the moment my time is very limited. If could submit a fix I would happily merge it.
