### ISSUE TITLE
Swift 3

### ISSUE THREAD

**Issue by peyotll** [SVProgressHUD/SVProgressHUD#636]
Do you plan to create a swift3 branch soon?

**Comment by honkmaster** [comment]
No swift intended at the moment.

**Comment by pavankataria** [comment]
Just out of curiosity, any reason why @honkmaster? 
Is there a possible limitation that you're thinking of? Would love to know more. Cheers. Currently I'm using SVProgressHUD just fine in my swift project so I'm fine either way. Genuinely just curious.

**Comment by honkmaster** [comment]
I use Swift in some of my own project, thus I have no aversion against it. `SVProgressHUD` works totally fine with Swift and a bridging header. In addition, rework in Swift is (some) work, which I at the moment can not afford. Furthermore, we are here within an open source community. You are always allowed to go ahead and submit a pull request!

**Comment by pavankataria** [comment]
Ah, so no foreseeable limitation on your end in porting this over to Swift 3. 
Thank you.
