### ISSUE TITLE
How can I show animationView in the bottom

### ISSUE THREAD

**Issue by cnzlh** [SVProgressHUD/SVProgressHUD#637]
Thank you for such a great control!  but how can I show animationView in the bottom,and message in the center。

![image](https://cloud.githubusercontent.com/assets/5771860/16510089/b9583788-3f75-11e6-9ec4-b6f2e826e976.png)
![image](https://cloud.githubusercontent.com/assets/5771860/16510100/c7419574-3f75-11e6-94a2-fe89f6700dc4.png)

**Comment by honkmaster** [comment]
Not possible unless you modify the source code yourself.
