### ISSUE TITLE
why deprecated use + (void)showWithStatus:(NSString*)status maskType:(SVProgressHUDMaskType)maskType method?

### ISSUE THREAD

**Issue by ldhios** [SVProgressHUD/SVProgressHUD#638]
If i  use setDefaultMaskType don't allow user type. it mean at next use SVProgressHUD , must again setDefaultMaskType SVProgressHUDMaskTypeNone.  Can you understand my say? Because, my English is not good!

**Comment by honkmaster** [comment]
This has been explained in details in many other Issues and Pull Request. Use the search.
