### ISSUE TITLE
Show and dismiss actions not synchronous/ordered?

### ISSUE THREAD

**Issue by olejnjak** [SVProgressHUD/SVProgressHUD#645]
Hello,

I have this problem and I'd like to ask if this behavior is intended. Seems like if I call `SVProgressHUD.show()` immediately after `SVProgressHUD.dismiss()` the hud never appears.

My test project contains only single controller, whose `viewDidLoad` contains this code:
```
override func viewDidLoad() {
    super.viewDidLoad()

    SVProgressHUD.dismiss()
    SVProgressHUD.show()
}
```

I would expect this code to show the hud but the behavior is that it isn't shown. Is this known issue or intended behavior?

Thanks for the answer.

**Comment by honkmaster** [comment]
Working on a fix. However, PR are always welcome.

**Comment by honkmaster** [comment]
Should be fixed with the latest commit, please check the current master and provide feedback.

**Comment by olejnjak** [comment]
Ok, will report the result tomorrow :)

**Comment by honkmaster** [comment]
Hmmm ...??

**Comment by olejnjak** [comment]
Sorry i forgot about that and I haven't been at my computer, will report asap.

Odesláno z iPhonu

4. 8. 2016 v 22:00, Tobias Tiemerding <notifications@github.com>:

**Comment by olejnjak** [comment]
Looks OK.
