### ISSUE TITLE
SVProgressHUD dismiss   sleep(2.)  Will collapse

### ISSUE THREAD

**Issue by RabbitDream** [SVProgressHUD/SVProgressHUD#649]
[SVProgressHUD showErrorWithStatus:@"网络加载失败"];
dispatch_async(dispatch_get_global_queue(QOS_CLASS_USER_INITIATED, 0), ^{ 
sleep(2.);
 dispatch_async(dispatch_get_main_queue(), ^{ 
[SVProgressHUD dismiss];
 }); 
});
If I write, can cause a deadlock, But with (dispatch after ) there is no problem

**Comment by honkmaster** [comment]
Working on a fix. However, PR are always welcome.

**Comment by honkmaster** [comment]
Please check the latest master and provide feedback.

**Comment by honkmaster** [comment]
No feedback at all? This is sad.

Questions and issues like this, are the reason people burn out on open source. Don't let others do your work, give good questions, follow issue guidelines, provide a demo project or tell what you have already done to solve the problem. Also give feedback if required! This is a matter of respect for the programmers that make a lot of efforts on writing open source components.
