### ISSUE TITLE
SVProgressHUDMaskTypeBlack Interface changes

### ISSUE THREAD

**Issue by RabbitBell** [SVProgressHUD/SVProgressHUD#650]
hi:
After the update version 2.1, SVProgressHUDMaskTypeBlack changed state
How does the modification?
thanks

**Comment by honkmaster** [comment]
Could you clarify more in better English? I do not understand the problem.

**Comment by honkmaster** [comment]
FYI: Questions like this, are the reason people burn out on open source. Don't let others do your work, give good questions (including proper english), follow issue guidelines, provide a demo project or tell what you have already done to solve the problem.

Issue is closed for now until the things mentioned are respected.
