### ISSUE TITLE
NSLayoutConstraints Warning in swift 2.0 / ios9.3

### ISSUE THREAD

**Issue by ramyasrikontham** [SVProgressHUD/SVProgressHUD#652]
Hi,

I am using SVProgessHUD in my app which is building in swift2.0
I created a bridge between Swift and obj-C and using this. I found many warning.

Can  you please update the code based on the NSLayoutConstraints.

And please suggest me how to do that?
Thanks
Ramya

**Comment by honkmaster** [comment]
Our code does not use NSLayoutConstraints at all. What and where do you see your errors. And what are these errors in detail? We do not officially support the swift / objc bridge.

**Comment by honkmaster** [comment]
FYI: Questions like this, are the reason people burn out on open source. Don't let others do your work, give good questions, follow issue guidelines, provide a demo project or tell what you have already done to solve the problem. 

Will close this issue for now until a proper description is given including a demo project at least.
