### ISSUE TITLE
iphone 6 系统8.4闪退

### ISSUE THREAD

**Issue by RichardZhao1986** [SVProgressHUD/SVProgressHUD#653]
<img width="911" alt="2016-08-04 17 17 45" src="https://cloud.githubusercontent.com/assets/13765587/17396781/83fe3cc4-5a67-11e6-823b-e310f1cb1c27.png">

**Comment by honkmaster** [comment]
Again, as very often mentioned and I am a little tired. This is a project using english as main language => please give your error description in english and read the guidelines how to write an usefull bug request: https://github.com/necolas/issue-guidelines/blob/master/CONTRIBUTING.md#bugs
