### ISSUE TITLE
Hi)

### ISSUE THREAD

**Issue by SergeyOleynich** [SVProgressHUD/SVProgressHUD#654]
Please can you provide some small tutorial project how to use view for extension?

**Comment by honkmaster** [comment]
SV_APP_EXTENSIONS is a preprocessor macro. Add all the files to your extension, set SV_APP_EXTENSIONS to 1 (#define SV_APP_EXTENSIONS 1) and before calling show use setViewForExtension with self.view.

**Comment by SergeyOleynich** [comment]
Please could you tell me if I can use custom background blur view when present you controller. I mean when I make:
+ show
?

**Comment by honkmaster** [comment]
Sorry, but I do not understand the sentence and the structure. What do you want to do? What is the initial situation, what is the achieved result, what hurdles do you face? What is unclear.

**Comment by honkmaster** [comment]
FYI: Questions like this, are the reason people burn out on open source. Don't let others do your work, give good questions, follow issue guidelines, provide a demo project or tell what you have already done to solve the problem.

**Comment by SergeyOleynich** [comment]
ok i will try

**Comment by ooii** [comment]
Hi,

I asked the question [on stackoverflow](https://stackoverflow.com/questions/44758062/use-of-svprogresshud-in-share-extension) but no good answer. 
I'm using SVProgressHUD in my app and is working as expected. The problem occurs in the app extension, where nothing shows up, not even an error.

Here is the code I'm using, if someone could tell me what I'm doing wrong, I'll be very grateful.

Thanks.

```
class ShareViewController: UIViewController {
        ...
        Alamofire.upload(multipartFormData: { multipartFormData in
            multipartFormData.append(jpgImageData!, withName: "file",fileName: fname, mimeType: "image/jpg")
            for (key, value) in parameters {
                multipartFormData.append(value.data(using: String.Encoding.utf8)!, withName: key)
            }
        },
                         to:url!)
        { (result) in
            switch result {
            case .success(let upload, _, _):

                upload.uploadProgress(closure: { (progress) in
                    print("Upload Progress: \(progress.fractionCompleted)")
                    DispatchQueue.main.async(execute: {
                        SVProgressHUD.setViewForExtension(self.view)
                        SVProgressHUD.showProgress(Float(progress.fractionCompleted))
                    })
                })
                upload.responseJSON { response in
                if response.response?.statusCode == 200{
                    if let result = response.result.value {
                        DispatchQueue.main.async(execute: {

                            let pre = NSLocale.preferredLanguages[0]
                            var message = "Message"
                            SVProgressHUD.showSuccess(withStatus: message)
                            SVProgressHUD.dismiss(withDelay: 2)
                            self.extensionContext?.completeRequest(returningItems: nil, completionHandler: nil)
         })      

}
```
