### ISSUE TITLE
I have a problem that in the SVProgressHUD

### ISSUE THREAD

**Issue by RiversMaJianCheng** [SVProgressHUD/SVProgressHUD#658]
`return MAX((float)string.length * 0.06 + 0.5, [self sharedView].minimumDismissTimeInterval);
`

If i login successful means that i must wait for at least 5s,it too long!
it should like follows:
`return MIN((float)string.length * 0.06 + 0.5, [self sharedView].minimumDismissTimeInterval);`
Am i right?

**Comment by algrid** [comment]
Having MAX in this expression is absolutely ok. If you want shorter time - just change minimumDismissTimeInterval property.

**Comment by honkmaster** [comment]
@algrid is correct.
