### ISSUE TITLE
Problem with the library of SVProgressHUD

### ISSUE THREAD

**Issue by frl21** [SVProgressHUD/SVProgressHUD#659]
Hi, I’m trying to install SVProgressHUD framework on my Xcode project. I followed step by step the instruction but we I run the app in the simulator Xcode console promp out this error message:

dyld: Library not loaded: @rpath/SVProgressHUD.framework/SVProgressHUD
  Referenced from: /Users/francescolimoni/Library/Developer/CoreSimulator/Devices/4B627E53-C47E-4CA8-B86C-9C4354D18104/data/Containers/Bundle/Application/DA6935C8-890C-41E4-8F72-8F0C3E4B1BDD/hudProgress.app/hudProgress
  Reason: image not found
(lldb) 

what does it mean?  and what i have to do to solve it?

**Comment by honkmaster** [comment]
Which instruction: Cocoapods? Carthage? Manual?

**Comment by honkmaster** [comment]
No feedback at all? This is sad.

Questions and issues like this, are the reason people burn out on open source. Don't let others do your work, give good questions, follow issue guidelines, provide a demo project or tell what you have already done to solve the problem. Also give feedback if required! Why is the issue relevant, why do you want to change something etc. Programmers make a lot of efforts on writing open source components. Thus, you also should by better interacting with them.

**Comment by BjoernLindner** [comment]
hi,

i don't know if it is the same problem as described above.
i used cocoapods to install SVProgessHUD.
my podfile looks like
`platform :ios, '8.1'
use_frameworks!

target 'MeineApp' do
  pod 'SVProgressHUD', :git => 'https://github.com/SVProgressHUD/SVProgressHUD.git'
end`

i open the project with the .xcworkspace file, try to import SVProgessHUD in my ViewController and then i get an info "No such modul 'SVProgessHUD'

any ideas?

regards Björn

**Comment by honkmaster** [comment]
It is working for me with Pods. Please provide a minimal demo project.
