### ISSUE TITLE
Can we have other progress bar styles

### ISSUE THREAD

**Issue by vincentsong** [SVProgressHUD/SVProgressHUD#660]
Such as horizontal bar?

**Comment by honkmaster** [comment]
Questions and issues like this, are the reason people burn out on open source. Don't let others do your work, give good questions, follow issue guidelines, provide a demo project or tell what you have already done to solve the problem. Why is the issue relevant, why do you want to change something etc. Programmers make a lot of efforts on writing open source components. Thus, do the community a favor,  show respect by writing a better issue.
