### ISSUE TITLE
Adding Haptic Feedback?

### ISSUE THREAD

**Issue by Vortec4800** [SVProgressHUD/SVProgressHUD#664]
I would be very interested in having SVProgressHUD automatically trigger Haptic Feedback events on the iPhone 7 when the success or error HUDs are called. Is there interest in this for anyone else? It would definitely be a configurable option, perhaps even disabled by default, so it doesn't get in the way of other Haptics that may be included in an app.

If there is interest I would be more than happy to work on this and submit a PR for it, but I don't want to develop it if it isn't wanted as part of the framework.

More information about the new API is here:

https://www.hackingwithswift.com/example-code/uikit/how-to-generate-haptic-feedback-with-uifeedbackgenerator

**Comment by honkmaster** [comment]
In general: Welcome this idea, however, the HUD must remain compatible down-to iOS 7. This would be work that is only available to a few users and I am not sure about how to use this feedback very "sensible".

**Comment by Vortec4800** [comment]
Okay, well if you're open to the idea in general I'll put something together and send it as a PR and we can discuss more details there.

Agree that not many users would be able to use it at first, but with the functionality baked in it will be cool as users start to feel it in their existing apps when they get a new phone. Apple has specific feedback templates for success and error notices, so I'm hoping it will show up in various places around the system and feel right at home.

**Comment by honkmaster** [comment]
If Apple has really feedback templates for success and error notices this would be a solid justification as well as motivation for the PR. Please add them to the discussion.

**Comment by Vortec4800** [comment]
I've created a PR (#665) where we can continue the discussion there.
