### ISSUE TITLE
It's error when start Run my Program

### ISSUE THREAD

**Issue by ShowChance** [SVProgressHUD/SVProgressHUD#666]
I just '#import <SVProgressHUD.h>' and use the '[SVProgressHUD show]'

It's happened when I start Run , But It's fine in Building .

Is never run success again , unless I don't use it . or I use cocoapods install again.

error line 345 in file 'SVProgressHUD.m' 
NSBundle *bundle = [NSBundle bundleForClass:[SVProgressHUD class]];
NSURL *url = [bundle URLForResource:@"SVProgressHUD" withExtension:@"bundle"];
NSBundle *imageBundle = [NSBundle bundleWithURL:url];

2016-09-16 01:14:30.602 demo[15289:554746] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[NSBundle initWithURL:]: nil URL argument'

**Comment by dongmai** [comment]
me same

**Comment by honkmaster** [comment]
Guys, this is a common issue, where the bundle is not copied to target. Next time use the search please ...
