### ISSUE TITLE
#define SV_APP_EXTENSIONS 1  dose not work

### ISSUE THREAD

**Issue by yuchuanfeng** [SVProgressHUD/SVProgressHUD#668]
![image](https://cloud.githubusercontent.com/assets/10720607/18657532/add38a1e-7f2d-11e6-9352-519511694654.png)

**Comment by yuchuanfeng** [comment]
Occasionally I just want add HUD to self.view not the window, how can do it? thanks

**Comment by honkmaster** [comment]
Could your provide a demo project (minimal sample) to better see how you use it? It is working for me.

**Comment by yuchuanfeng** [comment]
Sorry，I just want add HUD to self.view， and my project no APP_EXTENSIONS, have solution?

**Comment by honkmaster** [comment]
I do not understand your english and thus the intention of what you want to achieve is unclead.

**Comment by yuchuanfeng** [comment]
首先我的工程里面没有用到app extention。我想把HUD 添加到某一个控制器的View上面，应该怎么做？？
