### ISSUE TITLE
'SVProgressAnimatedView.h' file not found

### ISSUE THREAD

**Issue by shenyufei** [SVProgressHUD/SVProgressHUD#670]
Show in PNG.
![477050e7-f374-4752-b192-a28ba9694ff9](https://cloud.githubusercontent.com/assets/13211527/18704778/ee8f22ca-801d-11e6-9440-cf404915745d.png)

I use pods. What should I do? I not doing anything,not delete.

**Comment by honkmaster** [comment]
It is working for me with Cocoapods. How did you integrate the component, please provide a sample project, or a more detailed description. Otherwise this issue will be closed.

**Comment by dcalhoun** [comment]
For reference, I ran into this as well. I really have no idea why. I'm fairly green when it comes to CocoaPods and iOS dev in general.

I got around this missing file error by updating my Podfile and running `pod install` again.

```diff
-pod 'SVProgressHUD'
+pod 'SVProgressHUD', :git => 'https://github.com/SVProgressHUD/SVProgressHUD.git'
```

**Comment by shenyufei** [comment]
You're right,Thank you ~ @dcalhoun
