### ISSUE TITLE
Cannot present next HUD right away after dismissing previous

### ISSUE THREAD

**Issue by iThinker** [SVProgressHUD/SVProgressHUD#671]
When calling `SVProgressHUD dismiss` one would expect it to dismiss right away, and be able to present next HUD. But if you try to present new HUD right away, it will be presented and immediately dismissed, because previous dismiss is enqueued and will happen after presentation.
Popping activity does not work, because I show only one HUD at a time. I dismiss one and then try to present another. Modules that present HUD are completely unrelated, meaning that I cannot change the HUD instead of dismissing-presenting it.
the proposed solution is to dismiss HUD right away if there is no delay, and cancel animation if new HUD presentation is requested.

P.S. From what I see, delay is not handled properly if there is `fadeOutAnimationDuration` is 0. Instead of dismissing with delay, it simply ignores delay and dismisses right away in that case.

**Comment by afc1903** [comment]
I'm having exactly the same issue.  Show the spinner while user is logging in, dismiss it once login has finished and move to new view controller where I then present a different loading spinner with a message.  If I switch on slow animations on the simulator I can see the second spinner appear and disappear immediately as if dismissed but the dismiss call is the previous one.

**Comment by acicartagena** [comment]
Same issue with handling nested asynchronous operations. Show the HUD, dismiss after the first callback, then show it again before the start of the second asynchronous operation. It's not showing up again.

**Comment by ssuchanowski** [comment]
Same here. Though I have a work around which seem to do the job for me. I've added a delay to showing the HUD (I know that it's not what any of us would like to have but it do works with little to none effort).
```
let delayTime = dispatch_time(DISPATCH_TIME_NOW, Int64(0.3 * Double(NSEC_PER_SEC)))
dispatch_after(delayTime, dispatch_get_main_queue()) {
    dispatch_async(dispatch_get_main_queue()) {
        SVProgressHUD.show()
    }
}
```

**Comment by ssuchanowski** [comment]
Even better you can use `SVProgressHUD.sharedView().fadeOutAnimationDuration` as a delay -- but `sharedView()` is not accessible so I've ended up writing a category revealing this publicly.

**Comment by lforme** [comment]
`    dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(1 * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
        [SVProgressHUD show];
        [SVProgressHUD dismiss];
        [SVProgressHUD showWithStatus:@"error"];
        [SVProgressHUD dismissWithDelay:2];
    });` 
When i run this code, HUD can not show.

**Comment by honkmaster** [comment]
I tried 

```
[SVProgressHUD showWithStatus:@"First time show"];
[SVProgressHUD dismiss];
[SVProgressHUD showInfoWithStatus:@"Second time show"];
```

and it was working fine. Hmm.

**Comment by ssuchanowski** [comment]
Which iOS? I think I tried iOS 9 and 10. Swift 2.3.

**Comment by honkmaster** [comment]
Xcode 8, iOS 10, Objc.

**Comment by iThinker** [comment]
@honkmaster trying 2.1.2 Seems to work fine. Issue was opened with 2.0.3 version. Will conduct additional test and close if everything is fine. Thank you.

**Comment by CoderKid101** [comment]
Could Someone Also Tell How To Lower The Time It Takes For ProgressHUD To Dismiss After Being Launched?

Code:

@IBAction func logOutPressed(_ sender: AnyObject) {
    
    //TODO: Log out the user and send them back to WelcomeViewController
    do {
        try Auth.auth().signOut()
        SVProgressHUD.showSuccess(withStatus: "Logging Out Sucsessful")
        navigationController?.popToRootViewController(animated: true)
    }
    
    catch {
        print("Error Logging Out : \(error)")
        SVProgressHUD.showError(withStatus: "Logging Out Unsucsessful")
        **SVProgressHUD.dismiss()** Tryed But HUD Duration Is Same Length.
    }
    
}
