### ISSUE TITLE
Padding is not right when show string only.

### ISSUE THREAD

**Issue by StYaphet** [SVProgressHUD/SVProgressHUD#674]
I set image to `nil` use `setErrorImage:` method，and found that if the string is too long，the padding between  string label and it's background view is not correct.Issues #359 discussed this before, and @azone fix it (commit id :51e46db9051faf64a03098f8d5eeb629b557f4cc).But it's seems that his code didn't merged into master branch.

**Comment by honkmaster** [comment]
Please provide a demo project.

**Comment by StYaphet** [comment]
![SV Bug](http://7xpt7v.com1.z0.glb.clouddn.com/sv_error.png)

This is screen shot,and my code is just modify the ViewController's `showErrorWithStatus` method (in the Demo you provided) as follows：

     - (void)showErrorWithStatus {
        [SVProgressHUD showMessage:@"Failed with Error Failed with ErroFailed with ErrorFailed with Error"];
    }
