### ISSUE TITLE
SVProgressHUD is not showing center in iOS10.

### ISSUE THREAD

**Issue by vpndemand** [SVProgressHUD/SVProgressHUD#675]
It was showing center in iOS9.Once it run in iOS 10, it's showing in upper left corner. Only on first time install.

**Comment by jiayuanfa** [comment]
Me too.

**Comment by sourabhsharmait** [comment]
I am using IQKeyboard and It was the issue for me.

There should be a disabled property for keyboard handling

**Comment by honkmaster** [comment]
I can not reproduce this issue, please provide a demo project.

**Comment by patgoley** [comment]
I'm also having this issue on iOS 10, however I'm building with Xcode 7.3.1, deployment target 9.0. I'm not sure this is the cause or if this is a common use case, just trying to provide some more info. I'll work up a demo project if I have some extra time.

**Comment by krisanthony** [comment]
Are you all seeing this in the simulator? If so, it may be because you have the soft keyboard hidden. I've noticed with the soft keyboard hidden but a textfield selected, the progress view is being moved to accommodate for a keyboard that is not visible.

Hope this helps.

**Comment by nitinumaretiya123** [comment]
I am still having this issue any solutions ?

**Comment by hdmdhr** [comment]
I am also having this issue on Xcode 11.3.1, iPhone 11, iOS 13 Simulator. SVProgressHUD shows at top left corner of the screen.

**Comment by thecolourfool** [comment]
Me too ✋

**Comment by hdmdhr** [comment]
> Me too ✋



> I am still having this issue any solutions ?

Please check this: https://github.com/SVProgressHUD/SVProgressHUD/issues/1002#issuecomment-555940717, it solved my problem.
