### ISSUE TITLE
When BTProgressHUD is used togheter with CRSAlertView, it stops showing

### ISSUE THREAD

**Issue by vackup** [SVProgressHUD/SVProgressHUD#676]
Hi! I've found an issue. When you use BTProgressHUD togheter with CRSAlertView, it stops showing.

The issue is in ProgressHUD.cs, method void ShowProgressWorker (float progress = -1, string status = null, MaskType maskType = MaskType.None, bool textOnly = false, ToastPosition toastPosition = ToastPosition.Center, string cancelCaption = null, Action cancelCallback = null, double timeoutMs = 1000, bool showContinuousProgress = false, UIImage displayContinuousImage = null)

In this code

```
            foreach (UIWindow window in windows) {
					if (window.WindowLevel == UIWindowLevel.Normal && !window.Hidden) {
						window.AddSubview (OverlayView);
						break;
					}
				}
```

The issue is because CRSAlertView adds a new window, so in addttion to window.WindowLevel == UIWindowLevel.Normal && !window.Hidden, we must check is is IsKeyWindow, eg: I replaced that code with this:

```
var window = windows.FirstOrDefault(w => w.WindowLevel == UIWindowLevel.Normal && !w.Hidden && w.IsKeyWindow);
			    if (window == null)
			    {
			        throw new Exception("Can't find a visible key window to add the subview");
			    }

                window.AddSubview(OverlayView);
```

**Comment by honkmaster** [comment]
Do you mean BTProgressHUD or SVProgressHUD?

**Comment by vackup** [comment]
BTProgressHUD

**Comment by honkmaster** [comment]
This is the repository for `SVProgressHUD`, please post issues related to `BPProgressHUD` here: https://github.com/nicwise/BTProgressHUD

**Comment by vackup** [comment]
UPS, Sorry! i followed the wrong link :( never mind, i'm going to post it there
THANKS!
