### ISSUE TITLE
Progress indicator jitter / stutter when using SVProgressHUDMaskTypeGradient

### ISSUE THREAD

**Issue by PlasmaSoftUK** [SVProgressHUD/SVProgressHUD#677]
As per title, when using Progress indicator with SVProgressHUDMaskTypeGradient the ring stutters and seems delayed. When switching to SVProgressHUDMaskTypeBlack this behaviour is not seen.

This is under Xcode 8 and IOS 10.

Plasma

**Comment by funnel20** [comment]
I have a similar issue with Xcode 8.2.1 and iOS 10.2 on an iPhone 7.
I'm using version 2.1.2.
The HUD is used in a WKWebView and when the observer receives an update for "estimatedProgress".
Was still using version 1.1.3, where the ring is fluently going towards 100%, it now jitters, which is ugly.
Changing from SVProgressHUDMaskTypeGradient to SVProgressHUDMaskTypeBlack doesn't help.
