### ISSUE TITLE
Why not display settings

### ISSUE THREAD

**Issue by xxwang** [SVProgressHUD/SVProgressHUD#679]
Why there is no display settings, only the default disappear time

**Comment by honkmaster** [comment]
What do you want to say with this issue, it remains unclear to me. FYI: Questions like this, are the reason people burn out on open source. Don't let others do your work, give good questions, follow issue guidelines, provide a demo project or tell what you have already done to solve the problem.

**Comment by honkmaster** [comment]
Very "good idea" to close the issue instead of specifying what you want to ask.
