### ISSUE TITLE
UIVisualEffectViews transition error

### ISSUE THREAD

**Issue by maplelover** [SVProgressHUD/SVProgressHUD#680]
[SVProgressHUD showInfoWithStatus:@"This is information."];

The transition animation of text elements is very smooth.
But the background view, which is UIVisualEffectViews, appears and disappears suddenly.

How can I fix it?

**Comment by algrid** [comment]
Maybe related to this: http://stackoverflow.com/questions/29307827/how-does-one-fade-a-uivisualeffectview-and-or-uiblureffect-in-and-out

**Comment by maplelover** [comment]
It's better to fix this issue within SVProgressHUD.

**Comment by honkmaster** [comment]
Acknowledged. Working on a fix.

**Comment by honkmaster** [comment]
I have a fix implemented. Will push soon.
