### ISSUE TITLE
How to handle different screen orientation ?

### ISSUE THREAD

**Issue by LeeWongSnail** [SVProgressHUD/SVProgressHUD#681]
In my project , I just support UIInterfaceOrientationPortrait, but in some interface，i use CMMotionManager to observe the interfaceOrientation change ,and make different UI display , can SVProgressHUD support this , i need different orientation HUD based on current orientation!

**Comment by honkmaster** [comment]
What is the overall question? What do you want to achieve, It remains unclear to me.
