### ISSUE TITLE
dismissWithDelay BUG 

### ISSUE THREAD

**Issue by j19927166** [SVProgressHUD/SVProgressHUD#682]
Call "dismissWithDelay", SVProgressHUD do not show in View

**Comment by honkmaster** [comment]
What do you want to say with this issue, it remains unclear to me. How to reproduce the issue etc.? FYI: Questions like this, are the reason people burn out on open source. Don't let others do your work, give good questions, follow issue guidelines, provide a demo project or tell what you have already done to solve the problem.
