### ISSUE TITLE
Changing status while showing SVProgress

### ISSUE THREAD

**Issue by cilasgimenez** [SVProgressHUD/SVProgressHUD#683]
I have this code:

```
        SVProgressHUD.show(withStatus: "Getting data...")
        DispatchQueue.main.asyncAfter(deadline: .now() + .seconds(1), execute: {
        CODE
        CODE
        })
```

Now in some place in my code, during this main queue a want to update the "Getting data" status(label) to something else. I tried 
`SVProgressHUD.setStatus(" Something Else ")`
But it updates de label just before i dismiss the SVProgressHUD.

I know its something related to the threading. But what should be the right way to change the status label while running something on background? 
Thanks

**Comment by honkmaster** [comment]
I cannot reproduce the issue. This is my code:
```
- (void)show {
    [SVProgressHUD showWithStatus:@"First"];
    [self performSelector:@selector(show2) withObject:nil afterDelay:4.0f];
}


- (void)show2 {
    [SVProgressHUD setStatus:@"Second"];
}
```

In general I can not recommend using GUI stuff on the background thread. If you need further investigation provide a demo project.
