### ISSUE TITLE
SVProgressHUD did not show right away after dismiss the previous one

### ISSUE THREAD

**Issue by LimyronChin** [SVProgressHUD/SVProgressHUD#687]
I use SVProgressHUD in intermodulation between JS and OC. First, JS will call a native method to show a SVProgressHUD Loading HUD, and dismiss it until remote data to be refreshed, then JS will call anthoer native method to show a SVProgressHUD Info HUD, but the Info HUD did not show. Is this a thread problem? or a problem of SVProgressHUD?

**Comment by honkmaster** [comment]
In general I can not support JS / OBJC bridging. What version are you are using.

**Comment by LimyronChin** [comment]
Sorry to reply you so late!
The version of SVProgressHUD that I use in our project is the latest!
The way I use SVProgressHUD in intermodulation between JS and OC is not depend on the support of JS / OBJC bridging which is provided by SVProgressHUD itself, because I resolved previously the JS / OBJC bridging operation and just use SVProgressHUD in the callback function body. And I think that is the Thread Operation Sequence caused this problem. Or, Will SVProgressHUD dismiss itself in advance when detect that it will be dismissed finally?

**Comment by xiaozhi** [comment]
I have the same problem.
like this:
```
[SVProgress showWithStatus:@"First time show"];
[SVProgress Dismiss];
[SVProgress showInfoWithStatus:@"Second time show"];
```
The second time no display.
In my debug, the process is as follow:

1､"First time" dismiss (but no complete, Animations take some time)
2､"Second time show", (Update HUD View)
3､"Frist time" Animation complete, the HUD view remove from superView.
4､"Second time" dismiss

In setup 2,3 ，" Second time show" display duration very short.

**Comment by LimyronChin** [comment]
@xiaozhi 
Maybe the phenomenon you talked about caused the problem. Because SVProgressHUD maintain only one HUD all the way.

**Comment by honkmaster** [comment]
@xiaozhi You code is working for me => thus can not reproduce.

**Comment by xiaozhi** [comment]
@honkmaster My version is 1.7  ,Sorry
