### ISSUE TITLE
Drop support for iOS Versions older than iOS 9? FEEDBACK REQUIRED!

### ISSUE THREAD

**Issue by honkmaster** [SVProgressHUD/SVProgressHUD#690]
Nowadays the build tools, especially Xcode only support the latest iOS (=10) and latest iOS - 1 (=9). Is it reasonable to drop support for all smaller iOS versions? This would really optimise the codebase a lot. Please comment!

**Comment by mkassoff** [comment]
Fine by me.

**Comment by honkmaster** [comment]
As the minimum deployment target with Xcode 8 is iOS 8 i think I will change it accordingly.

**Comment by warpling** [comment]
I still target iOS 8+ but if it truly helps to do this for future releases then by all means.

**Comment by Dids** [comment]
I've been targeting iOS 9+ for a while now, so don't see why older versions should be supported at this point.

**Comment by AcidicSkittles** [comment]
I still support 7, but that's just my unpopular opinion.

**Comment by wberger** [comment]
iOS 8 support would be great.

**Comment by honkmaster** [comment]
Funny sidenote: I downloaded Xcode 7 to test with iOS 7. But inside Xcode 7 you can not download an iOS 7 simulator anymore ...

**Comment by jmcazaux** [comment]
iOS 8 is still a significant portion of users when an app is mostly used on tablets 
FWIW https://david-smith.org/iosversionstats/

**Comment by honkmaster** [comment]
Thanks, totally forgot about _ iOS stats.

**Comment by honkmaster** [comment]
Tried also now Xcode 6. It does nut run on Sierra. You need to apply cruel fixes to make it work, but even than the simulator does not work (http://indiestack.com/2016/08/xcode-6-on-sierra/) Therefore it is not reasonable at all to still support iOS 7, as we can not test anymore. 

iOS 8 will therefore be the minimum target.

**Comment by LeoNatan** [comment]
@jmcazaux Significant portion = 5% of tablets?

**Comment by mickeyl** [comment]
9 should be fine these days

**Comment by dafnedegroof** [comment]
if iOS 8 is not supported anymore, I'll have to look for a replacement

**Comment by LeoNatan** [comment]
@dafnedegroof Or just use a version that supports iOS 8. No need to be dramatic.

**Comment by svintus** [comment]
We still support iOS 8, but I agree with dropping it. We'll pin to a version that supports iOS 8 and will have yet another reason to drop iOS 8 in our app :D

**Comment by honkmaster** [comment]
We will remain on 8 for now and support always the latest version supported by Xcode.
