### ISSUE TITLE
Error:SVProgressHUD.m and line 345  bundle url is nil

### ISSUE THREAD

**Issue by baiyidjp** [SVProgressHUD/SVProgressHUD#694]
NSBundle *bundle = [NSBundle bundleForClass:[SVProgressHUD class]];
NSURL *url = [bundle URLForResource:@"SVProgressHUD" withExtension:@"bundle"];
NSBundle *imageBundle = [NSBundle bundleWithURL:url]; // this url is nil  

i am install with cocoapods  Installing SVProgressHUD (2.0.3)

**Comment by honkmaster** [comment]
Please search old issues. This is a known cocoapods issue.
