### ISSUE TITLE
This code is what meaning, don't understand, trouble to help me explain.

### ISSUE THREAD

**Issue by zhoupengju** [SVProgressHUD/SVProgressHUD#695]
(window.windowLevel >= UIWindowLevelNormal && window.windowLevel <= self.maxSupportedWindowLevel)

**Comment by honkmaster** [comment]
Sorry, I do not understand your question.

**Comment by zhoupengju** [comment]
You help me explain what is the meaning of this code

**Comment by honkmaster** [comment]
This code iterates over all UI windows and checks if the current one in iteration has the right window level. If so, the hud is added to this windows. 

Please check the UIWindowLevel for more documentation.

**Comment by zhoupengju** [comment]
Thank you very much!
