### ISSUE TITLE
Crash on overlayViewDidReceiveTouchEvent:forEvent (100% iOS 8)

### ISSUE THREAD

**Issue by jetstar89** [SVProgressHUD/SVProgressHUD#696]
Hi there,
I got thousands of crash issue when adding observer for SVProgressHUDDidReceiveTouchEventNotification.
Here is my code:
`[[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(hudTapped:) name:SVProgressHUDDidReceiveTouchEventNotification object:nil];
        [SVProgressHUD showWithStatus:@"Loading...\n(Tap to cancel)"];
- (void)hudTapped:(NSNotification *)notification {
    [SVProgressHUD dismiss];
    [[NSNotificationCenter defaultCenter] removeObserver:self name:SVProgressHUDDidReceiveTouchEventNotification object:nil];
}`
And I see on crashlytic that always happens on iOS 8.
Could you take a look for this bug?
Thanks,

**Comment by jetstar89** [comment]
Here is Raw Text:
Fatal Exception: NSInvalidArgumentException
-[__NSCFDictionary hudTapped:]: unrecognized selector sent to instance 0x174e66ec0

**Comment by honkmaster** [comment]
The stacktrace tells you that `hudTapped:` is the unrecognized selector and that the error is not inside the HUD. Your code tries to call `hudTapped:` on an internal `NSDictionary` class.
