### ISSUE TITLE
minimumSize default is not CGSizeZero

### ISSUE THREAD

**Issue by Crycil** [SVProgressHUD/SVProgressHUD#697]

**Comment by honkmaster** [comment]
What do you want to say with such a cryptic issue?

Questions and issues like this, are the reason people burn out on open source. Don't let others do your work, give good questions, follow issue guidelines, provide a demo project or tell what you have already done to solve the problem. Also give feedback if required! This is a matter of respect for the programmers that make a lot of efforts on writing open source components.

**Comment by Crycil** [comment]
Sorry, I did not describe it clearly.
In 2.0.4
SVProgressHUD.m  `- (instancetype)initWithFrame:(CGRect)frame` set default value `_minimumSize = CGSizeMake(100.0f, 100.0f)`，but in SVProgressHUD.h `minimumSize` is described as "default is CGSizeZero, can be used to avoid resizing for a larger message". When I use 
`[SVProgressHUD setDefaultStyle:SVProgressHUDStyleCustom];` 
`[SVProgressHUD setInfoImage:nil];`
to show status , the HUD frame will be not correct.
