### ISSUE TITLE
show*WithStatus goes offscreen if status message is too long.

### ISSUE THREAD

**Issue by bzeeman** [SVProgressHUD/SVProgressHUD#699]
After updating to the latest version of SVProgressHUD I noticed that my HUD's were too wide if the status message was too long. I believe these used to word wrap instead of running off screen.
![simulator screen shot dec 7 2016 12 56 48 pm](https://cloud.githubusercontent.com/assets/2799913/20984242/a897d762-bc7c-11e6-9e14-051bec8d292a.png)

**Comment by nealsun** [comment]
same issue
