### ISSUE TITLE
UIVisualeffect fade in / fade out on iOS 8 

### ISSUE THREAD

**Issue by honkmaster** [SVProgressHUD/SVProgressHUD#703]
UIVisualeffect fade in looks broken on iOS 8. Currently we assign the effect inside an UIViewAnimation block:

`self.hudView.effect = blurEffect;`

This is only available since iOS 9. However, we can not use `alpha` values as `UIVisualeffect` does not allow these to be animated and requires a constant `1.0` alpha on its views.

**Comment by honkmaster** [comment]
Seems like setting the alpha values on iOS 8 works, even though it stills throws a warning. Still setting alphas on iOS 9 and above looks broken. Thus, we need some `if-else` magic ...

**Comment by NikitaSerhieiev** [comment]
@honkmaster  Can you provide demo that works fine on iOS8, please ?

**Comment by honkmaster** [comment]
I forgot to push. Will do this evening, as I am not at my Mac at the moment.

**Comment by NikitaSerhieiev** [comment]
It will help a lot! Thanks!

**Comment by NikitaSerhieiev** [comment]
Problem caused by this row:
self.hudVibrancyView.effect = [UIVibrancyEffect effectForBlurEffect:blurEffect];
commenting it resolve problem on 8 iOS.
Can't see difference on 10 iOS with or without it.

found problem on 9 iOS and commenting this row resolve this problem too.

adding if-else magic resolve problem with fade out on 8 iOS

**Comment by NikitaSerhieiev** [comment]
May I ask some questions?
in your commit i see some problems
1. on iOS 8 there are 2 problems
1) first "show" show HUD with no "appear" animation (second and other works ok)
2) is it everything ok with ring, when HUD shrinked already?
https://www.youtube.com/watch?v=c2mjdrqPNJ0
2. problem on iOS 9
some blue background is visible when animation start.
https://www.youtube.com/watch?v=yestJ02sG8Q

Please take a look at this videos and answer should are this problems be resolved?
If yes, i can make a pull request. I have resolved them already.

**Comment by honkmaster** [comment]
The later one is resolved in the latest master. Which version are you using?

**Comment by NikitaSerhieiev** [comment]
2.1.2

I just download and test latest version on device and there is really no problems with blue background on iOS 9

and what about iOS 8?

**Comment by yigitserin** [comment]
Can confirm there is a visual bug (blue background) in 2.1.2 version on iOS 9.3.

Had to turn off fade animations like this:
```
        SVProgressHUD.setFadeInAnimationDuration(0)
        SVProgressHUD.setFadeOutAnimationDuration(0)
```
