### ISSUE TITLE
2.0.4版本无法使用纯文字提醒

### ISSUE THREAD

**Issue by braveeeehu** [SVProgressHUD/SVProgressHUD#705]
在2.0.4版本中使用+ (void)showImage:(UIImage*)image status:(NSString*)status ，image传nil时文字下方还是显示图片的空间，2.0.3版本不会

**Comment by braveeeehu** [comment]
hello,i'm sorry.
I just realized that  you don't speak Chinese，but my English is not good(so bad),so i hope you can understand.
I want a hub that just show text,i used this method:
[SVProgressHUD showImage:nil status:@"text"];
The results are as following：
![img_4272](https://cloud.githubusercontent.com/assets/18521239/21133412/a3643f16-c153-11e6-9498-bbe6b3ea305d.JPG)
but the same way in version 2.0.3 show right result，like this:
![img_4274](https://cloud.githubusercontent.com/assets/18521239/21133505/0f93a762-c154-11e6-84ca-c9af45a226ed.JPG)

**Comment by honkmaster** [comment]
2.0.3 is quite old. Please update to 2.1.2. It is fixed there.

**Comment by braveeeehu** [comment]
thanks.Because i used 'pod search SVProgressHUD' and the latest version is 2.0.4......i forget to update local repo😢  sorry.....
