### ISSUE TITLE
v2.1.2 in iOS8.3 no display message

### ISSUE THREAD

**Issue by Jasonvvei** [SVProgressHUD/SVProgressHUD#706]
iPhone4S with iOS8.3 
SVProgressHUDStyle  set  SVProgressHUDStyleDark

is black  no display message

![screen shot 2016-12-14 at 16 28 25](https://cloud.githubusercontent.com/assets/14148888/21175130/e9dbfa88-c21b-11e6-873e-50e95397908d.png)

**Comment by honkmaster** [comment]
Will check that.

**Comment by honkmaster** [comment]
Which method did you use? On Simulator it looks fine.
 
<img width="467" alt="screen shot 2016-12-14 at 12 13 47" src="https://cloud.githubusercontent.com/assets/1380397/21179961/df4a38f2-c1f6-11e6-8b60-dfcc6fe8b330.png">

**Comment by Jasonvvei** [comment]
On Simulator it's fine. Mobile phone no display message ,  All method of show info will show this problem

**Comment by aimm** [comment]
iPhone4S iOS 8.1.2 , the message and the indicator is indistinct，and become clear when the hud is about to dismiss

**Comment by NickeyLin** [comment]
I have the same problem. iPhone5s iOS 8.3.

**Comment by haoXu1990** [comment]
楼上的兄弟，你解决了么

**Comment by aimm** [comment]
换低版本的吧，别用最新的就好了

**Comment by JanzTam** [comment]
I had the same problem on iPad min2( iOS 8.2 )

**Comment by JanzTam** [comment]
I had the same problem when i use that code(iPad min2( iOS 8.2 )):
```Swift
SVProgressHUD.setDefaultStyle(.dark)
```
Now it's good , replace with the code:
```Swift
SVProgressHUD.setDefaultStyle(.custom)
SVProgressHUD.setForegroundColor(.white)
SVProgressHUD.setBackgroundColor(UIColor.black.withAlphaComponent(0.8))
```

Anyway,thanks man.

**Comment by haoXu1990** [comment]
你好：
   我是用的 OC 版本的 ，当我发现问题后根据前面朋友的建议，把版本回滚到1.1.3  使用至今没有发现什么问题。

**Comment by honkmaster** [comment]
Guys, to be honest. Apple does not allow to test iOS 8 anymore. The iOS 8 simulators are mising from the current Xcode. In addition, any device running 8 can run 9. This bug will and can not be fixed, if not by you guys with an old Xcode version.

**Comment by honkmaster** [comment]
By the way: Chinese comments will not help me to understand the issue.

**Comment by cookey91** [comment]
在iOS 8下 显示几次之后 文字颜色会越来越深 最后就完全看不见了

**Comment by zvving** [comment]
![screen shot 2017-08-15 at 17 44 11](https://user-images.githubusercontent.com/485079/29310710-5fa82f04-81e1-11e7-8d0e-4a30823d0677.png)

@honkmaster I can install iOS8 simulator in Xcode8.3.3

**Comment by honkmaster** [comment]
This should be fixed.
