### ISSUE TITLE
Why does the framework not define a module?

### ISSUE THREAD

**Issue by LeoNatan** [SVProgressHUD/SVProgressHUD#708]
Using Carthage, I get a .framework file. But it seems the project does not define a module, and so, there is no module map with the framework. And so, I cannot just `import SVProgressHud` in Swift or ObjC, I have to fiddle with header files.

Please add this. It is time frameworks behave in a modern fashion.

**Comment by LeoNatan** [comment]
Hmm, looking at the Framework target, it does. So something is defined correctly in the project, because the Carthage created framework does not work properly.

**Comment by honkmaster** [comment]
I do not use Carthage myself. The support was added by others (@flovilmart for example). So I can not help atm.

**Comment by LeoNatan** [comment]
If untested, you should not accept pull requests.

**Comment by flovilmart** [comment]
Can you use the .h version in the bridging header?

**Comment by LeoNatan** [comment]
As I said, I can, but in a modern framework, I shouldn't. Modules have been available for two years, and should be used by developers, just like dynamic frameworks vs static libs.

**Comment by honkmaster** [comment]
You can always provide a Pull Request. Thanks.
