### ISSUE TITLE
Problems after custom UIStoryboardSegue

### ISSUE THREAD

**Issue by seboslaw** [SVProgressHUD/SVProgressHUD#711]
Hey guys,

first of all, great work on the component! Love it!
In my application I have a custom storyboard segue. It's very simple and just replaces the window's current rootViewController with another one. I use it to transition from a signup dialog to the main interface of my app.
The problem is that after I run this segue, SVProgressHUD stops working. It simply doesn't show anymore. My guess is that by changing the rootViewController of the window I somehow messed up the view hierarchy? But that's just a wild guess :) Any clues on how to fix this?

My custom segue is as follows:

class ReplaceSegue: UIStoryboardSegue {

	override func perform() {
		// Assign the source and destination views to local variables.
		if let firstVCView = self.source.view as? UIView,
			let secondVCView = self.destination.view as? UIView {
		
			// Get the screen width and height.
			let screenWidth = UIScreen.main.bounds.size.width
			let screenHeight = UIScreen.main.bounds.size.height
			
			// Specify the initial position of the destination view.
			secondVCView.frame = CGRect(x: 0.0, y: screenHeight, width: screenWidth, height: screenHeight)
			
			// Access the app's key window and insert the destination view above the current (source) one.
			let window = UIApplication.shared.keyWindow
			window?.insertSubview(secondVCView, aboveSubview: firstVCView)
			
			// Animate the transition.
			UIView.animate(withDuration: 0.4, animations: { () -> Void in
				firstVCView.frame = firstVCView.frame.offsetBy(dx: 0.0, dy: -screenHeight)
				secondVCView.frame = secondVCView.frame.offsetBy(dx: 0.0, dy: -screenHeight)
				
			}) { (finished) -> Void in
				firstVCView.removeFromSuperview()
				window?.rootViewController = self.destination
			}

		}
	}
}

**Comment by honkmaster** [comment]
Hi Seb, 

thanks for the good bug description. The issue can be reproduced. It is due to `- (void)updateViewHierarchy` where the `containerView` is added to the `frontWindow` (given by an own method). This is only done once, while `containerView` has no superview. 

I think there should be an additional check if the current frontWindow is still the same as the superview, otherwise replace it. I will work on it in the next few days.

Grüße nach Berlin

**Comment by seboslaw** [comment]
Awesome! Glad I could "help" :)

Grüße nach Oldenburg!! ;)

**Comment by seboslaw** [comment]
Hey @honkmaster 
did you find any time to look into the issue? If not I'll be glad to help out (kind of need this fix for a pressing project ;). Can you give me a hint where to dig in?
