### ISSUE TITLE
2.1.2 does not work while 2.1.1 works fine

### ISSUE THREAD

**Issue by dzgnd** [SVProgressHUD/SVProgressHUD#716]
When i try to show a ProgressHud, the screen goes dim, but the ProgressHud does not show. Switching back to 2.1.1 makes it all work without a problem.

My environment is:
XCode 8.2.1.
iOS 9
Swift 3

My code:
    SVProgressHUD.setDefaultStyle(SVProgressHUDStyle.custom)
    SVProgressHUD.setForegroundColor(UIColor.gray)
    SVProgressHUD.setBackgroundColor(UIColor(0xF7F7F7))
    SVProgressHUD.setDefaultMaskType(SVProgressHUDMaskType.black)
    SVProgressHUD.show(withStatus: "Connecting")

**Comment by honkmaster** [comment]
This should be fixed. Please check the latest update.
