### ISSUE TITLE
[Warning] Setting the backgroundColor gives a warning log.

### ISSUE THREAD

**Issue by glennposadas** [SVProgressHUD/SVProgressHUD#717]
Hi all, thanks for this HUD. I spent my 8 hours looking for a new HUD. I used to use KVNProgress - but it messes up my Status Bar Style/Color, and author seems no longer interested in solving tickets???. 

So far this is the best one, and I will be integrating this to my production project in a few moments. 

It works fine with SplitVC, with NavigationController, and with TabBarController. Anyways, going back to the issue, I see a warning in my logs whenever I use a custom backgroundColor.

>  [Warning] <UIVisualEffectView 0x7fc474413890> is being asked to animate its opacity. This will cause the effect to appear broken until opacity returns to 1.

Any idea how to avoid this warning? If it's inevitable, then it's fine. :)

**Comment by honkmaster** [comment]
It is inevitable (due to iOS 8).

**Comment by glennposadas** [comment]
Thanks! Currently using this HUD to my biggest international project yet. And will use it again ;)
