### ISSUE TITLE
HUD has alpha of 0 when attempting to show with delayed dismissal

### ISSUE THREAD

**Issue by JoshHrach** [SVProgressHUD/SVProgressHUD#721]
I have a function that is mocking an upload. Essentially, it is the following:
```swift
func upload() {
  print("Uploading...")
  SVProgressHUD.show(withStatus: "Uploading...")
  SVProgressHUD.dismiss(withDelay: 5, completion: { print("Complete") })
}
```

However, while the HUD apparently operates fine, and I see the two print statements, the HUD itself never appears. Inspecting the UI during the HUD's appearance showed that the HUD had an alpha of 0. There is nothing in our project that affects the HUD's appearance in this manner, nor are other uses of the HUD disrupted at present.

Note that if I remove the .dismiss(withDelay: completion:) call, the HUD appears as if it is itself underneath something else, as the HUD, normally white, is grayed out like everything else normally is when the HUD appears.

**Comment by jacobo360** [comment]
Probably the number 5 there is 5 milliseconds (so its disappearing really fast). Try with 5000.
