### ISSUE TITLE
Success HUD now small?

### ISSUE THREAD

**Issue by Vortec4800** [SVProgressHUD/SVProgressHUD#722]
I've noticed in a recent update (alas I don't know which version exactly) the success HUD is now quite a bit smaller, basically just the size of the checkmark. Is this expected behavior, or is this a bug?

**Comment by pirags** [comment]
+

**Comment by honkmaster** [comment]
The HUD size previously was fixed (100x100 min) and now is dynamic based on the content. I could adjust the "spacers" left and right from the image, however I think it works out fine.

**Comment by shubh10** [comment]
Try this HUD library for iOS in swift https://github.com/shubh10/JustHUD

**Comment by honkmaster** [comment]
By the way you could still change the minimum size and ring radius.
