### ISSUE TITLE
accessibilityLabel should not be "SVProgressHUD"

### ISSUE THREAD

**Issue by hiltonc** [SVProgressHUD/SVProgressHUD#725]
A view's accessibilityLabel should human-readable text. End users will not understand what "SVProgressHUD" is when their screen reader reads it out loud to them. Having accessibilityIdentifier, which is not end-user-facing, set to "SVProgressHUD" is sufficient.

**Comment by honkmaster** [comment]
What would be a better text? Suggestion are very welcome!

**Comment by hiltonc** [comment]
Just set to accessibilityIdentifier to "SVProgressHUD", and don't set the accessibilityLabel.

**Comment by honkmaster** [comment]
I rechecked: The `accessibilityLabel` is changed in `showStatus` to the current string. This it is not `SVProgressHUD ` the whole time, it is just an initial value.

**Comment by kenji21** [comment]
Reproduced the issue, it is related to the mask type (SVProgressHUD.m:905-911):

````
    if(self.defaultMaskType != SVProgressHUDMaskTypeNone) {
        self.accessibilityLabel = status;
        self.isAccessibilityElement = YES;
    } else {
        self.hudView.accessibilityLabel = status;
        self.hudView.isAccessibilityElement = YES;
    }
````

If you change the default mask type, you will have two item that will be accessible : hudView and self.
So voice over read both of them because there is no ".isAccessibilityElement = NO"; to prevent this
