### ISSUE TITLE
Feature request. Cancel button

### ISSUE THREAD

**Issue by gerchicov-bp** [SVProgressHUD/SVProgressHUD#727]

**Comment by gerchicov-bp** [comment]
@honkmaster 
could you explain - Do you close this task because you won't implement it or do you need additional info about it?

**Comment by honkmaster** [comment]
I will add a section to the `Readme.md` as this was requested more than once. The main idea is to use `SVProgressHUDDidTouchDownInsideNotification` in your app and then call `dismiss`.

**Comment by lw254605953** [comment]
I do not think touch the HUD for cancel is a good interactive design
