### ISSUE TITLE
问下 关于键盘弹出状态下确认输入内容后，HUD会随着键盘下移到屏幕中心问题 

### ISSUE THREAD

**Issue by paintingStyle** [SVProgressHUD/SVProgressHUD#729]
问下 关于键盘弹出状态下确认输入内容后，HUD会随着键盘下移到屏幕中心问题 ，我想HUD一直处于屏幕中心，作者有什么好的设置方法吗

**Comment by honkmaster** [comment]
English please.

**Comment by wiliams-xu** [comment]
After hiding the keyboard, the HUD will move down with the keyboard to the center of the screen. I think it's  same with #450 .

**Comment by ShengkunZhang** [comment]
作者说: 在SVProgressHud.m界面中，此visibleKeyboardHeight决定着是否跟随键盘的出现与隐藏而上下移动。你可以试着修改本程序的源代码试试#443

**Comment by honkmaster** [comment]
@ShengkunZhang Please comment in englisch.

**Comment by ShengkunZhang** [comment]
@honkmaster I translate this sentence, you once said ”Not via API. However you could fiddle around with 'visibleKeyboardHeight' in 'SVProgressHud.m'.”
