### ISSUE TITLE
Click-to-dismiss mode

### ISSUE THREAD

**Issue by mantas** [SVProgressHUD/SVProgressHUD#730]
Hi,

I'd like to add click-to-dismiss mode. It'd make sense for displaying success/info/error. Sometimes I want to make sure that user did saw the message (e.g. it didn't time out before him seeing it) but allow quick close too.

I was thinking about adding additional parameter to showError/showSuccess `dismissOnTap` which would default to false. Would this fit the look'n'feel of this library?

Thanks!

P.S. I see there's https://github.com/SVProgressHUD/SVProgressHUD/pull/689 but it wasn't addressed in quite a while..

**Comment by lotus-lotus** [comment]
SVProgressHUDDidReceiveTouchEventNotification

**Comment by honkmaster** [comment]
@lotus-lotus is right. Use `SVProgressHUDDidReceiveTouchEventNotification` and close with it.
