### ISSUE TITLE
Question: Custom Success Image without Mask

### ISSUE THREAD

**Issue by cruisediary** [SVProgressHUD/SVProgressHUD#733]
I tried but everytime image was masked to foregroundColor
```Swift
SVProgressHUD.setDefaultStyle(.custom)
SVProgressHUD.setDefaultMaskType(.none)
SVProgressHUD.setSuccessImage(image)
```

how can i show SVProgressHUD success image without mask?

**Comment by honkmaster** [comment]
What do you mean with the mask here? Do you only want to show the image?
