### ISSUE TITLE
There is no effect with the delay method

### ISSUE THREAD

**Issue by qingkuangshusheng110** [SVProgressHUD/SVProgressHUD#734]
[SVProgressHUD showInfoWithStatus:@"Hello Word !"];
[SVProgressHUD dismissWithDelay:2.0f];

The above code, after running the direct HUD is not displayed

**Comment by NOlivNeto** [comment]
请用英文写.

The effect you probably want you can achieve with [SVProgressHUD dismissWithDelay:3.0f]

**Comment by qingkuangshusheng110** [comment]
You have already tested this method,if used alone [SVProgressHUD showInfoWithStatus:@"Hello Word !"]; The HUD will disappear after 5 seconds, regardless of the length of the character,
version :SVProgressHUD (2.0.4)

**Comment by qingkuangshusheng110** [comment]
If you call [SVProgressHUD dismissWithDelay: 2.0f] afterwards; then the HUD will not show

**Comment by qingkuangshusheng110** [comment]
Thank you. the problem has been resolved !

**Comment by NOlivNeto** [comment]
May you close this thread?
