### ISSUE TITLE
setDefaultMaskType not work

### ISSUE THREAD

**Issue by FrostBest** [SVProgressHUD/SVProgressHUD#735]
SVProgressHUD.setDefaultMaskType(.gradient)
not work

**Comment by NOlivNeto** [comment]
This issue is a duplicate of #719 

`setDefaultMaskType` is apparently only not working with `.gradient` in Swift 3 since version 2.1.2, at least. `.black` and `.white` seems to be ok.

**Comment by honkmaster** [comment]
Can someone provide a swift demo project?

**Comment by honkmaster** [comment]
Should be working again.
