### ISSUE TITLE
Dialog appears empty (no text or activity indicator)

### ISSUE THREAD

**Issue by RVoiseyFirstApp** [SVProgressHUD/SVProgressHUD#736]
Hi Everyone,

We are seeing an issue where showing a status message is not dispaying either the text or the activity indicator resulting in an empty box being shown. The text is being correctly shown on our test devices, but not on an iPad mini 2 with iOS 8.4. 

<img width="326" alt="screen shot 2017-03-17 at 14 24 53" src="https://cloud.githubusercontent.com/assets/7535013/24048110/cba867c0-0b1f-11e7-8792-41401b1aed03.png">

We also change the text by calling `[SVProgressHUD showSuccessWithStatus:NSLocalizedString(message, nil)]` and the box does resize so it indicates that the text is being received by the library.

We go through a few status text changes in the following order:

1.	`[SVProgressHUD showWithStatus:message]`
2.	`[SVProgressHUD showSuccessWithStatus:message, nil)]`
3.	`[SVProgressHUD showWithStatus:message]`
4. 	`[SVProgressHUD dismiss]`

All exhibit the same issue.

Any help would be appreciated!

Thanks,
Rob

**Comment by Juice007** [comment]
The same to me

**Comment by JanzTam** [comment]
The same to me. on an iPad mini 2 with iOS 8.2

**Comment by honkmaster** [comment]
To be honest; Apple does not allow to test iOS 8 anymore. The iOS 8 simulators are missing from the current Xcode. In addition, any device running 8 can run 9. This bug will and can not be fixed by me. You can do it however, if you still have an old Xcode version on your disk.

**Comment by cookey91** [comment]
https://github.com/SVProgressHUD/SVProgressHUD/issues/760

**Comment by honkmaster** [comment]
Could you check the current master?

**Comment by honkmaster** [comment]
This should be fixed.
