### ISSUE TITLE
a position error

### ISSUE THREAD

**Issue by LHJ-K2S** [SVProgressHUD/SVProgressHUD#740]
i think errr, if there is an containerView,maybe the hudVIew's center should not write as `containerView.center`. the right way should be `self.hudView.center = CGPointMake(self.containerView.bounds.size.width / 2, self.containerView.bounds.size.height / 2);`

actually, i used this way to slove my position problem.

**Comment by honkmaster** [comment]
Please provide a sample project to replicate the issue. Your code is functionally equivalent.

**Comment by LHJ-K2S** [comment]
here is a wrong demo and a right one.I made the y of the controller's view added by 64.
[SVProgressHUDDemoWithErrorPosition.zip](https://github.com/SVProgressHUD/SVProgressHUD/files/982817/SVProgressHUDDemoWithErrorPosition.zip)
[SVProgressHUDDemoWithRightPosition.zip](https://github.com/SVProgressHUD/SVProgressHUD/files/982824/SVProgressHUDDemoWithRightPosition.zip)

**Comment by mileswd** [comment]
@honkmaster Any update on this?

The `center` property of `UIView` is the center of the `frame`, relative to the superview. Consequently, the above code is not functionally equivalent - although it may appear to be under certain circumstances, such as when the frame has an origin of (0, 0).

I've attached another project demonstrating this issue: [Demo.zip](https://github.com/SVProgressHUD/SVProgressHUD/files/1321519/Demo.zip)

![demo screenshot](https://user-images.githubusercontent.com/5622554/30700609-f1bf049c-9edf-11e7-8067-5873191e769e.png)

Thanks in advance, and I really appreciate your efforts with this library! :smile:

**Comment by filipealva** [comment]
Any update on this?

It looks like even if we solve this `center` problem, the HUD is not calculating the navigationbar + statusbar to properly centralize on the window.
