### ISSUE TITLE
OrientationChanged

### ISSUE THREAD

**Issue by MyOnlyOnlySunshine** [SVProgressHUD/SVProgressHUD#741]
My App has to support landScapeOritentation，but hud does not support now.

**Comment by honkmaster** [comment]
![simulator screen shot 30 apr 2017 17 01 35](https://cloud.githubusercontent.com/assets/1380397/25565431/ae9dcda4-2dc6-11e7-83c7-a0074cd740ea.png)

The HUD does support landscape.
