### ISSUE TITLE
UIApplicationDelegate doesn't have window object

### ISSUE THREAD

**Issue by ArniDexian** [SVProgressHUD/SVProgressHUD#744]
Hi guys. Just wanna notice the code below is incorrect
`[[[UIApplication sharedApplication] delegate] window]`
Coz `UIApplicationDelegate` not always have `window` object, it usually generated by Xcode.
In my case I need to add property just to keep SVProgressHUD working.
I guess `[UIApplication sharedApplication].keyWindow` should be more correct way to get window object.

+ (SVProgressHUD*)sharedView method in SVProgressHUD.m

Thank's for attention.

**Comment by mkowalski87** [comment]
@ArniDexian Actually you can override window property in your AppDelegate in such cases

**Comment by honkmaster** [comment]
This is the correct answer.
