### ISSUE TITLE
"Landscape" likely SVProgressHUD in Portrait

### ISSUE THREAD

**Issue by d0ye** [SVProgressHUD/SVProgressHUD#746]
hi I'm demanding a SVProgressHUD in landscape or Horizontal mode, My View is landscape likely since I rotate all view.So any interface I could reaching a "landscape" SVProgressHUD in the 
Portrait Mode?

**Comment by honkmaster** [comment]
What do you want to achieve?

**Comment by honkmaster** [comment]
![simulator screen shot 30 apr 2017 17 01 35](https://cloud.githubusercontent.com/assets/1380397/25565436/c060ecb0-2dc6-11e7-8305-2a6830c51a7e.png)

By the way, the HUD already supports landscape

**Comment by d0ye** [comment]
I implement the "landscape" by rotate the view by codes like 
`view.transform = CGAffineTransform(rotationAngle: CGFloat(M_PI) / CGFloat(2))`
At that time watching for  a interface to show a "landscape" hud.
But seems there no one...

**Comment by honkmaster** [comment]
The HUD only applies the devices rotation.
