### ISSUE TITLE
关于玻璃效果的问题

### ISSUE THREAD

**Issue by kuangtao22** [SVProgressHUD/SVProgressHUD#750]
如果手机系统 通用-辅助功能-增强对比度-降低透明度关闭时，样式选择SVProgressHUDStyleDark时，弹出框文字和图案会变黑，看不清楚

**Comment by kuangtao22** [comment]
找到原因，UIBlurEffectStyleDark这个效果显示不了，导致文字也变黑了，求解决方法

**Comment by honkmaster** [comment]
Please reopen with an English text.
