### ISSUE TITLE
Very dark ring

### ISSUE THREAD

**Issue by pedro380085** [SVProgressHUD/SVProgressHUD#757]
Hi, recently I've come across a case where the ring is very dark (letters cannot be found). It happens only on 7s phones. See screenshot below.

![image uploaded from ios](https://cloud.githubusercontent.com/assets/1212753/25462804/ee913d3a-2ac7-11e7-809b-d584e48c570e.jpg)

Someone has any idea of what can be?

**Comment by honkmaster** [comment]
I can not debug iOS 7 as it is not supported by Xcode anymore. Maybe someone else has an idea.

**Comment by pedro380085** [comment]
Sorry, my mistake. This a is an iPhone 7 running on iOS 10.2.

**Comment by hychen1024** [comment]
self.hudVibrancyView.effect = [UIVibrancyEffect effectForBlurEffect:blurEffect];
commenting it resolve problem on 8 iOS.

**Comment by pedro380085** [comment]
Hi @hychen1024, thanks for commenting. You were experiencing a very similar issue to this?

**Comment by honkmaster** [comment]
Yes it this the vibrancy, which will be removed in a future update.
