### ISSUE TITLE
Can't seem to resize SVProgressHUD on tvOS

### ISSUE THREAD

**Issue by rickvdl** [SVProgressHUD/SVProgressHUD#761]
Hi All,

For some reason I can't seem to resize the SVProgressHUD spinner on tvOS. I've tried the following as described in the README:

```
SVProgressHUD.setMinimumSize(CGSize(width: 200, height: 200)
SVProgressHUD.setRingRadius(200)
```

I'm calling these methods in my `ViewDidLoad`, but they appear to be doing nothing, the result:

![simulator screen shot 5 may 2017 23 27 37](https://cloud.githubusercontent.com/assets/6663039/25764966/c12dc3f2-31ea-11e7-822d-13ca7d656fe9.png)

Thanks!

**Comment by honkmaster** [comment]
Will check it out. Thanks for reporting!

**Comment by rickvdl** [comment]
@honkmaster Thanks a lot, no worries. Let me know if you need more info!

**Comment by honkmaster** [comment]
I have a tvOS project this week, probable starting wednesday or thursday, good opportunity to get this fixed. The infos you provided are sufficient for now.

**Comment by honkmaster** [comment]
It seems to work with the recent master.

![simulator screen shot 7 sep 2017 15 57 58](https://user-images.githubusercontent.com/1380397/30167012-58069ef0-93e5-11e7-972d-3e0291e616c3.png)
