### ISSUE TITLE
How to handle Apple REJECT when using SVProgressHUD

### ISSUE THREAD

**Issue by leonfu** [SVProgressHUD/SVProgressHUD#762]
We still found your app uses or references the following non-public APIs:

NSBlock, UIInputSetContainerView, UIInputSetHostView, UIKeyboard, UIPeripheralHostView, UIStatusBarDataNetworkItemView, __NSCFURLSessionConfiguration

**Comment by honkmaster** [comment]
Hm. 1) We do not use `NSBlock`, `UIStatusBarDataNetworkItemView`, and `__NSCFURLSessionConfiguration`. 2) `UIInputSetContainerView`, `UIInputSetHostView`, `UIKeyboard`, and `UIPeripheralHostView` are not used by class instantiation, they are only referenced by name `NSClassFromString`. We do not modify the view hierachy and all my submission to the App Store were fine.

**Comment by honkmaster** [comment]
However, maybe we could change to code to listen to `UIKeyboardDidShowNotification`.

**Comment by dyegos** [comment]
I got my app rejected:
```Your app uses or references the following non-public APIs:

UIInputSetContainerView, UIInputSetHostView, UIKeyboard, UIPeripheralHostView, UITabBarButton```

**Comment by honkmaster** [comment]
We do not use `UITabBarButton`.

**Comment by dyegos** [comment]
Okay, but the `UIInputSetContainerView, UIInputSetHostView, UIKeyboard, UIPeripheralHostView` is "used". I don't Apple is rejecting this code. What would be the solution to it?

**Comment by yanpanpan** [comment]
I also received this: **Your app uses or references the following non-public APIs:
 UIInputSetContainerView, UIPeripheralHostView, UIInputSetHostView, UIKeyboard**. I  would remove these code for submitting.

**Comment by dyegos** [comment]
@yanpanpan I did a "solution" and I'm waiting for Apple review. As soon as it works I'm gonna open a PR.

**Comment by honkmaster** [comment]
Is there any other way to determine the keyboard height during runtime? See the following sequence.

- Keyboard is visible <=> All Notifications already have been fired
- HUD should be shown for the first time <=> HUD gets allocated
- Now we need the keyboard height without notifications

This sequence would is not possible without the current implementation. I see that there "might" be a problem and as a "quickfix" I could remove the code fragment. Nonetheless, there need to be a solution for the sequence described above.

**Comment by dyegos** [comment]
My app was rejected again with the same problem even changing all comparations to `[NSStringFromClass([possibleKeyboard class]) isEqualToString:`.

**Comment by honkmaster** [comment]
Ok, the only reasonable solution is thus to remove the corresponding code. However, the issue of determining the keyboard height still remains. There must be a way to get the keyboard frame without actively listening for notifications.

**Comment by dyegos** [comment]
@honkmaster if I remove the code on my side, will it be okay or it can cause problems?

**Comment by honkmaster** [comment]
You can just return 0, will give no problems. However, the Hud might be displaced if the HUD is shown if an keyboard is already present.

**Comment by honkmaster** [comment]
I think I will try the solution presented [here](https://stackoverflow.com/questions/26981261/get-height-of-ios-keyboard-without-uikeyboardwillshownotification).

**Comment by honkmaster** [comment]
I check IQKeyboardManager. THey use the same technique. However, they [obfuscate ](https://github.com/hackiftekhar/IQKeyboardManager/blob/5abd305258f8c1456ad4e3b1932e398a0623892d/Demo/Objective_C_Demo/YYText/YYTextKeyboardManager.m#L191) their use of "private" API by checking prefix and suffix of the class.name and not the whole string ... 

```
  if (![subViewName hasPrefix:@"UI"]) continue;
  if (![subViewName hasSuffix:@"InputSetHostView"]) continue;
```

**Comment by dyegos** [comment]
@honkmaster that's a bypass. it could work, but I don't know if it's a complete solution. I think it's worth a try.

**Comment by puneetchd** [comment]
Is it safe to use SVProgressHUD since there has been issues related to rejection of app by Apple?

**Comment by honkmaster** [comment]
I implemented a bypass and someone has to give app review feedback if it works. By the way: I did not have a rejection for an app submitted last week.

**Comment by dyegos** [comment]
I see, in my case, I can't risk another rejection. So I just removed the code inside the method. But if anyone can test it, it would be good to know.

**Comment by alexqin1224** [comment]
I used the lasted version,but i got my app  rejected.   @honkmaster 


Your app uses or references the following non-public APIs:

UIPeripheralHostView
UIKeyboard
UIInputSetContainerView
UIInputSetHostView

**Comment by honkmaster** [comment]
Did you use the latest code?

**Comment by alexqin1224** [comment]
Yes,so i set the "visibleKeyboardHeight" to 0 without other code.Then the app already passed.

**Comment by honkmaster** [comment]
Just as an FYI: I got two apps through app review with the latest modifications with no problem.
