### ISSUE TITLE
How to set UIOffset?

### ISSUE THREAD

**Issue by Hearsayer** [SVProgressHUD/SVProgressHUD#763]
I use 
```
 SVProgressHUD.setOffsetFromCenter(UIOffset(horizontal: 100, vertical: 100))
```
but no any effect
how to set HUD's offset?

**Comment by honkmaster** [comment]
![simulator screen shot 26 may 2017 15 40 34](https://cloud.githubusercontent.com/assets/1380397/26496916/b6f76bb4-4229-11e7-802f-e409389856b2.png)

It is working for me. Do you have more details?

**Comment by Hearsayer** [comment]
I want to  HUD show in view, and set offset, e.g.:
```
SVProgressHUD.setContainerView(myView)
SVProgressHUD.setOffsetFromCenter(UIOffset(horizontal: 100, vertical: 100))
SVProgressHUD.show()
```
no any effect, it still stay in center.
look forward to your early reply, thank you!
