### ISSUE TITLE
SVProgressHUD HUD is changing position on screen

### ISSUE THREAD

**Issue by pdegouville** [SVProgressHUD/SVProgressHUD#767]
I have a weird behavior with SVProgressHUD. When I launch it : SVProgressHUD.show(), the HUD appears above the center and 1-2 second after, it goes down to the center. I want to have it directly in the center of the View. By the way, I have let nothing in my Viewcontroller and its view.

**Comment by honkmaster** [comment]
Can you provide a minimal demo project?

**Comment by shubh10** [comment]
Try this HUD library for iOS in swift https://github.com/shubh10/JustHUD

**Comment by dl528** [comment]
I tried with this code

`UIView *hudContainer = [[UIView alloc] initWithFrame:CGRectMake(0, 0, 100, 100)];
    hudContainer.center = CGPointMake(self.view.frame.size.width/2, self.view.frame.size.height/2 + 40);
    hudContainer.backgroundColor = UIColor.clearColor;
    [self.view addSubview:hudContainer];
    
    [SVProgressHUD setForegroundColor: [UIColor colorWithRed:29.0/255 green:185.0/255 blue:84.0/255 alpha:1.0]];
    [SVProgressHUD setBackgroundColor: [UIColor clearColor]];
    [SVProgressHUD setContainerView:hudContainer];`

But hud is not showing in this view. 
Anyhelp?
