### ISSUE TITLE
I think '+showWithStatus: maskType:'  method shouldn't be instead by  '+setDefaultMaskType:'

### ISSUE THREAD

**Issue by mrxir** [SVProgressHUD/SVProgressHUD#768]
我觉得, 即使在添加了 '+setDefaultMaskType:' 方法之后, 原来的 '+showXXX: maskType:' 方法也应该被保留, 因为在同一个 App 的不同场景中, 个别情况需要单独的设置 maskType, 而其余情况则使用 default maskType即可. 因为我现在使用时就遇到了一个问题, 我设置了 default maskType 之后, 个别地方需要把 maskType 修改成另外一个 type, 可我还得再修改回来, 以免影响其他使用的地方. 谢谢.

**Comment by honkmaster** [comment]
Please add english description.

**Comment by mrxir** [comment]
If you can reserve both '+setDefaultMaskType' method and '+showXXX: maskType:' method, I think it's more convenient and flexible. Because sometimes I only want to use another mask type for this situation for one time, I don't want to change all mask type after this.
    Use '+showXXX:' and 'setDefaultMaskType' to instead '+showXXX: maskType:' is not very convenient, my English is not so good, wish you can understand it, thanks!

**Comment by yu243e** [comment]
SVProgressHUD.setDefaultMaskType(.custom)
SVProgressHUD.show()
//doSomething... ...
SVProgressHUD.setDefaultMaskType(.none)
SVProgressHUD.showSuccess(withStatus: LocalizedString(key: "information_upload_success"))
SVProgressHUD.dismiss(withDelay: 2, completion: {
    SVProgressHUD.setDefaultMaskType(.custom)
})
If I want to show diffrent mask type , I need to do something like above.

**Comment by honkmaster** [comment]
In general it is not a good idea to use different kind of masks.

**Comment by mrxir** [comment]
yeah, I hava the same feeling like you, but I still have this demand. Never mind, I can handle it, thank you~

**Comment by honkmaster** [comment]
Can this issue be closed?

**Comment by honkmaster** [comment]
Thanks. 👍
