### ISSUE TITLE
Set UIOffset in a view

### ISSUE THREAD

**Issue by Hearsayer** [SVProgressHUD/SVProgressHUD#774]
I want to HUD show in view, and set offset, e.g.:
```
SVProgressHUD.setContainerView(myView)
SVProgressHUD.setOffsetFromCenter(UIOffset(horizontal: 100, vertical: 100))
SVProgressHUD.show()
```
no any effect, it still stay in center. how to change?
look forward to your early reply, thank you!

**Comment by RomainQuidet** [comment]
same issue in swift, iOS10.3...

**Comment by RomainQuidet** [comment]
saw this PR : https://github.com/SVProgressHUD/SVProgressHUD/pull/738
why not yet included ?
