### ISSUE TITLE
The status label always showing light style.

### ISSUE THREAD

**Issue by wiliams-xu** [SVProgressHUD/SVProgressHUD#776]
I'm trying the iOS 11 beta version, I'm not sure it's iOS 11 bug. Just look at my screen shot, Thx.
OS: iOS 11
Device: iPhone 6 and Simulator iPhone 7.
![a5fdcce5-5bec-470c-968c-d136edda6833](https://user-images.githubusercontent.com/902272/27176394-ea7bc4dc-51f4-11e7-87c2-9a6d9d569b7a.png)

**Comment by honkmaster** [comment]
I think this is an issue with `UIVibrancyEffect` in iOS 11. The `UIVibrancyEffect` has different effects on images and labels, which should not be the case. Should we fill a radar or wait for the second beta.

**Comment by gongyuhonglou** [comment]
[SVProgressHUD setDefaultStyle:SVProgressHUDStyleDark];
I'm usering the iOS 9 version, The label always showing grayColor.
But in the iOS 10 version,The label showing whiteColor，is normal.
Device: iPhone 6 .
I want the label to be white. Is there any way?

**Comment by tangbing** [comment]
so do I,I'm usering the iOS 10.1 version, The label always showing grayColor.

**Comment by bulolo** [comment]
the same

**Comment by AndrewBennet** [comment]
Seems to still be the case with the iOS 11 beta included in Xcode 9 Beta 6.
However, the label looks correct on the appear and disappear animations, is only light grey in between.
