### ISSUE TITLE
GETTING WARNIG ON CUSTOM STYLE SVPROGRESS HUD 

### ISSUE THREAD

**Issue by amsunil** [SVProgressHUD/SVProgressHUD#779]
I'm getting following warning from svprogress hud pod
<UIVisualEffectView 0x13de22a30> is being asked to animate its opacity. This will cause the effect to appear broken until opacity returns to 1.

Im using Xcode 8.3.3

**Comment by losedMemory** [comment]
I have this problem, too

**Comment by shubh10** [comment]
Try this HUD library for iOS in swift https://github.com/shubh10/JustHUD
