### ISSUE TITLE
Option to attach to view so both can dismiss at the same time

### ISSUE THREAD

**Issue by timroesner** [SVProgressHUD/SVProgressHUD#783]
Steps to reproduce:
1. Go to view with SVProgressHUD
2. Progress spinner appears
3. Leave view before spinner is dismissed
4. Spinner will never disappear
---
Expected result:
1. Go to view with SVProgressHUD
2. Progress spinner appears
3. Leave view before spinner is dismissed
4. Spinner disappears with view

I know this can be achieved with dismissing the ProgressHUD in the viewWillDisappear method but I would prefer not doing that in every view that I am presenting a ProgressHUD. MBProgressView does offer this option for example, but they don't have a flat UI.

**Comment by honkmaster** [comment]
Thanks for this exemplary report. I will look into this, however, if you could provide a minimal demo project this would help alot and speed up the process as my time is very limited.

**Comment by timroesner** [comment]
Of course! Just use [timroesner/9to5Mac](http://github.com/timroesner/9to5Mac) as an example project. You can reproduce it when you back out of the article view before the spinner disappears.

**Comment by toohotz** [comment]
@timroesner would it be something like this that you are looking to achieve? I made this PR after running into a similar issue that you stated.
[https://github.com/SVProgressHUD/SVProgressHUD/pull/753](url)

**Comment by timroesner** [comment]
Yes exactly, if that PR isn't merged soon I'll just use your branch

**Comment by toohotz** [comment]
@timroesner Sure, I'll keep my fork updated with the master fork if / when my PR does get merged in

**Comment by timroesner** [comment]
@toohotz Thank you! I appreciate that, I'll be using your fork then

**Comment by honkmaster** [comment]
#753 is to cluttered for a single PR at the moment to be merged into the master.

**Comment by toohotz** [comment]
@honkmaster saw your message, I'll split them into two PRs, thanks.
