### ISSUE TITLE
GETTING WARNIG ON CUSTOM STYLE SVPROGRESS HUD

### ISSUE THREAD

**Issue by losedMemory** [SVProgressHUD/SVProgressHUD#785]
I'm getting following warning from svprogress hud pod <UIVisualEffectView 0x13de22a30> is being asked to animate its opacity. This will cause the effect to appear broken until opacity returns to 1.
Im using Xcode 8.3.3

**Comment by losedMemory** [comment]
[SVProgressHUD setDefaultStyle:SVProgressHUDStyleCustom];
    [SVProgressHUD setForegroundColor:[UIColor greenColor]];
    [SVProgressHUD setBackgroundLayerColor:[UIColor blueColor]];
  
Run result:  [Warning] <UIVisualEffectView 0x7f9509904530> is being asked to animate its opacity. This will cause the effect to appear broken until opacity returns to 1.

**Comment by honkmaster** [comment]
Should be fixed on the current master. Cocoapods release soon.
