### ISSUE TITLE
The user crashed while using the iOS8 jailbreak phone

### ISSUE THREAD

**Issue by dairuiquan** [SVProgressHUD/SVProgressHUD#789]
[<__NSArrayI 0x17001b640> valueForUndefinedKey:]: this class is not key value coding-compliant for the key gaussianBlur.
DingDangDai __28-[SVProgressHUD showStatus:]_block_invoke (SVProgressHUD.m:)

**Comment by honkmaster** [comment]
This is might due to the jailbreak itself, thus I will not fix this issue.
