### ISSUE TITLE
HUD not displaying when setting background / foreground color

### ISSUE THREAD

**Issue by toohotz** [SVProgressHUD/SVProgressHUD#791]
Starting on commit *002afe53 Animation changes (Blur, iOS 7)* the ability to change the HUD color is not working due to the setting of the alpha state on the `contentView` of the HUD.  I made a fix for this on branch as I needed it for a store release but I wanted to know @honkmaster if you will be fixing this as I have a PR outstanding already and do not want to tie this bugfix into it. Thanks.

**Comment by fanpyi** [comment]
I met the same problem, but release version 2.1.2 work good.
