### ISSUE TITLE
Foreground color issue

### ISSUE THREAD

**Issue by AnkitaJoshi110** [SVProgressHUD/SVProgressHUD#792]
Hello, 
I'm getting issue in foreground color i.e. ring color. I'm setting forground color #01eba5, so as per expectation i should get #01eba5 color, but instead of that color i'm getting another color. Here is code.

SVProgressHUD.setDefaultStyle(.custom)
SVProgressHUD.setDefaultMaskType(.custom)
SVProgressHUD.setMinimumSize(CGSize(width: 60, height: 60))
SVProgressHUD.setRingThickness(2.7)
SVProgressHUD.setRingNoTextRadius(20)
SVProgressHUD.setBackgroundLayerColor(UIColor.init(colorLiteralRed: 0, green: 0, blue: 0, alpha: 0.05))
SVProgressHUD.setBackgroundColor(UIColor.white)
SVProgressHUD.setForegroundColor(UIColor.init(colorLiteralRed: 1.0/255.0, green: 235.0/255.0, blue: 165.0/255.0, alpha: 1.0))

I'm getting this color:
https://www.screencast.com/t/mjxiE5W1mHP

**Comment by lytes20** [comment]
Hello AnkitaJoshi110, the code u have is the correct, the color you entered is the right color it's returning. Maybe for more about color codes, you can visit color palette websites, an example website you can visit is http://www.color-hex.com/color-palettes/

**Comment by honkmaster** [comment]
Should be fixed on the current master. Cocoapods release soon.
