### ISSUE TITLE
New Cocoapods Release

### ISSUE THREAD

**Issue by Vortec4800** [SVProgressHUD/SVProgressHUD#796]
Can you create a new release version with all the recent changes? The last one was from late last year, and I'd much prefer to use a numbered release instead of just pointing to the head of the repository. Plus having a release here before potential iOS 11 changes may be useful at some point.

**Comment by honkmaster** [comment]
![a-cat-in-the-toilet-soon-meme](https://user-images.githubusercontent.com/1380397/30137225-a6f408a0-9362-11e7-8716-824777e2195b.jpg)

**Comment by honkmaster** [comment]
Check 2.2.
