### ISSUE TITLE
tvOS HUD moving when showing after a swipe on remote

### ISSUE THREAD

**Issue by LucasAdam** [SVProgressHUD/SVProgressHUD#797]
Hi, 

I experience a small movement of the HUD on screen when I call the .show function right after a swipe / gesture on the Siri Remote. Is there any way I can get rid of this ?

**Comment by honkmaster** [comment]
I currently have no AppleTV on hand, in Simulator I can not reproduce the issue. However, this might be an issue of the "software remote".
