### ISSUE TITLE
iOS 11 beta 9 bug - When the style is SVProgressHUDStyleLight, the statusLabel is white text

### ISSUE THREAD

**Issue by wenbobao** [SVProgressHUD/SVProgressHUD#798]
Hi @honkmaster : 
iOS 11 beta 9, 
When the style is SVProgressHUDStyleLight, the statusLabel is white text . it should be black text.
<img width="123" alt="qq20170904-174428 2x" src="https://user-images.githubusercontent.com/10412011/30021269-614c79f6-9199-11e7-948e-ea20b62be1a2.png">

```
+ (void)showProgressHUDWithTitle:(NSString *)title {
    [SVProgressHUD showWithStatus:title];
    [SVProgressHUD setDefaultMaskType:SVProgressHUDMaskTypeBlack];
}
```

**Comment by honkmaster** [comment]
Should be fixed on the current master. Cocoapods release soon.
