### ISSUE TITLE
crash NSUnknownKeyException [<__NSArrayI 0x17401c090> valueForUndefinedKey:]: this class is not key value coding-compliant for the key gaussianBlu

### ISSUE THREAD

**Issue by dairuiquan** [SVProgressHUD/SVProgressHUD#799]
CoreFoundation | ___exceptionPreprocess + 132
-- | --
1 libobjc.A.dylib | objc_exception_throw + 60
2 CoreFoundation | -[NSException init]
3 Foundation | -[NSObject(NSKeyValueCoding) valueForUndefinedKey:] + 276
4 QuartzCore | 0x0000000186b70000 + 275440
5 QuartzCore | 0x0000000186b70000 + 95352
6 UIKit | 0x0000000187218000 + 4885036
7 UIKit | 0x0000000187218000 + 4889680
8 UIKit | 0x0000000187218000 + 4889292
9 DingDangDai | __28-[SVProgressHUD showStatus:]_block_invoke (SVProgressHUD.m:880)
10 UIKit | 0x0000000187218000 + 282784
11 UIKit | 0x0000000187218000 + 380144
12 DingDangDai | -[SVProgressHUD showStatus:] (SVProgressHUD.m:919)
13 DingDangDai | __43-[SVProgressHUD showImage:status:duration:]_block_invoke (SVProgressHUD.m:832)
14 Foundation | ___NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 16
15 Foundation | -[NSBlockOperation main] + 96
16 Foundation | -[__NSOperationInternal _start:] + 636
17 Foundation | ___NSOQSchedule_f + 228
18 libdispatch.dylib | __dispatch_client_callout + 16
19 libdispatch.dylib | _dispatch_main_queue_callback_4CF + 932
20 CoreFoundation | ___CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 12
21 CoreFoundation | ___CFRunLoopRun + 1492
22 CoreFoundation | CFRunLoopRunSpecific + 396
23 GraphicsServices | GSEventRunModal + 168
24 UIKit | UIApplicationMain + 1488
25 DingDangDai | main (main.m:19)
26 libdyld.dylib | 0x0000000193838000 + 10760

**Comment by honkmaster** [comment]
More details? iOS Version etc.?

**Comment by dairuiquan** [comment]
Crash back on iOS8,not other information。 I like this Hud, but crash is more than 80.  I hope to solve it in the next release. Thank you!

**Comment by honkmaster** [comment]
I think it is the same as #533. It is a iOS 8 internal error.

**Comment by dairuiquan** [comment]
Thanks for answering my question.
