### ISSUE TITLE
SVprogressHud ring Color

### ISSUE THREAD

**Issue by usman1057** [SVProgressHUD/SVProgressHUD#800]
Hello everyone
I now this issue posted more times but i have not fix my issue. In my case foregroundColor is not working. Ring is not appear with darkGray color even that foregroundColor not pick any color. Please View my code and help me. Thanks 
import SVProgressHUD
       
        SVProgressHUD.setDefaultStyle(.custom)
        SVProgressHUD.setDefaultMaskType(.custom)
        SVProgressHUD.setMinimumSize(CGSize(width: 60, height: 60))
        SVProgressHUD.setRingThickness(3)
        SVProgressHUD.setRingNoTextRadius(20)
        SVProgressHUD.setBackgroundColor(UIColor.white)
        SVProgressHUD.setForegroundColor(UIColor.darkGray)
        SVProgressHUD.show()

please see attached Image.
<img width="375" alt="screen shot 2017-09-06 at 3 29 07 pm" src="https://user-images.githubusercontent.com/18173257/30107436-337723b6-9318-11e7-9ec6-ed29c5acbee5.png">

**Comment by honkmaster** [comment]
Acknowledged. Fixing now.

**Comment by usman1057** [comment]
Its fixed with update SVProgressHud Pod. Can I set borderColor around white layer in above screen shot. If yes than how can I. Thanks
