### ISSUE TITLE
Progress flickers when updates come too fast

### ISSUE THREAD

**Issue by mickeyl** [SVProgressHUD/SVProgressHUD#801]
I'm using SVProgressHUD to show progress loading from net. On fast connections, I emit a lot of update calls to the progress value, which lead to severe flickering. Is there something we can do about it in SVProgressHUD? I.e. how about a) either doing a slight debounce by delaying the actual animation hence a newer update makes the older update be silently dropped or b) change the animation target "in-flight".

**Comment by honkmaster** [comment]
b) would be the best solution. What is the update rate in your application? We had a similar issue with #415 and #386 and from my recollection it was fixed. Can you provide a demo project?

**Comment by honkmaster** [comment]
b) would be the best solution. What is the update rate in your application? We had a similar issue with #415 and #386 and from my recollection it was fixed. Can you provide a demo project?

**Comment by mickeyl** [comment]
I'm sorry, apparently I was working with a version prior to the fixes applied in #415 and #386. The latest code does not show any problems. Thanks for responding so fast!

**Comment by honkmaster** [comment]
Keine Ursachen.
