### ISSUE TITLE
`setContainerView:` parameter should be `nullable`

### ISSUE THREAD

**Issue by charliewilliams** [SVProgressHUD/SVProgressHUD#802]
In 2.2 the UIView passed into `+ (void)setContainerView:` changed its nullability specifier to `nonnull`. However, the containerView property is `nullable`:

`@property (strong, nonatomic, nullable) UIView *containerView; `

And a comment specifies `// default is window level`, indicating that it is valid to have a `nil` value here.

Proposal: change to

```+ (void)setContainerView:(nullable UIView*)containerView;```

**Comment by honkmaster** [comment]
Please submit a PR.

**Comment by charliewilliams** [comment]
https://github.com/SVProgressHUD/SVProgressHUD/pull/803

**Comment by honkmaster** [comment]
Thanks.
