### ISSUE TITLE
setRingRadius and showProgress with status has bug

### ISSUE THREAD

**Issue by balkarov** [SVProgressHUD/SVProgressHUD#806]
setRingRadius and showProgressStatus has small circle

**Code:**
`[SVProgressHUD setRingRadius:1.0];`
`[SVProgressHUD showProgress:progress status:@"Loading..."];`

**Result:**
![simulator screen shot 16 2017 12 17 43](https://user-images.githubusercontent.com/6030335/30511028-19248e54-9ad9-11e7-8a6e-3dc7bdac1a47.png)

**Comment by honkmaster** [comment]
You set the radius to 1px. What did you expect?

**Comment by balkarov** [comment]
Without show progress with status circle show normal.
