### ISSUE TITLE
iOS 11, transparent bug

### ISSUE THREAD

**Issue by LvJianfeng** [SVProgressHUD/SVProgressHUD#807]
The prompt text is transparent bug

**Comment by honkmaster** [comment]
![simulator screen shot - iphone x - 2017-09-21 at 18 47 37](https://user-images.githubusercontent.com/1380397/30707950-5c7473c2-9efd-11e7-860c-55c44bfa1167.png)

What do you mean by transparent?

**Comment by hoferdan** [comment]
I think he has the same problem/bug that i do.
The text looks like this on iOS 11:
![img_e4360](https://user-images.githubusercontent.com/7467442/30792380-386398ae-a1ba-11e7-9e6e-1d28da52bd42.JPG)

**Comment by honkmaster** [comment]
This bug was fixed 2 weeks or so ago. Please look at my screenshot where it looks as expected. Please use the latest release.
