### ISSUE TITLE
IOS 11 text flash become transparent

### ISSUE THREAD

**Issue by kshipeng** [SVProgressHUD/SVProgressHUD#808]
IOS 11 text flash become transparent.

**Comment by hellensoloviy** [comment]
not only in iOS 11. I have the same issue after update to 2.2.1 (was 2.1.2) at all devices and iOS versions

**Comment by honkmaster** [comment]
What do you mean by text flash?

**Comment by PowerYang** [comment]
this bug how to fix?

**Comment by honkmaster** [comment]
Can you give a screenshot?

**Comment by kshipeng** [comment]
[screenVideo.mp4.zip](https://github.com/SVProgressHUD/SVProgressHUD/files/1328720/1506327486.mp4.zip)
@honkmaster

**Comment by honkmaster** [comment]
This issue must be fixed with the latest release (see #807).

**Comment by kshipeng** [comment]
![pod](https://user-images.githubusercontent.com/18022364/30799569-db6c85ce-a20f-11e7-8900-7bd20d5893e4.png)
`pod search SVProgressHUD`

**Comment by honkmaster** [comment]
The latest release is 2.2.1. You are using 2.1.2, which is outdated.

**Comment by kshipeng** [comment]
Thank you for your reply.But the version I've searched with CocoaPods is 2.1.2, no higher version.You try using CocoaPods to search it.

**Comment by honkmaster** [comment]
I tried... Update your local repo. 

![screen shot 2017-09-25 at 11 10 15](https://user-images.githubusercontent.com/1380397/30800820-93f018c4-a1e1-11e7-9a54-d3372773088b.png)

![screen shot 2017-09-25 at 11 02 55](https://user-images.githubusercontent.com/1380397/30800536-9b822cfe-a1e0-11e7-890a-605acdfe7bf6.png)

**Comment by kshipeng** [comment]
Thank you. The problem has been settled.
`pod repo update`Then`pod search svprogresshud`

**Comment by kshipeng** [comment]
Could you tell me what caused the problem? On iOS 11

**Comment by honkmaster** [comment]
Look into the code.
