### ISSUE TITLE
[SVProgressHUD show] does not display 

### ISSUE THREAD

**Issue by SionChen** [SVProgressHUD/SVProgressHUD#809]
iOS11 xcode 9 at the time of page jump In jump target page viewdidload method perform [SVProgressHUD show] does not display

**Comment by xuhongfei** [comment]
[SVProgressHUD show] , I found the view under the display view which show my control. But i can not find the way to resolve it.

**Comment by SionChen** [comment]
Execute [SVProgressHUD show]  after VC viewDidAppeaer  is  display. So, How to solve this

**Comment by CaiWanFeng** [comment]
@SionChen  try this in viewdidload:
dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(0.1 * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
     [SVProgressHUD show];
});

**Comment by apptasklpaco** [comment]
There is a change that SVProgressHUD not showing when using UIAlertView, deprecated in iOS8, as a popup an alert. 
Step:
1. [SVProgressHUD show] ;
2. [UIAlertView show];
or 
1. [UIAlertView show];
2. [SVProgressHUD show] ;

Example: [https://github.com/apptasklpaco/SVProgressHUDNotShowing](https://github.com/apptasklpaco/SVProgressHUDNotShowing)

**Comment by HaloWang** [comment]
Some issue
```Objective-C
CGFloat second = 0.3;
dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t) (second * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
    [SVProgressHUD show];
});
```
`second = 0.2` is not work but `second = 0.3` is work for me.
