### ISSUE TITLE
Show HUD without image and only text

### ISSUE THREAD

**Issue by ydms** [SVProgressHUD/SVProgressHUD#811]
Want a text-only method that disappears later, with the default animation circle, or without, can you have it?
想要一个纯文本的稍后消失的方法，带默认的动画圆圈，或者不带，可以有吗？

What if you customize it? Is anyone there?
如果自定义该如何做呢？有人吗？

**Comment by honkmaster** [comment]
Text only is not supported at the moment, however a pull request is warmly welcome.

**Comment by ydms** [comment]
@honkmaster 
Like Showsuccess, Showinfo, no icons, just text, okay?

**Comment by honkmaster** [comment]
jep.

**Comment by ydms** [comment]
？？

**Comment by trunghvbk** [comment]
you can use SVProgressHUD.setImageViewSize(.zero), it's worked

**Comment by 520** [comment]
> you can use SVProgressHUD.setImageViewSize(.zero), it's worked

Its just worked, not perfectly, I can see a margin beyond the label
