### ISSUE TITLE
Not Showing HUD

### ISSUE THREAD

**Issue by syedrazackimran** [SVProgressHUD/SVProgressHUD#812]
I have ViewControllers RootVC, Login, SignUp and Verify. RootVC I customize Some Property HUD
       `SVProgressHUD.setFadeInAnimationDuration(0.5)`
        `SVProgressHUD.setFadeOutAnimationDuration(0.5)`
        `SVProgressHUD.setDefaultStyle(SVProgressHUDStyle.light)`
        `SVProgressHUD.setFont(UIFont(name: FontName.Medium, size: 14)!)`
        `SVProgressHUD.setContainerView(view)`
        `SVProgressHUD.setDefaultMaskType(.clear)`

RootVC inherits with all ViewController I create some method!

<img width="522" alt="screen shot 2017-09-21 at 4 52 08 pm" src="https://user-images.githubusercontent.com/15051045/30690088-3ca95a4a-9eed-11e7-89aa-e12cf0fda5ad.png">
 
On SignUp VC i'm showing `SVProgressHUD.show(withStatus: message)` without dismiss i go to verfiyVC there i'm showing `SVProgressHUD.showInfo(withStatus: message) `

The problem is without dismissing! another HUD can't be showing! so kindly give some solution

**Comment by honkmaster** [comment]
For me your wanted behaviour is working without a dismiss. 

![sep-21-2017 18-50-23](https://user-images.githubusercontent.com/1380397/30708054-bd63d574-9efd-11e7-859e-6760382795ff.gif)

**Comment by honkmaster** [comment]
Any feedback?

**Comment by apptasklpaco** [comment]
There is a conflict when using UIAertView and SVProgressHUD at the same time.

**Comment by honkmaster** [comment]
@apptasklpaco What has `UIAlertView` to do with this issue?
