### ISSUE TITLE
SVProgressHUD calling UIKit API from background thread

### ISSUE THREAD

**Issue by deepumukundan** [SVProgressHUD/SVProgressHUD#814]
UIKit API's should be only called from main thread in Xcode 9.
SVProgressHUD seems to be triggering warnings from Xcode 9 Main thread checker about usage of UIView.bounds

Main Thread Checker: UI API called on a background thread: -[UIView bounds]
PID: 50136, TID: 687479, Thread name: (none), Queue name: com.apple.root.default-qos, QoS: 21
Backtrace:
4   SVProgressHUD                       0x0000000104fd5798 __27+[SVProgressHUD sharedView]_block_invoke + 137
5   libdispatch.dylib                   0x000000010d1cc43c _dispatch_client_callout + 8
6   libdispatch.dylib                   0x000000010d1cd9c7 dispatch_once_f + 297
7   SVProgressHUD                       0x0000000104fd570d +[SVProgressHUD sharedView] + 102
8   SVProgressHUD                       0x0000000104fd5e07 +[SVProgressHUD setBackgroundColor:] + 52

**Comment by yarodevuci** [comment]
I have the same issue

**Comment by endlessLetter** [comment]
I have the same issue

**Comment by yarodevuci** [comment]
why was this closed? what is the solution?
