### ISSUE TITLE
crash log

### ISSUE THREAD

**Issue by cj768025549** [SVProgressHUD/SVProgressHUD#818]
This is the crash log that I got from fabric.

SVProgressHUD.m line 1268
-[SVProgressHUD hudView]
Fatal Exception: NSRangeException
*** -[__NSArrayM removeObjectsInRange:]: range {1, 1} extends beyond bounds [0 .. 0]

**Comment by cj768025549** [comment]
ps:iOS 10.3.3

**Comment by honkmaster** [comment]
Do you have more details?
