### ISSUE TITLE
Questions about iOS 11 play window does not display！

### ISSUE THREAD

**Issue by liss1990** [SVProgressHUD/SVProgressHUD#819]
Excuse me, iOS11 adapter is there a problem?Why am I in the main thread, the hud will not play out?Other versions of the can?Please help me.thank you

**Comment by BBHNation** [comment]
In iOS 11 & Swift 4, there is a problem with the progress view's alpha,
![img_e7d5069591f4-1](https://user-images.githubusercontent.com/9971257/30950886-360387d2-a452-11e7-83aa-8fd848a750cd.jpeg)

**Comment by liss1990** [comment]
不是这样的！连系统的alert 都不弹出来了！

**Comment by honkmaster** [comment]
Do you use the current version?

**Comment by D-james** [comment]
same question,last version2.2.1

**Comment by qpc2015** [comment]
我的也有这个问题

**Comment by qpc2015** [comment]
你的问题升级到最新版就没问题了 @BBHNation

**Comment by BBHNation** [comment]
谢谢提醒！@qpc2015

**Comment by noname004** [comment]
楼主的问题是不是和我提出的那个“ 2.2.1 windowLevel BUG ”是同一个情况？？

**Comment by honkmaster** [comment]
Please write in English.

**Comment by JermeryLee** [comment]
in iOS11 UIAlertViewDelegate(clickedButtonAtIndex:) does not display

**Comment by honkmaster** [comment]
@JermeryLee This component is not `UIAlertView` thus the delegate method is of course not firing 😐.

**Comment by JermeryLee** [comment]
but iOS11 lowser can be display in clickedButtonAtIndex: method.

**Comment by apptasklpaco** [comment]
There is a change that SVProgressHUD not showing when using UIAlertView, deprecated in iOS8, as a popup an alert.
Step:

1. [SVProgressHUD show] ;
2. [UIAlertView show];
or
1. [UIAlertView show];
2. [SVProgressHUD show] ;
Example: [There is a change that SVProgressHUD not showing when using UIAlertView, deprecated in iOS8, as a popup an alert.
Step:

[SVProgressHUD show] ;
[UIAlertView show];
or
[UIAlertView show];
[SVProgressHUD show] ;
Example: https://github.com/apptasklpaco/SVProgressHUDNotShowing](https://github.com/apptasklpaco/SVProgressHUDNotShowing)

**Comment by honkmaster** [comment]
UIAlertView is deprecated, we can not deal with thus issue.
