### ISSUE TITLE
Swift 4 compatibility?

### ISSUE THREAD

**Issue by ethanwa** [SVProgressHUD/SVProgressHUD#820]
Is this library fully Swift 4 compatible? If not, is it on the roadmap? Thanks!

**Comment by honkmaster** [comment]
I am using the library right now with a bridging header in a Swift 4 project.

**Comment by ethanwa** [comment]
I am using it as well, but my Pod project for it is set to Swift 3.2. Can I set it to 4.0 and not run into issues?

**Comment by honkmaster** [comment]
Sure. BTW: Why so afraid? Just try it out. If you use version management you can always go back to the previous version.
