### ISSUE TITLE
ios11 crash:  Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[NSBundle initWithURL:]: nil URL argument' *** First throw call stack:

### ISSUE THREAD

**Issue by 2360219637** [SVProgressHUD/SVProgressHUD#827]
0   CoreFoundation                      0x000000010e6111cb __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x000000010df73f41 objc_exception_throw + 48
	2   CoreFoundation                      0x000000010e685b95 +[NSException raise:format:] + 197
	3   Foundation                          0x000000010d97e2b9 -[NSBundle initWithURL:] + 87
	4   Foundation                          0x000000010d97e24f +[NSBundle bundleWithURL:] + 45
	5   Test                                0x000000010d643d93 -[SVProgressHUD initWithFrame:] + 1107
	6   Test                                0x000000010d641847 __27+[SVProgressHUD sharedView]_block_invoke + 263
	7   libdispatch.dylib                   0x000000011291e43c _dispatch_client_callout + 8
	8   libdispatch.dylib                   0x000000011291f9c7 dispatch_once_f + 297
	9   Test                                0x000000010d641718 +[SVProgressHUD sharedView] + 136
	10  Test                                0x000000010d6430a2 +[SVProgressHUD showErrorWithStatus:] + 66
	11  Test                                0x000000010d652cfd -[ViewController viewDidLoad] + 381

**Comment by 2360219637** [comment]
错误描述：我再viewDIdload方法中使用：[SVProgressHUD showErrorWithStatus:@"错误"];就crash了

**Comment by datwelk** [comment]
From the `README`: "Take care that SVProgressHUD.bundle is added to Targets->Build Phases->Copy Bundle Resources"

**Comment by honkmaster** [comment]
Thanks Damiaan.

**Comment by surbhivarma90** [comment]
I have used the Pods to install SVProgressHUD, an facing this issue.
Please suggest.

**Comment by MHamayun** [comment]
Jazakallah thanks...
