### ISSUE TITLE
After setting graceTimeInterval, dismiss(withDelay:) will not work correctly

### ISSUE THREAD

**Issue by superk589** [SVProgressHUD/SVProgressHUD#828]
I have created a demo project for this issue:
https://github.com/superk589/SVProgressHUDGraceAndDismissIssue

When use ```SVProgressHUD.setGraceTimeInterval()``` before```SVProgressHUD.dismiss(withDelay:)``` will cause it not working correctly. The hud will never show.
```Swift
        SVProgressHUD.setGraceTimeInterval(0.5)
        SVProgressHUD.show(withStatus: "This is a test")
        SVProgressHUD.dismiss(withDelay: 3)
```

However, using GCD like this way, the hud will work correctly.
```Swift 
        SVProgressHUD.setGraceTimeInterval(0.5)
        SVProgressHUD.show(withStatus: "This is a test")
        DispatchQueue.main.asyncAfter(deadline: .now() + 3) {
            SVProgressHUD.dismiss()
        }
```

So, I think there is something wrong in ```SVProgressHUD.dismiss(withDelay:)```.
Sorry for that I have not read the source code carefully. If this is not a bug, I'll close this issue.

**Comment by rpendleton** [comment]
Calling the dismiss method immediately sets the graceTimer to nil which causes the HUD to never appear. Fixing this might be as simple as setting the graceTimer to nil inside the dispatch_after instead.

**Comment by honkmaster** [comment]
A PR is always warmly welcome.

**Comment by devcatin** [comment]
[SVProgressHUD setMinimumDismissTimeInterval:3.0];
[SVProgressHUD setMaximumDismissTimeInterval:3.0];
设置这两个时间无效,求解

**Comment by RenChuanChuan** [comment]
If this problem is solved, please let me know.；）
