### ISSUE TITLE
SVProgressHUD auto dismiss - When navigating to an Viewcontroller from Sidemenu

### ISSUE THREAD

**Issue by aromal-sasidharan** [SVProgressHUD/SVProgressHUD#830]
I am using [Sidemenu](https://github.com/jonkykong/SideMenu)  in my project. The problem is that SVProgressHUD gets **auto dismissed when loading a Viewcontroller(has SVProgressHUD in it)** from Sidemenu. 
_Please let me know what went wrong._
[Here](https://github.com/Code-Snippets-IOS/SIdeMenuSVProgressTest) is a sample project to demonstrate the issue

**Comment by aromal-sasidharan** [comment]
Please help!!

**Comment by honkmaster** [comment]
I can only help with issues directly related to SVProgressHUD.
