### ISSUE TITLE
Text overlap

### ISSUE THREAD

**Issue by Mr-Cannon** [SVProgressHUD/SVProgressHUD#832]
When I pop up, there is text overlap

**Comment by Mr-Cannon** [comment]
@dennisreimann

**Comment by honkmaster** [comment]
Hi guys. Any more details? Screenshot etc.?

**Comment by Mr-Cannon** [comment]
![img_0740](https://user-images.githubusercontent.com/23579664/32527387-64826540-c3f3-11e7-9c3d-34cee5d1c6bb.PNG)

**Comment by Mr-Cannon** [comment]
This overlap occurs in Chinese.I didn't find it in English

**Comment by Mr-Cannon** [comment]
![img_0744](https://user-images.githubusercontent.com/23579664/32528731-43d5df78-c3fa-11e7-84e5-2388c44bb37b.PNG)
<img width="866" alt="359661c4-c7a0-4789-92c4-d175a95e4acc" src="https://user-images.githubusercontent.com/23579664/32528735-4c78cbd6-c3fa-11e7-9e6a-89a67912a6c2.png">

**Comment by XuWisp** [comment]
字体重叠问题解决了吗? 我也遇到了同样的问题, 望告知!
Has the problem of overlapping fonts been solved? I have the same problem, please let me know!

**Comment by zhuyuping** [comment]
I have a same issue~~

**Comment by Vi-jay** [comment]
same issue

**Comment by Vi-jay** [comment]
i changed UILabel backgroundColor to fixed issue

**Comment by 623034345** [comment]
我也遇到了这个问题
I also encountered this problem.
