### ISSUE TITLE
iOS 11: HUD is not centered

### ISSUE THREAD

**Issue by cherpake** [SVProgressHUD/SVProgressHUD#835]
On iOS 11 HUD is not centered... iOS 11 vs iOS 10

![10 3](https://user-images.githubusercontent.com/876484/32695886-70f59a2e-c770-11e7-91d8-82047544a09f.png)
![11 2](https://user-images.githubusercontent.com/876484/32695887-71162ed8-c770-11e7-90c1-35b09ed12692.png)

**Comment by sbdk** [comment]
Same issue for me. Noticed this issue after I updated my phone to 11.2

**Comment by MaxiHuber** [comment]
+1 Same problem here. Very annoying.

**Comment by RajanMaheshwari** [comment]
+1 Same problem after updating to iOS 11.2. Any solution to this?

**Comment by bembem1011** [comment]
+1

**Comment by NikolayDmitrievRally** [comment]
+1

**Comment by zqzal** [comment]
+1

**Comment by abilashblnair** [comment]
+1

**Comment by sokalyambda** [comment]
+1

**Comment by valabal** [comment]
+1

**Comment by cherpake** [comment]
Eventually to stop receiving this I’m going to fork it and fix it ;)

**Comment by SonnyMore** [comment]
+1

**Comment by honkmaster** [comment]
Should be fixed by the recent merge of @juliensaad.

**Comment by NeerajKumar123** [comment]
+1

**Comment by fukemy** [comment]
still not fixed

**Comment by hitendradeveloper** [comment]
+1

**Comment by TwoMinNap** [comment]
+1

**Comment by TwoMinNap** [comment]
Follow this guys : https://github.com/SVProgressHUD/SVProgressHUD/pull/846

**Comment by borzh** [comment]
Check out the new one: #1050
