### ISSUE TITLE
MinimumDismissTimeInterval

### ISSUE THREAD

**Issue by inPhilly** [SVProgressHUD/SVProgressHUD#836]
I created a hud with this code:
        [SVProgressHUD showWithStatus:statusString];
        [SVProgressHUD setMinimumDismissTimeInterval:10.0];
    
Sometime later I called:
        [SVProgressHUD dismiss];

The MinimumDismissTimeInterval is completely ignored and the hud dismisses almost immediately, when the work is don't very quickly. Am I misusing this, or is there an issue?

**Comment by inPhilly** [comment]
Anyone? Any thoughts on this?

**Comment by forbidden404** [comment]
I'm getting similar problems, calling SVProgress.show() in a Swift 4 Xcode 9.2 application is being dismissed almost instantly, even thought the call to SVProgress.dismiss() hasn't happened yet.

**Comment by phoney** [comment]
@inPhilly setMinimumDismissTimeInterval is only related to showSuccess(). In that case the Success HUD appears and then goes away after the dismissTimeInterval. When you showWithStatus() the HUD goes away when you dismiss(). What you're observing is the correct behavior.

**Comment by honkmaster** [comment]
@phoney is right.
