### ISSUE TITLE
Inconsistent frame when using setContainerView (Swift)

### ISSUE THREAD

**Issue by HackShitUp** [SVProgressHUD/SVProgressHUD#841]
The following method in my XIB class doesn't set the frame properly:
``` swift
SVProgressHUD.setContainerView(self.imageView)
SVProgressHUD.setForegroundColor(UIColor.blue)
SVProgressHUD.show()
```

**Comment by honkmaster** [comment]
Please provide a demo project.

**Comment by Ericji1989114** [comment]
yes when i used autolayout to set a small view in my screen.
i can not add SVProgressHUD to my small view.
i think it is a problem.
it seems not to support autolayout.

**Comment by zapjonny** [comment]
I see this too. I assume also that SVProgressHUD does not account for autolayout, OR just simply always use centering visavi the whole screen as opposed to the set container view. Or some mix of that.

**Comment by zapjonny** [comment]
I had a fairly simple UI this time and was able to workaround it for now by using an offset for the indicator.
