### ISSUE TITLE
Is it possible to reposition SVProgressHUD?

### ISSUE THREAD

**Issue by NoorinHasan** [SVProgressHUD/SVProgressHUD#843]
Is it possible to reposition SVProgressHUD? Instead of having it appear in the centre of the view, have it appear at the right/left of the view. Basically, I have a UIImageView added as a subview at the left of the screen and I want SVProgressHUD to spin at the centre of the UIIMageView rather than have it spin at the centre of the view?

**Comment by honkmaster** [comment]
You can use `offsetFromCenter`.
