### ISSUE TITLE
hudView is not centered

### ISSUE THREAD

**Issue by xiasanlan** [SVProgressHUD/SVProgressHUD#845]
- (CGFloat)visibleKeyboardHeight {
#if !defined(SV_APP_EXTENSIONS)
    UIWindow *keyboardWindow = nil;
    for (UIWindow *testWindow in UIApplication.sharedApplication.windows) {
        if(![testWindow.class isEqual:UIWindow.class]) {
            keyboardWindow = testWindow;
            break;
        }
    }
    
    for (__strong UIView *possibleKeyboard in keyboardWindow.subviews) {
        NSString *viewName = NSStringFromClass(possibleKeyboard.class);
        if([viewName hasPrefix:@"UI"]){
            if([viewName hasSuffix:@"PeripheralHostView"] || [viewName hasSuffix:@"Keyboard"]){
                return CGRectGetHeight(possibleKeyboard.bounds);
            } else if ([viewName hasSuffix:@"InputSetContainerView"]){
                for (__strong UIView *possibleKeyboardSubview in possibleKeyboard.subviews) {
                    viewName = NSStringFromClass(possibleKeyboardSubview.class);
                    if([viewName hasPrefix:@"UI"] && [viewName hasSuffix:@"InputSetHostView"]) {
                        return CGRectGetHeight(possibleKeyboardSubview.bounds);
                    }
                }
            }
        }
    }
#endif
    return 0;
}

This method return 216 run as iOS 11.2.  It causes the view to not be in the middle.

**Comment by JimHowell20** [comment]
Same issue here

**Comment by kwGao** [comment]
me too, please help me, thanks

**Comment by xiasanlan** [comment]
- (CGFloat)visibleKeyboardHeight {
#if !defined(SV_APP_EXTENSIONS)
    UIWindow *keyboardWindow = nil;
    for (UIWindow *testWindow in [[UIApplication sharedApplication] windows]) {
        #ifdef __IPHONE_11_2
            if([[testWindow class] isEqual:NSClassFromString(@"UIRemoteKeyboardWindow")]) {
                keyboardWindow = testWindow;
                break;
            }
        #else
            if(![[testWindow class] isEqual:[UIWindow class]]){
                keyboardWindow = testWindow;
                break;
            }
        #endif
    }
    
    for (__strong UIView *possibleKeyboard in [keyboardWindow subviews]) {
        if([possibleKeyboard isKindOfClass:NSClassFromString(@"UIPeripheralHostView")] || [possibleKeyboard isKindOfClass:NSClassFromString(@"UIKeyboard")]) {
            return CGRectGetHeight(possibleKeyboard.bounds);
        } else if([possibleKeyboard isKindOfClass:NSClassFromString(@"UIInputSetContainerView")]) {
            for (__strong UIView *possibleKeyboardSubview in [possibleKeyboard subviews]) {
                if([possibleKeyboardSubview isKindOfClass:NSClassFromString(@"UIInputSetHostView")]) {
                    return CGRectGetHeight(possibleKeyboardSubview.bounds);
                }
            }
        }
    }
#endif
    return 0;
}

**Comment by xiasanlan** [comment]
@kwGao replace this method

**Comment by kwGao** [comment]
@xiasanlan I tried, but this Hud was not displayed on the window

**Comment by kwGao** [comment]
@xiasanlan I tried the method you had before, but the view was not displayed in the window, so I tried to change your method, maybe some help：
- (CGFloat)visibleKeyboardHeight {
#if !defined(SV_APP_EXTENSIONS)
    UIWindow *keyboardWindow = nil;
    for (UIWindow *testWindow in UIApplication.sharedApplication.windows) {
        if (@available(iOS 11.0, *)) {
            if([testWindow.class isEqual:NSClassFromString(@"UIRemoteKeyboardWindow")]) {
                keyboardWindow = testWindow;
                break;
            }
        } else {
            if(![testWindow.class isEqual:UIWindow.class]) {
                keyboardWindow = testWindow;
                break;
            }
        }
    }
    
    for (__strong UIView *possibleKeyboard in keyboardWindow.subviews) {
        NSString *viewName = NSStringFromClass(possibleKeyboard.class);
        if([viewName hasPrefix:@"UI"]){
            if([viewName hasSuffix:@"PeripheralHostView"] || [viewName hasSuffix:@"Keyboard"]){
                return CGRectGetHeight(possibleKeyboard.bounds);
            } else if ([viewName hasSuffix:@"InputSetContainerView"]){
                for (__strong UIView *possibleKeyboardSubview in possibleKeyboard.subviews) {
                    viewName = NSStringFromClass(possibleKeyboardSubview.class);
                    if([viewName hasPrefix:@"UI"] && [viewName hasSuffix:@"InputSetHostView"]) {
                        return CGRectGetHeight(possibleKeyboardSubview.bounds);
                    }
                }
            }
        }
    }
#endif
    return 0;
}

**Comment by honkmaster** [comment]
Could you please check the PR #846 and give feedback. I have very limited time, PR and feedback on those thus helps the most.

**Comment by xiasanlan** [comment]
@honkmaster  I checked the PR #846.It works very well.

**Comment by ashokkumarmw** [comment]
I'm not using any keyboard, but the issue is still there. Using Xcode9.1, Swift4, iOS11.1
A screenshot and Sample code are here: https://www.dropbox.com/sh/t1x1508s8bhrrfc/AAAFoxParSBu1gY-Zuyk12GDa?dl=0

**Comment by xiasanlan** [comment]
@ashokkumarmw  It's not in the middle. It defaults to 45% of screen height

**Comment by ashokkumarmw** [comment]
@xiasanlan Okay. Can you help me where exactly I can change the default value to 50% of screen height.

**Comment by xiasanlan** [comment]
@ashokkumarmw  you can search “0.45” in SVProgressHUD.m

**Comment by ashokkumarmw** [comment]
@xiasanlan Thanks, found it. changed it to 0.5f and it worked.
CGFloat posY = floorf(activeHeight*0.5f);

**Comment by NeerajKumar123** [comment]
Thanks @kwGao (y)

**Comment by skvaghasiya402** [comment]
refer this answer : https://iostutorialpoints.blogspot.com/2018/10/svprogresshud-not-showing-at-center-of.html
