### ISSUE TITLE
when changeStyle  The original view does not disappear will have problems

### ISSUE THREAD

**Issue by GodVampire** [SVProgressHUD/SVProgressHUD#847]
steps 
The premise condition : In Demo.

1.At SVProgressHUDStyleLight status ,Do: show
2.changeStyle SVProgressHUDStyleDark,Do :show

Step 2 display status is not I wanted dark style

The effect：
![2017-12-12 12 06 42](https://user-images.githubusercontent.com/24238447/33867044-f6233df6-df34-11e7-9c7b-645aaf0da5f9.png)

So: Whether to need to perform when switching state
`[SVProgressHUD dismiss];`

Or is there a way to make two styles coexist, please inform me, thank you for.

**Comment by darling0825** [comment]
I have this problem.

**Comment by honkmaster** [comment]
Which version are you using?
