### ISSUE TITLE
iOS 11系统上加载动画偏上，没有居中

### ISSUE THREAD

**Issue by fortitude1990** [SVProgressHUD/SVProgressHUD#849]
如题

**Comment by padishahG** [comment]
我也是

**Comment by padishahG** [comment]
你升级一下，现在好了

**Comment by BBB1n** [comment]
请问你偏上多少？我感觉如果有键盘在下面的话算是在正中间

**Comment by demoncraz** [comment]
same issue - it seems that the -(CGFloat)visibleKeyboardHeight method still returns a valid keyboard bounds even if the keyboard is actually hidden in iOS 11.

**Comment by Shanesun** [comment]
@demoncraz right, UIInputSetHostView always 226 and hidden is NO(<UIInputSetHostView: 0x1072081c0; frame = (0 736; 414 226); layer = <CALayer: 0x10dea2770>>)but keyboard not show. in iOS11

**Comment by honkmaster** [comment]
Could you please check the PR #846 and give feedback. I have very limited time, PR and feedback on those thus helps the most.

**Comment by zhiliang729** [comment]
CGRect rect = possibleKeyboardSubview.bounds;
                        if (CGRectGetMaxY(rect) >= [UIScreen mainScreen].bounds.size.height) {
                            return 0;
                        } else {
                            return CGRectGetHeight(possibleKeyboardSubview.bounds);
                        }

**Comment by zhiliang729** [comment]
Replace line 1370 with below:

CGRect rect = possibleKeyboardSubview.bounds;
                        if (CGRectGetMaxY(rect) >= [UIScreen mainScreen].bounds.size.height) {
                            return 0;
                        } else {
                            return CGRectGetHeight(possibleKeyboardSubview.bounds);
                        }

**Comment by pusswzy** [comment]
replace in [visibleKeyboardHeight] function

if (CGRectGetMinY(possibleKeyboardSubview.frame) >= [UIScreen mainScreen].bounds.size.height) {
                        return 0;
} else {
                       return CGRectGetHeight(possibleKeyboardSubview.bounds);
}

**Comment by juliensaad** [comment]
Should be fixed with https://github.com/SVProgressHUD/SVProgressHUD/pull/846#pullrequestreview-92033451
