### ISSUE TITLE
Display is not in the middle

### ISSUE THREAD

**Issue by padishahG** [SVProgressHUD/SVProgressHUD#852]
Jump to set the interface returned back, display is not in the middle, when can solve?thank you

**Comment by padishahG** [comment]
@dennisreimann @justin @alloy @andreyvit @theill @

**Comment by padishahG** [comment]
MBProgressHUD, compared the framework, it is more simple, but the problem is also more.Hope you can add some more developers to the maintenance.

**Comment by honkmaster** [comment]
Could you please check the PR #846 and give feedback. I have very limited time, PR and feedback on those thus helps the most.

**Comment by padishahG** [comment]
@honkmaster    alright, thank you very much

**Comment by zhiliang729** [comment]
Replace line 1370 with below:

CGRect rect = possibleKeyboardSubview.bounds;
if (CGRectGetMaxY(rect) >= [UIScreen mainScreen].bounds.size.height) {
return 0;
} else {
return CGRectGetHeight(possibleKeyboardSubview.bounds);
}

**Comment by juliensaad** [comment]
Should be fixed with https://github.com/SVProgressHUD/SVProgressHUD/pull/846#pullrequestreview-92033451
