### ISSUE TITLE
[A feature request] Display a 'x' cancel/dismiss button

### ISSUE THREAD

**Issue by daurenm** [SVProgressHUD/SVProgressHUD#857]
Hi there, 

Is possible to add a 'x' (cancel) button right in the middle, after few seconds to dismiss the hud? For example, it will be helpful, if your operations are taking too much time at the same time disabling UI, to give users ability to stop the loading.

Here is example from VK app: https://youtu.be/h9n5XFiSMoc

**Comment by balkarov** [comment]
+1

**Comment by honkmaster** [comment]
This issue has been discussed very often #727, #593, #429.  

> The main idea is to use `SVProgressHUDDidTouchDownInsideNotification` in your app and then call dismiss. I won't implement a dedicated button.
