### ISSUE TITLE
Swift: Repositioning issue of Progress Bar when keyboard goes down 

### ISSUE THREAD

**Issue by gunjankumr** [SVProgressHUD/SVProgressHUD#866]
I am using SVProgressHUD (~> 2.0) in my app and facing the animation issue. When keyboard goes down, progress hud moves to center.

**Comment by rpendleton** [comment]
That sounds like expected behavior to me... What do you think it should do instead?

**Comment by honkmaster** [comment]
This is indeed expected. The HUD will always be in the center of the visible view field.

**Comment by yongyotk** [comment]
Please check the similar issue you had with Objective C also and you people fixed the issue. The expected behavior is, loader should always show in center.

**Comment by gunjankumr** [comment]
I am also expecting that hud should always be in center. The issue is, hud moves to the center when keyboard goes down not from the starting. If keyboard is already down, then it works perfect.

**Comment by gunjankumr** [comment]
You people fixed the same issue for Objective C
