### ISSUE TITLE
Getting Error While Trying to İnstall via Carthage

### ISSUE THREAD

**Issue by xyzbilal** [SVProgressHUD/SVProgressHUD#874]
hi, I m getting this error while trying to create files vis Carthage with an exit code,  I have no idea how to solve this problem. regards..

`A shell task (/usr/bin/xcrun xcodebuild -project /Users/bilal/Desktop/seefood/Carthage/Checkouts/SVProgressHUD/SVProgressHUD.xcodeproj CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES -list) failed with exit code 72:
xcrun: error: unable to find utility "xcodebuild", not a developer tool or in PATH`

**Comment by justin** [comment]
What is the output if you run `which xcodebuild` and `xcode-select -p`?

**Comment by xyzbilal** [comment]
`/usr/bin/xcodebuild` for `which xcodebuild `
`/Library/Developer/CommandLineTools` for `xcode-select -p`

**Comment by justin** [comment]
Can you adjust the `xcode-select` command to point to a copy of Xcode directly?

`sudo xcode-select --switch /Applications/Xcode.app`

See if that works.

**Comment by xyzbilal** [comment]
it worked. thank you for your effort.

**Comment by justin** [comment]
@honkmaster this can be closed.
