### ISSUE TITLE
Remove Carthage suppport?

### ISSUE THREAD

**Issue by honkmaster** [SVProgressHUD/SVProgressHUD#875]
There seem to be many issues regarding Carthage, including #874 #708 #613 #601, #535. Some of those I closed as they were stale for some time.

Overall, Carthage does not work. I can not provide Carthage support as I am not using it myself. The original proposers do not maintain the feature. Thus I propose to remove support for it. Any opinions?

As an alternative, I could have a look on how to integrate with the Swift Package Manager.

**Comment by honkmaster** [comment]
@juliensaad Your opinion?

**Comment by juliensaad** [comment]
I don't use Carthage either. My projects either directly use submodules or CocoaPods. If Carthage doesn't work, we should drop it until we properly support it.

**Comment by honkmaster** [comment]
Maybe we should ask the some previous commiters too: @flovilmart, @justin.

**Comment by justin** [comment]
We still use the framework through Carthage and haven't run into any issues with it.

**Comment by justin** [comment]
For what its worth, we at TED are willing to handle any Carthage issues as they arise. Looking at these tickets it like its either user error ($PATH) or misidentified functionality (does the framework support tvOS as is or is that just a wishlist?). 

Happy to discuss this more here or offline in terms of what mantaining Carthage support actually entails. Contact info on my GitHub profile.

**Comment by honkmaster** [comment]
It seems that it was worth opening this thread. @justin: Thanks for this commitment.

**Comment by justin** [comment]
I've added it to my bug queue to look at the tvOS building thing. I'd suggest a Playground demo as well to verify / demo the Swift support + exercise the framework builds.

Is iOS 8.3 / tvOS 10(?) still the required minimum for support? Any other building settings that are untouchable?

**Comment by flovilmart** [comment]
I'll also try to have a look to in the open issues, see if I can help. I don't use carthage much anymore but still contribute to projects that leverage it and I know it can be a bit painful to keep up with compatibility. However, I don't believe removing the support is the way to go.
