### ISSUE TITLE
Please add release notes to releases

### ISSUE THREAD

**Issue by pepejeria** [SVProgressHUD/SVProgressHUD#878]
It would be great if you could add release notes to the releases. There is now no way to know what changed in a new release. 

Thanks.

**Comment by honkmaster** [comment]
Have you checked the repository? There is already a `CHANGELOG.md`.

**Comment by pepejeria** [comment]
Ok fair enough. Would have been nice to see what's new on the following link as well:
https://github.com/SVProgressHUD/SVProgressHUD/releases

**Comment by honkmaster** [comment]
There is no way to do it automatically (as far as i know). My main workflow is from the console.
