### ISSUE TITLE
Using SVProgressHUD in a pure Swift app extension?

### ISSUE THREAD

**Issue by jeanfw** [SVProgressHUD/SVProgressHUD#887]
Is there a way to use `SVProgressHUD` in an app extension written in pure Swift?

Using the `#define SV_APP_EXTENSIONS` preprocessor macro (as suggested in the [readme](https://github.com/SVProgressHUD/SVProgressHUD/blob/2.2.5/README.md#app-extensions)) isn't possible in Swift.

Thanks for your help & for maintaining SVProgressHUD, it's an awesome lib ! 👍

**Comment by gunjotSinghMansa** [comment]
any solution ?

**Comment by jeanfw** [comment]
@gunjotSinghMansa No unfortunately I didn't find any. As a workaround, ended up implementing a custom `UIActivityIndicatorView` overlay for my extension.
