### ISSUE TITLE
Change background color but keep blur

### ISSUE THREAD

**Issue by fl034** [SVProgressHUD/SVProgressHUD#888]
I want to achieve a HUD which is more native style (see volume HUDs).
But when I set the `backgroundColor`, I lose the blur effect.

I looked inside the code and saw that you are putting a 60% white under the blur effect. 
This leads to the problem that you can't see the borders of the light HUD on a white view controller background.

It would be cool to be able to change those colors and provide a more native default setting.

**Something like `UIColor.gray` with 20% alpha looks much more pleasant to me:**
![examplegrey](https://user-images.githubusercontent.com/11268968/38088125-055a7030-335b-11e8-827a-e85193b30105.png)

**This is how the default setting looks on white:**
![lightexample](https://user-images.githubusercontent.com/11268968/38088126-0573122a-335b-11e8-9b52-cfe552eb93d7.png)

**iOS 11 Volume HUD:**
![examplevol](https://user-images.githubusercontent.com/11268968/38088127-058985dc-335b-11e8-9dc1-89a431f235fc.png)

**Comment by honkmaster** [comment]
A Pull request is warmly welcome.

**Comment by fl034** [comment]
Replying to leave this open. Maybe me or someone else can invest some time to create light and dark default styles that mimic the system overlay look and feel.

**Comment by Kaspik** [comment]
PR opened - https://github.com/SVProgressHUD/SVProgressHUD/pull/945 - is there anything else you would need @fl034 ?

**Comment by fl034** [comment]
@Kaspik thanks for your help. I have no time for testing right now, but the code looks good to me :).

If you also need a hud style that looks more like the native volume hud, you could experiment with the background color and make a new PR with adding a new default style beside dark and light.

**Comment by Kaspik** [comment]
The problem is that every major iOS version looks little bit different so keeping it as it is can't hurt. :))

**Comment by honkmaster** [comment]
I think we should do two things:

1. Provide an option to set a custom blur effect
1. Change the default to look as native as possible (compared to the most recent iOS version)

**Comment by Kaspik** [comment]
The option for custom blur is added on my PR, the second is nice to have but currently something I'm not planning to add...
