### ISSUE TITLE
Views behind the HUD still interactive

### ISSUE THREAD

**Issue by JohneSchwoopf** [SVProgressHUD/SVProgressHUD#895]
Title

**Comment by EmmanuelC19** [comment]
Use de property maskType to avoid the interaction with the vies behind the HUD

**Comment by swlaunch** [comment]
Same issue, I tried all maskTypes, view still interactive

**Comment by JimmyGoGoGo** [comment]
@swlaunch try this:
OperationQueue.main.addOperation {
                SVProgressHUD.setDefaultMaskType(defaultMaskType)
            }

Work for me. Because the hub is shown asynchronously in main queue.

**Comment by JimmyGoGoGo** [comment]
@swlaunch 

let defaultMaskType = SVProgressHUDMaskType.none
        SVProgressHUD.setDefaultMaskType(.clear)
//Now show it with the clear mask
        SVProgressHUD.showInfo(withStatus: msg)
//Now restore it with the default mask
        OperationQueue.main.addOperation {
                SVProgressHUD.setDefaultMaskType(defaultMaskType)
            }
