### ISSUE TITLE
ProgressHUD does not display from delegate callback on iOS 11.3

### ISSUE THREAD

**Issue by MrPingPong** [SVProgressHUD/SVProgressHUD#896]
I have UIAlertView delegate implementation in my view controller and in the delegate implementation, I show the ProgressHUD and perform some task. Task is being perform without showing the ProgressHUD.

// Sample code
-(void)alertView:(UIAlertView *)alertView clickedButtonAtIndex:(NSInteger)buttonIndex {
  if (buttonIndex == 1) {
        [SVProgressHUD show];
        //my task
  }
}

I even tried invoking "SVProgressHUD show" from dispatch_async/MainThread but no help.

This issue is reproducible on iOS 11.3 but NOT on iOS 10.3 (only these 2 devices i have, din't try on simulator or any other iOS version).

Please share if there is any workaround.

**Comment by popking5466** [comment]
the same question at UIActionSheetDelegate

```
- (void)actionSheet:(UIActionSheet *)popup clickedButtonAtIndex:(NSInteger)buttonIndex {
    [SVProgressHUD showErrorWithStatus:@"permission denied"];
}
```
the function is run but didnot display anything..
:(
