### ISSUE TITLE
UI API called from the background thread.

### ISSUE THREAD

**Issue by arpwal** [SVProgressHUD/SVProgressHUD#902]
SVProgressHUD.m -- sharedView class method,

Code snippet here: 

static SVProgressHUD *sharedView;
#if !defined(SV_APP_EXTENSIONS)
    dispatch_once(&once, ^{ sharedView = [[self alloc] initWithFrame:[[[UIApplication sharedApplication] delegate] window].bounds]; });
#else
    dispatch_once(&once, ^{ sharedView = [[self alloc] initWithFrame:[[UIScreen mainScreen] bounds]]; });
#endif

**Comment by qianlishun** [comment]
I had the same problem.
```
dispatch_async(dispatch_get_main_queue(), ^{
            [SVProgressHUD show];
});
```
This does not eliminate the Main Thread Checker warning.

**Comment by caobug** [comment]
Yes, I had the same problem.

**Comment by titiphoque** [comment]
I have the same problem.

**Comment by xiao99xiao** [comment]
It's 2019 and the issue still exists.

**Comment by qianlishun** [comment]
> I had the same problem.
> 
> ```
> dispatch_async(dispatch_get_main_queue(), ^{
>             [SVProgressHUD show];
> });
> ```
> This does not eliminate the Main Thread Checker warning.

Looks like a CoreMotion bug , I only encountered this situation in XR / XS /XSM and new iPad Pro.

**Comment by emanharout** [comment]
Is there anything we can do to work around this? Any insight/input is appreciated. Just started testing my app on a new XR and I'm getting this issue pretty frequently.

**Comment by endlessLetter** [comment]
I have the same problem.Xcode 10.2 iOS12.1 iPhone XR

**Comment by mkkroliks** [comment]
Same here. Iphone Xs xcode 10.2.

**Comment by dgpratt4** [comment]
Same here. iPhone XS Max, Xcode 10.2, Swift 5.0

**Comment by EggsOfAngel** [comment]
The same issue, and app not crashed, it occurred in my iPhone XR ,not occurred in my iPhone 6

**Comment by kapoorsahil** [comment]
Same here. iPhone XS, Xcode 10.2, Swift 5.0.

**Comment by MourinhoLove** [comment]
Same here. iPhone XR, Xcode 10.2, Swift 5.0.

**Comment by AminFadul** [comment]
it's May 2019 and I'm still facing this problem with Swift 5 and Xcode 10.2, iPhone XS Max

**Comment by Li-Heng-LH** [comment]
Same problem here. iPhone XSM, Xcode 10.2, Swift 5.0.

**Comment by vytautasgimbutas** [comment]
Same here.

**Comment by bkrijgsman** [comment]
Same issue here.

**Comment by emiltsang** [comment]
same issue here.
The problem existed over 1 years.

**Comment by MehdiChennoufi** [comment]
Hey guys, it seems that this issue concerns CoreMotion on iPhone X/Xs/Xr, the behavior is the same, I don't have any problem with SVProgressHud's animation when my device is not running from Xcode

Radars are opened for this and only happens in Debug mode

https://openradar.appspot.com/46210367
https://openradar.appspot.com/45003816
An other topic with same issue :
https://github.com/Instabug/Instabug-iOS/issues/298

**PS :** I really don't why CoreMotion is involved in here but my console references to it, same as yours I guess..

**Comment by daoinek** [comment]
I have this problem
