### ISSUE TITLE
Crash in iOS10.3

### ISSUE THREAD

**Issue by CaliosD** [SVProgressHUD/SVProgressHUD#909]
Hi, I've got some problems when using this library.
```
SVProgressHUD.showInfo(withStatus: Text.refundSuccess.localized)
SVProgressHUD.dismiss(withDelay: 1.0, completion: { [weak self] in // <--- crashes from here
    // Do something 
})
```

Crash lines in deep:
```
// Update imageView
            if (self.shouldTintImages) {
                if (image.renderingMode != UIImageRenderingModeAlwaysTemplate) {
                    strongSelf.imageView.image = [image imageWithRenderingMode:UIImageRenderingModeAlwaysTemplate];  // <-- crashes at this line, L845 of SVProgressHUD.m
                }
                strongSelf.imageView.tintColor = strongSelf.foregroundColorForStyle;;
            } else {
                strongSelf.imageView.image = image;
            }
```

Here's the snapshot below.
![1527509444646](https://user-images.githubusercontent.com/5526378/40613972-4efebade-62b3-11e8-850a-de1bca4e4125.jpg)

I tried several times, but in iOS11, it works fine. 

I wonder what happened and how to solve it. Thanks in advance for any help.

**Comment by GaoRuihao** [comment]
I meet this crash too,and in iOS 11, it also crash

**Comment by LuckZXF** [comment]
I meet the same problem，and I deal with
`if (self.shouldTintImages) {
                if (image.renderingMode != UIImageRenderingModeAlwaysTemplate) {
                    if ([image respondsToSelector:@selector(imageWithRenderingMode:)]) {
                        strongSelf.imageView.image = [image imageWithRenderingMode:UIImageRenderingModeAlwaysTemplate];
                    }
                }
                strongSelf.imageView.tintColor = strongSelf.foregroundColorForStyle;
            } else {
                if ([image isKindOfClass:[UIImage class]]) {
                    strongSelf.imageView.image = image;
                }
            }`

**Comment by CaliosD** [comment]
Hi, guys. I finally figured out why it crashed not too long after submitting this issue. 
I used to configure hub globally as follow, which is not correct, since the image should be `nonnull`:
```
SVProgressHUD.setInfoImage(UIImage())
```
I replaced it with a 1px image, and the crash dismissed. It works fine in other versions of iOS, but fails on iOS10.3. I really don't know why... :(
