### ISSUE TITLE
ios11 crash: Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[NSBundle initWithURL:]: nil URL argument' *** First throw call stack:

### ISSUE THREAD

**Issue by surbhivarma90** [SVProgressHUD/SVProgressHUD#911]
I am getting this crash using the pods to install SVProgressHUD

**Comment by unleashedspeed** [comment]
Same here. I am getting the same crash.

**Comment by lintongSD** [comment]
Same here.But only simulator crash,LaunchImage not full screen.My iPhone 6s is ok,

Xcode 9.2 simulator iPhone 8p

**Comment by songkuixi** [comment]
Same here, iOS 12 beta 1 + Xcode 10 beta
