### ISSUE TITLE
During the presentation, the frame changes

### ISSUE THREAD

**Issue by XLMARK** [SVProgressHUD/SVProgressHUD#912]
With a third party login, the frame position changes during the show while jumping back to my application from other applications. #
![default](https://user-images.githubusercontent.com/17427379/40954104-95d08b92-68b5-11e8-94bc-a0372b5f7642.gif)

**Comment by WZSlike** [comment]
we meet the same problem.

**Comment by xuanyuelin** [comment]
Though i use the mehotd setOffsetFromCenter to adjust it's location,the center still jump around the page. Which makes me suffer.Provide to use MBProgressHUD!!!

**Comment by pawanline** [comment]
did anybody get the solution to this problem?. I am getting the same. please help asap.
