### ISSUE TITLE
设置消失时间

### ISSUE THREAD

**Issue by devcatin** [SVProgressHUD/SVProgressHUD#924]
[SVProgressHUD setMinimumDismissTimeInterval:3.0];
[SVProgressHUD setMaximumDismissTimeInterval:3.0];
设置这两个时间无效,请求指教,谢谢

**Comment by Adrift001** [comment]
能用英文问问题么?你以为GitHub是中国的?

**Comment by caobug** [comment]
If I am not there, will you both fight?
