### ISSUE TITLE
swift 3

### ISSUE THREAD

**Issue by khushDesai** [SVProgressHUD/SVProgressHUD#928]
Hey How can i use this pods in Swift 3 with xcode 8?

Please Help!

**Comment by skhiearth** [comment]
Use CocoaPods. 

Make sure you have CocoaPods installed in your machine. Then, initiate pod in the current working directory by `pod init` 

Open Podfile using Xcode and add the pods you want. 

Then use `pod install`

Open the .xcworkspace to work on your project.
