### ISSUE TITLE
SVProgressHUD should be able to be added to a specific view

### ISSUE THREAD

**Issue by nyeu** [SVProgressHUD/SVProgressHUD#933]
I would like to add the hud into an specific view rather in the `UIWindow` as its at the moment.
The case is, I want the user interaction blocked as I don't want the user to keep tapping the buttons or interact with the view. But, I would like them to be able to access the back button (or any navigation bar button), this could be achieved if the Hud was added as a subview of the Viewcontroller view. At the moment, there's no way to set the Hud into an specific view.

**Comment by repixels** [comment]
You can use the method

```objc
+ (void)setContainerView:(nullable UIView*)containerView;
```

**Comment by lori0208** [comment]
A little bit of a problem.
+ (void)setContainerView:(nullable UIView*)containerView; 
show view frame is incorrect
it should be parents view bounds not frame

**Comment by shubham14896** [comment]
Still facing a problem with the set container view, kindly fix

**Comment by IMKalpataru** [comment]
`let containerOrigin = yourView.frame.origin
            SVProgressHUD.setOffsetFromCenter(UIOffset(horizontal: -containerOrigin.x, vertical: -containerOrigin.y))`

This solved my issue.
