### ISSUE TITLE
urgent problem need to be solved - from a sincere customer

### ISSUE THREAD

**Issue by XHJiang** [SVProgressHUD/SVProgressHUD#935]
hi there,

we cannot check the reason why we met the problem as following picture shows. please help check and give us a feedback..

![image](https://user-images.githubusercontent.com/13825718/48472987-709ac480-e832-11e8-829d-73ea762107c7.png)

**Comment by Mian-Wu** [comment]
Yes, I had the same problem.Is there any solution?
