### ISSUE TITLE
Showing two HUD simultaneously

### ISSUE THREAD

**Issue by aabanaag** [SVProgressHUD/SVProgressHUD#936]
I have an upload process that shows the progress via SVProgressHUD. After which should show another HUD for printing the badge. But whenever the printing process is called SVProgressHUD never shows.

```
viewModel.uploadProgress
      .skip(1)
      .bind(to: SVProgressHUD.rx.uploadProgress())
      .disposed(by: bag)
```

uploadProgress is just an RxSwift extension that has this `SVProgressHUD.showProgress(value, status: "Uploading")`

**Comment by MZabih** [comment]
hey @aabanaag did you find any solution? I think `show` method in the `SVprogresshud` class must not be static.

**Comment by aabanaag** [comment]
No I haven't found any solution to it yet.
