### ISSUE TITLE
in UIAlertView delegate alertView:clickedButtonAtIndex: when clicked confirm button ,call  [SVProgressHUD show] 

### ISSUE THREAD

**Issue by yumengbdw** [SVProgressHUD/SVProgressHUD#944]

**Comment by yumengbdw** [comment]
![image](https://user-images.githubusercontent.com/11400046/51017268-7997e000-15ae-11e9-8761-e352b9473815.png)

window return nil
![image](https://user-images.githubusercontent.com/11400046/51017294-8fa5a080-15ae-11e9-96b1-687af67ffe61.png)

**Comment by yumengbdw** [comment]
` if(windowOnMainScreen && windowIsVisible && windowLevelSupported && windowKeyWindow) {
            return window;
        }`
windowOnMainScreen  ：YES
windowIsVisible ：YES
windowLevelSupported ：YES
windowKeyWindow is NO

**Comment by czl0325** [comment]
我是加个延时0.1秒显示SVProgressHUD来解决这个问题

**Comment by Ryan0520** [comment]
@czl0325 这个延迟0.1秒再显示，会不会是曲线救国啊。我感觉现在SVProgressHUD好不稳定啊，iOS13.0的没加tag，如果是系统的AlertView或者是ActionSheet点击了操作按钮后，都没法正常显示这个弹窗提示了。keyWindow是系统的AlertView或ActionSheet，这个作者应该改改吧。。
