### ISSUE TITLE
Crash `dispatch_once(predicate, block);` when call `showHud` in `viewdidLoad`

### ISSUE THREAD

**Issue by phuhk** [SVProgressHUD/SVProgressHUD#953]
Hi there,

My project using lastest XCode 10.2, Swift 5. I just call `showHud` in `viewdidLoad` but app crash at `dispatch_once(predicate, block);`

This is my screenshot [https://prnt.sc/n9ob5m](url)

**Comment by wAikAp** [comment]
Did you run the showHud at the main thread? such as 
dispatch_async(dispatch_get_main_queue(), ^{

}

**Comment by wAikAp** [comment]
> Hi there,
> 
> My project using lastest XCode 10.2, Swift 5. I just call `showHud` in `viewdidLoad` but app crash at `dispatch_once(predicate, block);`
> 
> This is my screenshot [https://prnt.sc/n9ob5m](url)

Did you run the showHud at the main thread? such as
dispatch_async(dispatch_get_main_queue(), ^{

}

**Comment by phuhk** [comment]
hi, if we run some code in viewDidLoad, we can ensure they run in main thread already :)

**Comment by wAikAp** [comment]
Now I get it, thanks for your comment XD

**Comment by yybmsrs** [comment]
maybe bundle not load.

**Comment by otetLopez** [comment]
Hello, Is this resolveld?  I got the same problem

**Comment by haohaofan** [comment]
I am facing with the same problem in Swift project, How can I solve it?
