### ISSUE TITLE
lost ’;‘ in SVProgressHUD.m line 894

### ISSUE THREAD

**Issue by Sunday4** [SVProgressHUD/SVProgressHUD#963]
SVProgressHUD.m

line number 894 

`
 NSString *accessibilityString = [[self.statusLabel.text componentsSeparatedByCharactersInSet:[NSCharacterSet newlineCharacterSet]] componentsJoinedByString:@" "]
`  no't found ';'

**Comment by honkmaster** [comment]
Fixed.
