### ISSUE TITLE
iOS 13 Dark Mode

### ISSUE THREAD

**Issue by getaaron** [SVProgressHUD/SVProgressHUD#964]
Perhaps a new default value that switches between `SVProgressHUDStyleLight` and `SVProgressHUDStyleDark` based on the dark mode setting?

**Comment by honkmaster** [comment]
Good idea. A PR is warmly welcome.

**Comment by getaaron** [comment]
@honkmaster any update on this?

**Comment by getaaron** [comment]
Lol

**Comment by getaaron** [comment]
.

**Comment by getaaron** [comment]
👹

**Comment by tomblah** [comment]
This would be an incredibly useful feature
