### ISSUE TITLE
UIApplicationDidChangeStatusBarOrientationNotification not firing in iOS 13

### ISSUE THREAD

**Issue by ajprala** [SVProgressHUD/SVProgressHUD#966]
Hey all anyone seeing this in thier apps ? In ios 12.3 and less the 
UIApplicationDidChangeStatusBarOrientationNotification is firing , so the HUD will reposition / resize correctly.  In iOS 13 this event isnt fired which leaves the HUD in nomans land when changing orientation, the others fire like UIKeyboardWillShowNotification

**Comment by ajprala** [comment]
whats weird it seems to work on the demo app in iOS 13. The only difference i can think of is the demo has a storyboard, and im using a nib, it shouldnt make a difference but i see 0 other difference.

**Comment by harshith7823** [comment]
UIApplicationDidChangeStatusBarOrientationNotification is deprecated on iOS13  @ajprala  - https://developer.apple.com/documentation/uikit/uiapplicationdidchangestatusbarorientationnotification?language=objc
