### ISSUE TITLE
Support Swift Package Manager

### ISSUE THREAD

**Issue by peterboni** [SVProgressHUD/SVProgressHUD#967]
Support developers using Xcode 11 and Swift Package Manager.

https://wwdcbysundell.com/2019/xcode-swiftpm-first-look/

**Comment by rosskimes** [comment]
Any plans for this now that Xcode 11 is out?

**Comment by GottaGetSwifty** [comment]
+1

**Comment by GottaGetSwifty** [comment]
Pull request here: https://github.com/SVProgressHUD/SVProgressHUD/pull/993

**Comment by Jeehut** [comment]
This is not stale at all, SwiftPM is still not supported and we're at Xcode 12.3 already, so many are switching away from Carthage / CocoaPods, like we are doing right now. How can I remove `stale` from here?
