### ISSUE TITLE
iOS 13运行卡主线程

### ISSUE THREAD

**Issue by 18339689882** [SVProgressHUD/SVProgressHUD#969]
Is apple's latest version of the system using SVPProgressHUD to card the main thread?

**Comment by iTaosky** [comment]
I also encountered the same problem, the problem appeared in iPhone xr iOS 12.2

![image](https://user-images.githubusercontent.com/15977397/60250754-cf143f00-98f9-11e9-8593-9da0f7386591.png)

**Comment by iTaosky** [comment]
> I also encountered the same problem, the problem appeared in iPhone xr iOS 12.2
> 
> ![image](https://user-images.githubusercontent.com/15977397/60250754-cf143f00-98f9-11e9-8593-9da0f7386591.png)

I found that this problem occurs when using real machine debugging, and this will not happen after the line is unplugged.

**Comment by hucool** [comment]
I have the same problem

**Comment by abinchy** [comment]
> > I also encountered the same problem, the problem appeared in iPhone xr iOS 12.2
> > ![image](https://user-images.githubusercontent.com/15977397/60250754-cf143f00-98f9-11e9-8593-9da0f7386591.png)
> 
> I found that this problem occurs when using real machine debugging, and this will not happen after the line is unplugged.

Yea.. I also found that not happen when not debugging

**Comment by myhubname** [comment]
我也是一样

**Comment by inoryshu** [comment]
这个问题真的很是奇怪，在苹果最新几款手机iPhone XS,iPhone XS Max，iPhone XR，在真机调试的时候都会出现这个问题，并且我找到报问题的位置
<img width="1165" alt="WechatIMG205093" src="https://user-images.githubusercontent.com/16499387/61697174-532adc80-ad69-11e9-9168-46816e01f469.png">
<img width="459" alt="WechatIMG205092" src="https://user-images.githubusercontent.com/16499387/61697184-5625cd00-ad69-11e9-87d1-cd3f0afd9c52.png">
<img width="414" alt="WechatIMG205090" src="https://user-images.githubusercontent.com/16499387/61697189-5920bd80-ad69-11e9-90cc-81054880c745.png">

**Comment by inoryshu** [comment]
并且我把这句代码注释以后就不会线程问题了：[self.hudView addMotionEffect:effectGroup];

**Comment by northcity** [comment]
I encountered the same problem that caused my online bug. I caused it after setting the display time of the pop-up box.

**Comment by honkmaster** [comment]
Please use the HUD, as shown in the Usage section, from the main thread.

**Comment by inoryshu** [comment]
> 请使用主线程中的HUD，如用法部分所示。

请看截图线程，addMotionEffect的时候肯定百分百在主线程里，但是依然被Xcode报了线程问题

**Comment by thecorsair** [comment]
之前我用 MBProgressHUD. 也会报这个问题。
```
 Main Thread Checker: UI API called on a background thread: -[UIApplication applicationState] 
```

**Comment by myhubname** [comment]
我测试了下好像真机才会出这个问题



------------------ 原始邮件 ------------------
发件人: "lkhan"<notifications@github.com>; 
发送时间: 2019年9月9日(星期一) 下午2:26
收件人: "SVProgressHUD/SVProgressHUD"<SVProgressHUD@noreply.github.com>; 
抄送: "渡"<1716089236@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [SVProgressHUD/SVProgressHUD] iOS 13运行卡主线程 (#969)




之前我用 MBProgressHUD. 也会报这个问题。
  Main Thread Checker: UI API called on a background thread: -[UIApplication applicationState]
