### ISSUE TITLE
SvProgress hud is display after 2 - 3 seconds

### ISSUE THREAD

**Issue by MandeepSingh1** [SVProgressHUD/SVProgressHUD#973]
=================================================================
Main Thread Checker: UI API called on a background thread: -[UIApplication applicationState]
PID: 1729, TID: 405255, Thread name: com.apple.CoreMotion.MotionThread, Queue name: com.apple.root.default-qos.overcommit, QoS: 0

Here is the logs which I get in my console. So please guys check, I have download your code and run it in Xcode 10.3.

Device Information:-

iOS: 12.4
Device Name:- iPhone XS MAx

**Comment by wubing3688** [comment]
我也遇到了

**Comment by misolab** [comment]
I referenced this link:
https://github.com/JonasGessner/JGProgressHUD/issues/98
