### ISSUE TITLE
iOS13 beat4 show hud problem

### ISSUE THREAD

**Issue by wuwenyan** [SVProgressHUD/SVProgressHUD#974]
iOS13 beat4，HUD don't show statusLabel when Second Call

**Comment by Ryan0520** [comment]
I have same issues

**Comment by ajprala** [comment]
i see the same thing for my app built against iOS 12 SDK running on iOS 13, however if I build it on iOS 13 SDK the label seems to show up everytime (at least on the simulator).

**Comment by rl3780** [comment]
iOS13 beta7, problem still exist

**Comment by gh552** [comment]
We had the same problem and updated SVProgressHUD to Version 2.2.6. 
With 2.2.6 everything works fine, there is no problem.

**Comment by rl3780** [comment]
@gh552 thanks, not sure why there is no tag for version 2.2.6, but update to newest code works for me.

**Comment by Ryan0520** [comment]
> @gh552 thanks, not sure why there is no tag for version 2.2.6, but update to newest code works for me.

the newest code is 2.2.5, did not solve the problem

**Comment by imilakovic** [comment]
Hm... It seems to work for me with version 2.2.5, built with Xcode 11.0 GM (11A419c).

**Comment by CloseServer** [comment]
some issue .😟 
![image](https://user-images.githubusercontent.com/12987627/65371791-d8fbd300-dc99-11e9-9a54-763f6865c13c.png)

**Comment by demoker** [comment]
`if(!_stringLabel.superview)
        [self.hudView addSubview:_stringLabel];`
替换上面的代码为:
`if(![self.hudView.subviews containsObject:_stringLabel])
        [self.hudView addSubview:_stringLabel];`

**Comment by nickthedude** [comment]
This seems to still be an issue

**Comment by ivela** [comment]
> `if(!_stringLabel.superview) [self.hudView addSubview:_stringLabel];`
> 
> replace:
> 
> `if(![self.hudView.subviews containsObject:_stringLabel]) [self.hudView addSubview:_stringLabel];`

Hi. I couldn't find this line: if(!_stringLabel.superview) [self.hudView addSubview:_stringLabel]; in the source code.

Could you explain me where do I have to change it?

**Comment by remew** [comment]
We had the same problem but @demoker 's solution works fine!!
Thank you for your solution!

@ivela 
`_stringLabel` is old name.
So replace `_stringLabel` with `_statusLabel` in @demoker 's code and find it.

You have to change around this line if you are using current `master` branch.
https://github.com/SVProgressHUD/SVProgressHUD/blob/master/SVProgressHUD/SVProgressHUD.m#L1308
It should solve the problem.

**Comment by tritmm** [comment]
@demoker @remew 
thank you so much <3

**Comment by muratyasarr** [comment]
Why not fix this problem and release a new version of SVProgressHUD?

**Comment by honkmaster** [comment]
This component is OSS. You are always welcome to submit a fix as pull request.

**Comment by honkmaster** [comment]
have

**Comment by iHardikTrivedi** [comment]
Try this solution:
[[SOLUTION]](https://github.com/SVProgressHUD/SVProgressHUD/issues/1013#issuecomment-567335032)

**Comment by honkmaster** [comment]
![Simulator Screen Shot - iPhone 11 Pro - 2020-01-04 at 09 47 14](https://user-images.githubusercontent.com/1380397/71763013-388f8e80-2ed7-11ea-8b82-77a226d126c0.png)
 
I am looking at the demo project. The label is shown on iOS 13 without any issue. Please provide any details to reproduce this issue.
