### ISSUE TITLE
请问如何更改文字的大小，文本多了，字体就变小了。

### ISSUE THREAD

**Issue by Mac-sir** [SVProgressHUD/SVProgressHUD#980]
SVProgressHUD.setMinimumSize(CGSize(width: 300, height: 17))
SVProgressHUD.setOffsetFromCenter(UIOffset(horizontal: 0, vertical: 35))
SVProgressHUD.setDefaultMaskType(.none)
SVProgressHUD.showInfo(withStatus: msg)

**Comment by Agent-4** [comment]
+ (void)setFont:(nonnull UIFont*)font;  Use this method.

**Comment by honkmaster** [comment]
@Agent-4 is right.
