### ISSUE TITLE
SVProgressHUD is not adapted to ios13.0

### ISSUE THREAD

**Issue by ChinaTzone** [SVProgressHUD/SVProgressHUD#985]
When the system version is ios13.0, its location will not be in play.

**Comment by nickthedude** [comment]
bump

**Comment by wutao66** [comment]
bump

**Comment by wl199452** [comment]
find  “- (UILabel *)stringLabel {” in 835 line ，modify " if(!_stringLabel.superview) " to "   if((!_stringLabel.superview) || (_stringLabel.frame.size.width != 0))"

**Comment by nickthedude** [comment]
> find “- (UILabel *)stringLabel {” in 835 line ，modify " if(!_stringLabel.superview) " to " if((!_stringLabel.superview) || (_stringLabel.frame.size.width != 0))"

Can you submit a PR with this change?

**Comment by iamjia** [comment]
> find “- (UILabel *)stringLabel {” in 835 line ，modify " if(!_stringLabel.superview) " to " if((!_stringLabel.superview) || (_stringLabel.frame.size.width != 0))"

虽然不懂为什么这么改，但是同理 图像也需要 if(!_imageView.superview || (_stringLabel.frame.size.width != 0))

**Comment by thienthancuagio** [comment]
SVProgressHUD display not center screen.

**Comment by RengeRenge** [comment]
1. create a class to save app window 
<img width="449" alt="QQ20190927-182037@2x" src="https://user-images.githubusercontent.com/14158970/65762410-874cc000-e153-11e9-839d-ad6768f3daf9.png">

```objective-c
- (void)startRootViewController:(UIWindow *)window {
    self.window = window;
    window.rootViewController = [[MyTabbarViewController alloc] init];
    // TODO: Init Your View or Do Somethings
}
```

2. overwrite - (UIWindow *)window;  in AppDelegate.m
<img width="378" alt="QQ20190927-182210@2x" src="https://user-images.githubusercontent.com/14158970/65762514-c4b14d80-e153-11e9-9da7-790c56a64190.png">

3. init rootViewController with window in AppDelegate.m or SceneDelegate.m

- AppDelegate.m
```objective-c
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
    if (@available(iOS 13, *)) {
        
    } else {
        self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
        [self.window makeKeyAndVisible];

        [[AppLaunchHandler shared] startRootViewController:self.window];
    }
    return YES;
}
```

- SceneDelegate.m
```objective-c
- (void)scene:(UIScene *)scene willConnectToSession:(UISceneSession *)session options:(UISceneConnectionOptions *)connectionOptions  API_AVAILABLE(ios(13.0)) {
    self.window = [[UIWindow alloc] initWithWindowScene:(UIWindowScene *)scene];
    [self.window makeKeyAndVisible];
    
    [[AppLaunchHandler shared] startRootViewController:self.window];
}
```

**Comment by zhufengyi01** [comment]
> if(!_imageView.superview || (_stringLabel.frame.size.width != 0))



> > find “- (UILabel *)stringLabel {” in 835 line ，modify " if(!_stringLabel.superview) " to " if((!_stringLabel.superview) || (_stringLabel.frame.size.width != 0))"
> 
> 虽然不懂为什么这么改，但是同理 图像也需要 if(!_imageView.superview || (_imageView.frame.size.width != 0))
下面的图片应该是(_imageView.frame.size.width != 0))吧

**Comment by manmal** [comment]
In the SceneDelegate, set the newly connected UIWindow to the AppDelegate:

`(UIApplication.shared.delegate as? AppDelegate)?.self.window = window`

**Comment by mithyer** [comment]
> find “- (UILabel *)stringLabel {” in 835 line ，modify " if(!_stringLabel.superview) " to " if((!_stringLabel.superview) || (_stringLabel.frame.size.width != 0))"

I think changing to this one is better:
`[_stringLabel removeFromSuperview];`

**Comment by chimingzi** [comment]
> 1. create a class to save app window
> 
> <img alt="QQ20190927-182037@2x" width="449" src="https://user-images.githubusercontent.com/14158970/65762410-874cc000-e153-11e9-839d-ad6768f3daf9.png">
> 
> ```objc
> - (void)startRootViewController:(UIWindow *)window {
>     self.window = window;
>     window.rootViewController = [[MyTabbarViewController alloc] init];
>     // TODO: Init Your View or Do Somethings
> }
> ```
> 
> 1. overwrite - (UIWindow *)window  in AppDelegate.m
> 
> <img alt="QQ20190927-182210@2x" width="378" src="https://user-images.githubusercontent.com/14158970/65762514-c4b14d80-e153-11e9-9da7-790c56a64190.png">
> 
> Because SVProgressHUD use
> 
> ```objc
> [[[UIApplication sharedApplication] delegate] window]
> ```
> 
> to get window
> 
> 1. init rootViewController with window in AppDelegate.m or SceneDelegate.m
> 
> * AppDelegate.m
> 
> ```objc
> - (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
>     if (@available(iOS 13, *)) {
>         
>     } else {
>         self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
>         [self.window makeKeyAndVisible];
> 
>         [[AppLaunchHandler shared] startRootViewController:self.window];
>     }
>     return YES;
> }
> ```
> 
> * SceneDelegate.m
> 
> ```objc
> - (void)scene:(UIScene *)scene willConnectToSession:(UISceneSession *)session options:(UISceneConnectionOptions *)connectionOptions  API_AVAILABLE(ios(13.0)) {
>     self.window = [[UIWindow alloc] initWithWindowScene:(UIWindowScene *)scene];
>     [self.window makeKeyAndVisible];
>     
>     [[AppLaunchHandler shared] startRootViewController:self.window];
> }
> ```
> 
> @thienthancuagio
> @nickthedude
> @ChinaTzone

It works! Thanks a lot for sharing.
And it's a very good way for adapting to iOS 13's SceneDelegate and iOS12's AppDelegate.One codes-line instead of two UIWindow create and initialize code-lines.

While,there's some issue here. In AppDelegate's 
> ```objc
>  - (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
> ```

**[self.window ] will bring infinite-loop error.**
Solution down below:
> ```objc
> - (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
>     if(@available (iOS 13,*))
>         return YES;
>     else
 >    {
>         UIWindow* window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
 >        [[AppLaunchHandler SharedInstance] startRootViewController:window];
 >    }
 >    return YES;
> }
>```

**Comment by iHardikTrivedi** [comment]
Try this solution:
[[SOLUTION]](https://github.com/SVProgressHUD/SVProgressHUD/issues/1013#issuecomment-567335032)

**Comment by sagarkhakhar** [comment]
> In the SceneDelegate, set the newly connected UIWindow to the AppDelegate:
> 
> `(UIApplication.shared.delegate as? AppDelegate)?.self.window = window`

Thanks @manmal it worked now in ios 13 it is displayed in center.
