### ISSUE TITLE
iOS13 部分时候弹出文字不显示，只显示一个黑色框。

### ISSUE THREAD

**Issue by YeaLink89** [SVProgressHUD/SVProgressHUD#987]
iOS13 部分时候弹出文字不显示，只显示一个黑色框。

**Comment by CalmHeart** [comment]
你用的是最新版本的SVProgressHUD吗，可以尝试更新到最新版本试一试......

**Comment by fb2012** [comment]
是的，第一次有文字，第二次以后 都没有文字。只显示一个框。已更新最新版 pod  。应该是bug

**Comment by fb2012** [comment]
![image](https://user-images.githubusercontent.com/6244804/66807360-81304f00-ef5b-11e9-8283-91a5cf992c90.png)
fu附件图

**Comment by YeaLink89** [comment]
> 你用的是最新版本的SVProgressHUD吗，可以尝试更新到最新版本试一试......

使用的版本是SVProgressHUD (2.2.5)

**Comment by yuZhongZhao** [comment]
mark , same issue :(

**Comment by yuZhongZhao** [comment]
https://github.com/SVProgressHUD/SVProgressHUD/issues/974

**Comment by sharlockk** [comment]
same issue :(

**Comment by newandroid** [comment]
same issue

**Comment by 275767099** [comment]
> ![图片](https://user-images.githubusercontent.com/6244804/66807360-81304f00-ef5b-11e9-8283-91a5cf992c90.png)
> fu附件图

解决了没 我也遇见了

**Comment by 275767099** [comment]
> iOS13部分时候弹出文字不显示，只显示一个黑色框。

解决了没

**Comment by iHardikTrivedi** [comment]
Try this solution:
[[SOLUTION]](https://github.com/SVProgressHUD/SVProgressHUD/issues/1013#issuecomment-567335032)

**Comment by AlianOL** [comment]
> Try this solution:
> [[SOLUTION]](https://github.com/SVProgressHUD/SVProgressHUD/issues/1013#issuecomment-567335032)

so,how to solve this  with object-c?

**Comment by AlianOL** [comment]
> Try this solution:
> [[SOLUTION]](https://github.com/SVProgressHUD/SVProgressHUD/issues/1013#issuecomment-567335032)

but it doesn't work

**Comment by honkmaster** [comment]
Please provide an english error description, otherwise this issue will be closed.

**Comment by liric28** [comment]
I solved the problem in line 733

- (void)moveToPoint:(CGPoint)newCenter rotateAngle:(CGFloat)angle {
    self.hudView.transform = self.kTransform;
    if (self.containerView) {
        self.hudView.center = self.containerView.center;
    } else {
        self.hudView.center = CGPointMake(newCenter.x + self.offsetFromCenter.horizontal, newCenter.y + self.offsetFromCenter.vertical);
        NSLog(@"---------> %@", NSStringFromCGRect(self.hudVibrancyView.frame));
        // 修复转屏 x轴坐标异常 --> {{733007751850.66663, -0.33333333333333215}, {106, 44}}
        CGRect frame = self.hudVibrancyView.frame;
        frame.origin.x = 0;
        self.hudVibrancyView.frame = frame;
    }
}

**Comment by AlianOL** [comment]
您好：
      傩送已经收到，谢谢啦
