### ISSUE TITLE
[[[UIApplication sharedApplication] delegate] window]

### ISSUE THREAD

**Issue by 993695620** [SVProgressHUD/SVProgressHUD#988]
If there's SceneDelegate in the project, there's no window in AppDelegate, crash

**Comment by maxkazakov** [comment]
@993695620 Hey! Your AppDelegate must have a field
`var window: UIWindow?`
Pay attention that the field is optional; if you've got a non-optional app still crashes.

**Comment by iHardikTrivedi** [comment]
Try this solution:
[[SOLUTION]](https://github.com/SVProgressHUD/SVProgressHUD/issues/1013#issuecomment-567335032)
