### ISSUE TITLE
SVProgressHUD does not work with newly created Xcode11 projects.

### ISSUE THREAD

**Issue by takep2** [SVProgressHUD/SVProgressHUD#990]
Steps to reproduce.
1. Create new single app project by Xcode11(use Storyboard).
2. Install SVProgressHUD by CocoaPods.
3. Simply execute `SVProgressHUD.show()`

Then the app aborts like this:

```
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[SVHUDTest.AppDelegate window]: unrecognized selector sent to instance 0x6000027342a0'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff23baa1ee __exceptionPreprocess + 350
	1   libobjc.A.dylib                     0x00007fff50864b20 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff23bcb154 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   UIKitCore                           0x00007fff475a6e79 -[UIResponder doesNotRecognizeSelector:] + 302
	4   CoreFoundation                      0x00007fff23baed16 ___forwarding___ + 838
	5   CoreFoundation                      0x00007fff23bb10f8 _CF_forwarding_prep_0 + 120
	6   SVProgressHUD                       0x0000000109bea9d2 __27+[SVProgressHUD sharedView]_block_invoke + 130
	7   libdispatch.dylib                   0x0000000109c1ed6c _dispatch_client_callout + 8
	8   libdispatch.dylib                   0x0000000109c202bb _dispatch_once_callout + 66
	9   SVProgressHUD                       0x0000000109bea928 +[SVProgressHUD sharedView] + 136
	10  SVProgressHUD                       0x0000000109bebecd +[SVProgressHUD showProgress:status:] + 61
	11  SVProgressHUD                       0x0000000109bebca4 +[SVProgressHUD showWithStatus:] + 68
	12  SVProgressHUD                       0x0000000109bebbb5 +[SVProgressHUD show] + 37
```

The reason is that the project created in Xcode11 does not have a window property in AppDelegate.

Workaround.
1.Add window property in AppDelegate
```
var window: UIWindow?
```

2.Add below code at `scene(_:willConnectTo:options)`method in SceneDelegate 

```
let appDelegate = UIApplication.shared.delegate as! AppDelegate
appDelegate.window = self.window
```

Then SVProgressHUD works well in newly created Xcode11 projects.

But, I hope SVProgressHUD can be used without any workaround.

**Comment by WGFcode** [comment]
Encounter the same problem, hope to adapt as soon as possible

**Comment by BhavinRanara21** [comment]
yes, facing same issue in xcode 11, working fine in xcode 10

**Comment by krasnyt** [comment]
Same here, iOS 13, Xcode 11. Any eta for solution?

**Comment by mertyertugrul** [comment]
I also have the same issue unfortunately.

**Comment by frkncngz** [comment]
You can this to your AppDelegate as a temporary solution:

```swift
lazy var window: UIWindow? = {
    return UIApplication.shared.windows.first
}()
```

**Comment by berarduc** [comment]
same problem here. ios 13 xcode 11.

**Comment by berarduc** [comment]
> You can add this to your AppDelegate as a temporary solution:
> 
> ```swift
> lazy var window: UIWindow? = {
>     return UIApplication.shared.windows.first
> }()
> ```

--> this does not work all by itself. Workaround quoted by takep2 works.

**Comment by ZM2Dev** [comment]
Your AppDelegate does not contain a window reference. Add a window variable in your AppDelegate

var window: UIWindow?
