### ISSUE TITLE
causing app to freeze because UI API called on a background thread on iphone xs, may be ios 13 related

### ISSUE THREAD

**Issue by olearyj234** [SVProgressHUD/SVProgressHUD#992]
For debugging purposes, I created a button and on tapped it calls SVProgressHUD.show() only. this is where i get the following error.

=================================================================
Main Thread Checker: UI API called on a background thread: -[UIApplication applicationState]
PID: 1002, TID: 255604, Thread name: com.apple.CoreMotion.MotionThread, Queue name: com.apple.root.default-qos.overcommit, QoS: 0
Backtrace:
4   libobjc.A.dylib                     0x00000001ed54f6f4 <redacted> + 56
5   CoreMotion                          0x00000001f3d52d7c CoreMotion + 294268
6   CoreMotion                          0x00000001f3d532ac CoreMotion + 295596
7   CoreMotion                          0x00000001f3d531bc CoreMotion + 295356
8   CoreMotion                          0x00000001f3d80ffc CoreMotion + 483324
9   CoreMotion                          0x00000001f3d81040 CoreMotion + 483392
10  CoreFoundation                      0x00000001ee2de98c <redacted> + 28
11  CoreFoundation                      0x00000001ee2de274 <redacted> + 276
12  CoreFoundation                      0x00000001ee2d9050 <redacted> + 972
13  CoreFoundation                      0x00000001ee2d8964 CFRunLoopRunSpecific + 452
14  CoreFoundation                      0x00000001ee2d9698 CFRunLoopRun + 84
15  CoreMotion                          0x00000001f3d809d4 CoreMotion + 481748
16  libsystem_pthread.dylib             0x00000001edf57908 <redacted> + 132
17  libsystem_pthread.dylib             0x00000001edf57864 _pthread_start + 48
18  libsystem_pthread.dylib             0x00000001edf5fdcc thread_start + 4
2019-10-10 14:17:16.653339-0400 myapp[1002:255604] [reports] Main Thread Checker: UI API called on a background thread: -[UIApplication applicationState]
PID: 1002, TID: 255604, Thread name: com.apple.CoreMotion.MotionThread, Queue name: com.apple.root.default-qos.overcommit, QoS: 0
Backtrace:
4   libobjc.A.dylib                     0x00000001ed54f6f4 <redacted> + 56
5   CoreMotion                          0x00000001f3d52d7c CoreMotion + 294268
6   CoreMotion                          0x00000001f3d532ac CoreMotion + 295596
7   CoreMotion                          0x00000001f3d531bc CoreMotion + 295356
8   CoreMotion                          0x00000001f3d80ffc CoreMotion + 483324
9   CoreMotion                          0x00000001f3d81040 CoreMotion + 483392
10  CoreFoundation                      0x00000001ee2de98c <redacted> + 28
11  CoreFoundation                      0x00000001ee2de274 <redacted> + 276
12  CoreFoundation                      0x00000001ee2d9050 <redacted> + 972
13  CoreFoundation                      0x00000001ee2d8964 CFRunLoopRunSpecific + 452
14  CoreFoundation                      0x00000001ee2d9698 CFRunLoopRun + 84
15  CoreMotion                          0x00000001f3d809d4 CoreMotion + 481748
16  libsystem_pthread.dylib             0x00000001edf57908 <redacted> + 132
17  libsystem_pthread.dylib             0x00000001edf57864 _pthread_start + 48
18  libsystem_pthread.dylib             0x00000001edf5fdcc thread_start + 4
(lldb) `

**Comment by iHardikTrivedi** [comment]
Try this solution:
[[SOLUTION]](https://github.com/SVProgressHUD/SVProgressHUD/issues/1013#issuecomment-567335032)
