### ISSUE TITLE
SVPHUD mask layer location point error, SVPHUD 菊花坐标不在中心的问题

### ISSUE THREAD

**Issue by wuyanzu3398** [SVProgressHUD/SVProgressHUD#998]
![解决前](http://chuantu.xyz/t6/702/1572420445x989499252.png)  
这是我遇到的问题.  
遮罩层失效,SVPHUDView跑到(0,0).原因是iOS13的window用[UIApplication   sharedApplication].keyWindow是获取不到的.  
因为iOS13window对象,是在SceneDelegate.h生成的.  
所以我在SceneDelegate.m加入了这么一句话:   
![解决后](http://chuantu.xyz/t6/702/1572420498x989559068.png)  
```objective-c
- (void)scene:(UIScene *)scene willConnectToSession:(UISceneSession *)session options:(UISceneConnectionOptions *)connectionOptions  API_AVAILABLE(ios(13.0)){
    //在这里手动创建新的window
    if (scene) {
        UIWindowScene *windowScene = (UIWindowScene *)scene; 
        self.window = [[UIWindow alloc] initWithWindowScene:windowScene];
        self.window.frame = CGRectMake(0, 0, [UIScreen mainScreen].bounds.size.width, [UIScreen mainScreen].bounds.size.height);
        // 临时解决svphud问题
        [UIApplication sharedApplication].delegate = windowScene.delegate;
    }
}  
```

**Comment by ZeKunLi** [comment]
`guard let windowScene = (scene as? UIWindowScene) else { return }
        self.window = UIWindow(windowScene: windowScene)
        self.window?.frame = CGRect(x: 0, y: 0, width: kScreenWidth, height: kScreenHeigth)
        UIApplication.shared.delegate = windowScene.delegate as? UIApplicationDelegate`

黑屏了

**Comment by honkmaster** [comment]
Please provide an full english error description, otherwise this issue will be closed.
